-- TOPIC-DWT-订单业主题宽表

drop table if exists julive_topic.topic_dwt_order_base;
create table if not exists julive_topic.topic_dwt_order_base(
clue_id                               bigint          comment '线索ID',
install_date                          string          comment 'APP激活日期:yyyy-MM-dd',
install_time                          string          comment 'APP激活时间',
create_date	                          string          comment '线索创建日期:yyyy-MM-dd',
create_time                           string          comment '线索创建时间',
distribute_date                       string          comment '上户日期:yyyy-MM-dd',
distribute_time                       string          comment '上户时间:yyyy-MM-dd HH:mm:ss',
first_see_date                        string          comment '首次带看日期:yyyy-MM-dd',
final_see_date                        string          comment '最后带看日期:yyyy-MM-dd',
first_subscribe_date                  string          comment '首次认购日期:yyyy-MM-dd',
final_subscribe_date                  string          comment '最后认购日期:yyyy-MM-dd',
first_sign_date                       string          comment '首次签约日期:yyyy-MM-dd',
final_sign_date                       string          comment '最后签约日期:yyyy-MM-dd',
clue_num                              int             comment '线索量',
distribute_num                        int             comment '上户量',
see_num                               int             comment '带看量',
see_project_num                       int             comment '带看楼盘量',
subscribe_num                         int             comment '认购量:含退、含外联',
subscribe_coop_num                    int             comment '净认购量:不含退、不含外联',
subscribe_contains_cancel_ext_num     int             comment '认购量-含退、含外联(同subscribe_num属性)',
subscribe_contains_ext_num            int             comment '认购量(不含退)-含外联',
subscribe_contains_ext_amt            decimal(19,4)   comment '认购(不含退)-含外联GMV',
subscribe_contains_ext_income         decimal(19,4)   comment '认购(不含退)-含外联佣金',
subscribe_contains_cancel_ext_amt     decimal(19,4)   comment '认购-含退、含外联GMV',
subscribe_contains_cancel_ext_income  decimal(19,4)   comment '认购-含退、含外联收入',
sign_num                              int             comment '签约量:含退、含外联',
call_duration                         int             comment '线索通话时长(秒)',
call_num                              int             comment '线索通话次数',
first_call_duration                   int             comment '线索首次通话时长(秒)',
distribute_call_duration              int             comment '上户通话时长(秒)',
clue_id_list                          string          comment '线索ID明细列表',
distribute_id_list                    string          comment '上户ID明细列表',
see_id_list                           string          comment '带看ID明细列表',
see_project_id_list                   string          comment '带看楼盘ID明细列表',
clue_see_list                         string          comment '产生带看的线索ID明细列表',
subscribe_contains_cancel_ext_id_list string          comment '含退含外联认购ID明细列表',
clue_subscribe_list                   string          comment '产生认购的线索ID明细列表',
sign_contains_cancel_ext_id_list      string          comment '含退含外联签约ID明细列表',
clue_sign_list                        string          comment '产生签约的线索ID明细列表',
clue_see_num                          int             comment '产生带看的线索量',
clue_subscribe_num                    int             comment '产生认购的线索量',
clue_sign_num                         int             comment '产生签约的线索量',
distribute_probs                      decimal(19,4)   comment '预测上户质量分',
clue_score                            decimal(19,4)   comment '线索质量分',
intent_low_num                        int             comment '产生签约的线索量',
etl_time                              string          comment '任务执行时间：yyyy-MM-dd HH:mm:ss'
) comment 'TOPIC-DWT-订单业主题宽表' 
stored as parquet 
;
