drop table if exists julive_topic.topic_lable_user_lifecycle_base;
create table julive_topic.topic_lable_user_lifecycle_base(
-- 基础标签 
global_id                                     string comment '用户ID',
product_id                                    string comment '端ID',
comjia_unique_id                              string comment '根据用户设备生成的标识',
julive_id                                     string comment '居理ID',
user_name                                     string comment '用户名称',
user_mobile                                   string comment '用户手机号',
emp_id                                        string comment '员工id',
emp_name                                      string comment '员工姓名', 
ip_city                                       string comment 'IP解析的市',
channel_id                                    string comment '渠道类信息',
select_city                                   string comment 'C端城市',
manufacturer                                  string comment '手机品类',
app_version                                   string comment 'app版本号',
os_system                                     string comment '手机系统',
os_version                                    string comment '手机系统版本',
is_close                                      string comment '是否关单1-关，0-未关',
latest_distribute_date                        string comment '关单时间',
comjia_unique_id_valid_status                 INT    COMMENT 'APP的comjia_unique_id的有效状态，1有效2无效，更新自打开app和push通道反馈',
comjia_unique_id_valid_status_update_datetime BIGINT COMMENT 'comjia_unique_id_valid_status的更新时间',
-- 行为标签 
first_visit_daytime                           string comment '首次访问时间',
final_visit_daytime                           string comment '最后一次访问时间',
visit_day_cnt                                 string comment '总计来访天数',
day_diff_from_last_visit                      string comment '最后一次访问距今天数',
is_7day_live                                  string comment '7日内是否活跃',
is_30day_live                                 string comment '30日内是否活跃',
visit_days_cnt_last_30day                     string comment '最近30天来访天数',
visit_session_cnt_last_30day                  string comment '最近30天来访次数(session级别)',
visit_duration_last_30day                     string comment '最近30天来访总时长',
visit_cnt_per_day                             string comment '日均来访次数',
visit_duration_per_day                        string comment '日均来访时长',
frequent_visit_hour_1st                       string comment '来访频度1st的hour(0-23)',
frequent_visit_hour_2nd                       string comment '来访频度2nd的hour(0-23)',
frequent_visit_hour_3rd                       string comment '来访频度3rd的hour(0-23)',
-- 偏好标签                 
fav_project                                   string comment '偏好楼盘(global_id, select_city维度)',  
fav_house_type                                string comment '偏好房型(global_id, select_city维度)',
district_name                                 string comment '偏好地区(global_id, select_city维度)',
project_type                                  string comment '偏好楼盘类型(global_id, select_city维度)',
order_house_type                              string comment '订单信息汇总: 偏好房型',
order_project_type                            string comment '订单信息汇总: 偏好楼盘类型',
-- 统计标签                 
-- 线下关键节点标签                 
is_gen_clue                                   string comment '线索标识',
is_distribute                                 string comment '上户标识',
is_see                                        string comment '带看标识',
is_subscribe                                  string comment '认购标识',
is_sign                                       string comment '签约标识',
video_play_cnt                                string comment 'C端版块:一般视频类播放次数',
video_play_duration                           string comment 'C端版块:一般视频类播放时长',
call_video_cnt                                string comment 'C端版块:视频看房次数',
call_video_duration                           string comment 'C端版块:视频看房时长',
activity_cnt                                  string comment 'C端版块: 参加活动次数',
qa_ask_cnt                                    string comment 'C端版块: 问问提问数',
qa_click_cnt                                  string comment 'C端版块: 问问点击数',
qa_view_duration                              string comment 'C端版块: 问问浏览数',
info_article_cnt                              string comment 'C端版块: 情报局文章点击数',
info_video_cnt                                string comment 'C端版块: 情报局视频点击数',
info_project_cnt                              string comment 'C端版块: 情报局楼盘点击数',
info_question_cnt                             string comment 'C端版块: 情报局问答点击数',
leave_phone_cnt                               string comment 'C端版块: 留电次数',
service_chat_cnt                              string comment 'C端版块: 在线咨询次数',
service_chat_duration                         string comment 'C端版块: 在线咨询时长',
booking_cnt                                   string comment 'C端版块: 在线订房数',
submit_question_cnt                           string comment 'C端: 问题提交次数',
project_comment_cnt                           string comment 'C端: 楼盘平均数',
send_comment_cnt                              string comment 'C端: 一般评论数',
share_cnt                                     string comment 'C端: 楼盘share次数',
like_cnt                                      string comment 'C端: 楼盘like数',
love_cnt                                      string comment 'C端: 楼盘love数',
follow_cnt                                    string comment 'C端: 楼盘follow数',
collect_cnt                                   string comment 'C端: 楼盘collect数',
query_cnt                                     string comment 'C端: 搜索数',
view_cnt                                      string comment 'C端: 页面浏览次数',
real_estate_cnt                               string comment '手机房产类App数量',  
real_estate_list                              string comment '手机房产类App列表',
house_decoration_cnt                          string comment '手机装修类App数量',
house_decoration_list                         string comment '手机装修类App列表',
car_cnt                                       string comment '手机汽车类App数量',
car_list                                      string comment '手机汽车类App列表',
marriage_cnt                                  string comment '手机婚恋类App数量',
marriage_list                                 string comment '手机婚恋类App列表',
mombaby_list                                  string comment '手机孕婴类App列表',
mombaby_cnt                                   string comment '手机孕婴类App数量',
investment_list                               string comment '手机金融理财类App列表',
investment_cnt                                string comment '手机金融理财类App数量',
order_status                                  string comment '订单信息汇总: 状态',
order_decision                                string comment '订单信息汇总: 线索质量decision',
order_score                                   string comment '订单信息汇总: 线索质量分',
order_urgent                                  string comment '订单信息汇总: 购房紧迫度',
order_district_id                             string comment '订单信息汇总: 区域ID',
order_pref_zone                               string comment '订单信息汇总: 倾向区域',
order_interest_project                        string comment '订单信息汇总: 兴趣楼盘ID',
order_interest_project_name                   string comment '订单信息汇总: 兴趣楼盘名称',
order_recommend_project                       string comment '订单信息汇总: 推荐楼盘ID',
order_recommend_project_name                  string comment '订单信息汇总: 推荐楼盘名称',
first_register_date                           string comment 'julive_id注册时间',
create_date_min                               string comment '线索创建日期-min',  
create_date_max                               string comment '线索创建日期-max',
distribute_date_min                           string comment '上户日期-min',
distribute_date_max                           string comment '上户日期-max',
first_see_date_min                            string comment '首次带看日期-min',
first_see_date_max                            string comment '首次带看日期-max',
first_subscribe_date_min                      string comment '首次认购日期-min',
first_subscribe_date_max                      string comment '首次认购日期-max',
first_sign_date_min                           string comment '首次签约日期-min',
first_sign_date_max                           string comment '首次签约日期-max',
clue_num                                      string comment '线索量',
distribute_num                                string comment '上户量',
see_num                                       string comment '带看量',
see_project_num                               string comment '带看楼盘量',
subscribe_num                                 string comment '认购量',
sign_num                                      string comment '签约量',
call_duration                                 string comment '线索通话时长(秒)',
call_num                                      string comment '线索通话次数',
clue_see_num                                  string comment '产生带看的线索量',
clue_subscribe_num                            string comment '产生认购的线索量',
clue_sign_num                                 string comment '产生签约的线索量',
pc_day_avg                                    string comment '日均点击楼盘卡片次数',
htc_day_avg                                   string comment '日均点击户型卡片次数',
se_day_avg                                    string comment '日均搜索次数',
fp_day_avg                                    string comment '日均楼盘过滤次数',
cp_cont_pv                                    string comment '连续点击楼盘卡片总次数',
cp_cont_days                                  string comment '连续点击楼盘卡片天数',
htc_cont_pv                                   string comment '连续点击户型卡片总次数',
htc_cont_days                                 string comment '连续点击户型卡片天数',
se_cont_pv                                    string comment '连续搜索总次数',
se_cont_days                                  string comment '连续搜索天数',
fp_cont_pv                                    string comment '连续楼盘过滤总次数',
fp_cont_days                                  string comment '连续楼盘过滤天数'
) comment '用户核心指标表' 
stored as parquet 
;