set hive.execution.engine=spark;
set spark.app.name=topic_lable_user_lifecycle_pcm_rating;
set spark.yarn.queue=etl;
insert overwrite table julive_topic.topic_lable_user_lifecycle_pcm_rating

select
tmp.global_id,
tmp.julive_id,
tmp.user_name,  
tmp.user_mobile,
tmp.select_city,
tmp.emp_id,     
tmp.emp_name,
tmp.is_close,
tmp.latest_distribute_date,
tmp.first_visit_daytime,     
tmp.final_visit_daytime,     
tmp.is_7day_live,            
tmp.is_30day_live,           
tmp.create_date_min,         
tmp.create_date_max,         
tmp.distribute_date_min,     
tmp.distribute_date_max,     
tmp.first_see_date_min,      
tmp.first_see_date_max,      
tmp.first_subscribe_date_min,
tmp.first_subscribe_date_max,
tmp.first_sign_date_min,     
tmp.first_sign_date_max,                      
tmp.visit_day_cnt_rating,        
tmp.visit_cnt_per_day_rating,    
tmp.visit_duration_per_day_rating,
tmp.pc_day_avg_rating,           
tmp.htc_day_avg_rating,          
tmp.visit_hour_rating,           
tmp.call_video_cnt_rating ,      
tmp.call_video_duration_rating,  
tmp.cp_cont_days_rating,         
tmp.htc_cont_days_rating,        
tmp.se_cont_days_rating,         
tmp.fp_cont_pv_rating,           
tmp.cp_cont_pv_rating,           
tmp.htc_cont_pv_rating,          
tmp.se_cont_pv_rating,           
tmp.fp_cont_days_rating,         
tmp.activity_cnt_rating,         
tmp.qa_ask_cnt_rating,           
tmp.qa_click_cnt_rating,         
tmp.qa_view_duration_rating,     
tmp.info_article_cnt_rating,     
tmp.info_video_cnt_rating,       
tmp.info_project_cnt_rating,     
tmp.info_question_cnt_rating,    
tmp.leave_phone_cnt_rating,      
tmp.service_chat_cnt_rating,     
tmp.service_chat_duration_rating,
tmp.booking_cnt_rating,          
tmp.submit_question_cnt_rating,  
tmp.project_comment_cnt_rating,  
tmp.send_comment_cnt_rating,     
tmp.share_cnt_rating,            
tmp.like_cnt_rating,             
tmp.love_cnt_rating,             
tmp.follow_cnt_rating,           
tmp.collect_cnt_rating,          
tmp.real_estate_cnt_rating,      
tmp.house_decoration_cnt_rating, 
tmp.car_cnt_rating,              
tmp.marriage_cnt_rating,         
tmp.mombaby_cnt_rating,          
tmp.investment_cnt_rating,
round(tmp.visit_day_cnt_rating+tmp.visit_cnt_per_day_rating+tmp.visit_duration_per_day_rating+tmp.pc_day_avg_rating+tmp.htc_day_avg_rating+         
tmp.visit_hour_rating+tmp.call_video_cnt_rating+tmp.call_video_duration_rating+tmp.cp_cont_days_rating+tmp.htc_cont_days_rating+tmp.se_cont_days_rating+ 
tmp.fp_cont_pv_rating+tmp.cp_cont_pv_rating+tmp.htc_cont_pv_rating+tmp.se_cont_pv_rating+tmp.fp_cont_days_rating+tmp.activity_cnt_rating+        
tmp.qa_ask_cnt_rating+tmp.qa_click_cnt_rating+tmp.qa_view_duration_rating+tmp.info_article_cnt_rating+tmp.info_video_cnt_rating+tmp.info_project_cnt_rating+
tmp.info_question_cnt_rating+tmp.leave_phone_cnt_rating+tmp.service_chat_cnt_rating+    
tmp.service_chat_duration_rating+tmp.booking_cnt_rating+tmp.submit_question_cnt_rating+tmp.project_comment_cnt_rating+ 
tmp.send_comment_cnt_rating+tmp.share_cnt_rating+tmp.like_cnt_rating+tmp.love_cnt_rating+tmp.follow_cnt_rating+tmp.collect_cnt_rating+
tmp.real_estate_cnt_rating+     
tmp.house_decoration_cnt_rating+
tmp.car_cnt_rating+             
tmp.marriage_cnt_rating+        
tmp.mombaby_cnt_rating+         
tmp.investment_cnt_rating,2)       as total_points
from
( 
select 
t1.global_id                          as global_id,
max(t1.julive_id)                     as julive_id, 
max(t1.select_city)                   as select_city,
max(t1.user_name)                     as user_name,                  
max(t1.user_mobile)                   as user_mobile,                  
max(t1.emp_id)                        as emp_id,                  
max(t1.emp_name)                      as emp_name,                     
max(t1.is_close)                      as is_close,
max(t1.latest_distribute_date)        as latest_distribute_date,
min(t1.first_visit_daytime)           as first_visit_daytime,         
min(t1.final_visit_daytime)           as final_visit_daytime,         
max(t1.is_7day_live)                  as is_7day_live,                          
max(t1.is_30day_live)                 as is_30day_live,                        
min(t1.create_date_min)               as create_date_min,         
max(t1.create_date_max)               as create_date_max,         
min(t1.distribute_date_min)           as distribute_date_min,     
max(t1.distribute_date_max)           as distribute_date_max,     
min(t1.first_see_date_min)            as first_see_date_min,      
max(t1.first_see_date_max)            as first_see_date_max,      
min(t1.first_subscribe_date_min)      as first_subscribe_date_min,
max(t1.first_subscribe_date_max)      as first_subscribe_date_max,
min(t1.first_sign_date_min)           as first_sign_date_min,     
max(t1.first_sign_date_max)           as first_sign_date_max,     
--浏览模块
max(t1.visit_day_cnt_rating)          as visit_day_cnt_rating,         
max(t1.visit_cnt_per_day_rating)      as visit_cnt_per_day_rating,     
max(t1.visit_duration_per_day_rating)  as visit_duration_per_day_rating,
max(t1.pc_day_avg_rating)             as pc_day_avg_rating,            
max(t1.htc_day_avg_rating)            as htc_day_avg_rating,           
max(t1.visit_hour_rating)             as visit_hour_rating,            
max(t1.call_video_cnt_rating)         as call_video_cnt_rating,        
max(t1.call_video_duration_rating)    as call_video_duration_rating,   
max(t1.cp_cont_days_rating)           as cp_cont_days_rating,          
max(t1.htc_cont_days_rating)          as htc_cont_days_rating,         
max(t1.se_cont_days_rating)           as se_cont_days_rating,          
max(t1.fp_cont_pv_rating)             as fp_cont_pv_rating,            
max(t1.cp_cont_pv_rating)             as cp_cont_pv_rating,            
max(t1.htc_cont_pv_rating)            as htc_cont_pv_rating,           
max(t1.se_cont_pv_rating)             as se_cont_pv_rating,            
max(t1.fp_cont_days_rating)           as fp_cont_days_rating,            
--c端行为 
max(t1.activity_cnt_rating)           as activity_cnt_rating,         
max(t1.qa_ask_cnt_rating)             as qa_ask_cnt_rating,           
max(t1.qa_click_cnt_rating)           as qa_click_cnt_rating,         
max(t1.qa_view_duration_rating)       as qa_view_duration_rating,     
max(t1.info_article_cnt_rating)       as info_article_cnt_rating,     
max(t1.info_video_cnt_rating)         as info_video_cnt_rating,       
max(t1.info_project_cnt_rating)       as info_project_cnt_rating,     
max(t1.info_question_cnt_rating)      as info_question_cnt_rating,    
max(t1.leave_phone_cnt_rating)        as leave_phone_cnt_rating,      
max(t1.service_chat_cnt_rating)       as service_chat_cnt_rating,     
max(t1.service_chat_duration_rating)  as service_chat_duration_rating,
max(t1.booking_cnt_rating)            as booking_cnt_rating,          
max(t1.submit_question_cnt_rating)    as submit_question_cnt_rating,  
max(t1.project_comment_cnt_rating)    as project_comment_cnt_rating,  
max(t1.send_comment_cnt_rating)       as send_comment_cnt_rating,     
max(t1.share_cnt_rating)              as share_cnt_rating,            
max(t1.like_cnt_rating)               as like_cnt_rating,             
max(t1.love_cnt_rating)               as love_cnt_rating,             
max(t1.follow_cnt_rating)             as follow_cnt_rating,           
max(t1.collect_cnt_rating)            as collect_cnt_rating,          
--app  
max(t1.real_estate_cnt_rating)        as real_estate_cnt_rating,      
max(t1.house_decoration_cnt_rating)   as house_decoration_cnt_rating, 
max(t1.car_cnt_rating)                as car_cnt_rating,             
max(t1.marriage_cnt_rating)           as marriage_cnt_rating,        
max(t1.mombaby_cnt_rating)            as mombaby_cnt_rating,          
max(t1.investment_cnt_rating)         as investment_cnt_rating       
from (
select 
t.global_id,        
t.product_id,       
t.comjia_unique_id, 
t.julive_id, 
t.user_name,  
t.user_mobile,
t.emp_id,     
t.emp_name,        
t.ip_city,          
t.channel_id,       
t.select_city,
t.is_close,
t.latest_distribute_date,
t.first_visit_daytime,     
t.final_visit_daytime,     
t.is_7day_live,            
t.is_30day_live,           
t.create_date_min,         
t.create_date_max,         
t.distribute_date_min,     
t.distribute_date_max,     
t.first_see_date_min,      
t.first_see_date_max,      
t.first_subscribe_date_min,
t.first_subscribe_date_max,
t.first_sign_date_min,     
t.first_sign_date_max,     
--1总计来访天数得分
if(t.visit_day_cnt<=2 and t.visit_day_cnt>=0,1.8, 
  if(t.visit_day_cnt>2 and t.visit_day_cnt <=5,3.6,
    if(t.visit_day_cnt>5 and t.visit_day_cnt<=8,5.4,
      if(t.visit_day_cnt>8 and t.visit_day_cnt <=11,7.2,
        if(t.visit_day_cnt>11,9.0,0))))) as visit_day_cnt_rating,
--2日均来访次数得分
if(t.visit_cnt_per_day<=1 and t.visit_cnt_per_day>0,0.6, 
  if(t.visit_cnt_per_day>1 and t.visit_cnt_per_day <=2,1.2,
    if(t.visit_cnt_per_day>2 and t.visit_cnt_per_day<=3,1.8,
      if(t.visit_cnt_per_day>3 and t.visit_cnt_per_day <=4,2.4,
        if(t.visit_cnt_per_day>=5,3.0,0))))) as visit_cnt_per_day_rating,
--3日均来访时长得分 
if(t.visit_duration_per_day<=150 and t.visit_duration_per_day>0,0.6, 
  if(t.visit_duration_per_day>150 and t.visit_duration_per_day <=400,1.2,
    if(t.visit_duration_per_day>400 and t.visit_duration_per_day<=450,1.8,
      if(t.visit_duration_per_day>450 and t.visit_duration_per_day <=550,2.4,
        if(t.visit_duration_per_day>550,3.0,0))))) as visit_duration_per_day_rating,
--4日均点击楼盘卡片次数得分 
if(t.pc_day_avg<=2 and t.pc_day_avg>0,0.6, 
  if(t.pc_day_avg>2 and t.pc_day_avg <=3,1.2,
    if(t.pc_day_avg>3 and t.pc_day_avg<=4,1.8,
      if(t.pc_day_avg>4 and t.pc_day_avg <=5,2.4,
        if(t.pc_day_avg>5,3.0,0))))) as pc_day_avg_rating, 
--5日均点击户型卡片次数得分
if(t.htc_day_avg<=1 and t.htc_day_avg>0,0.6, 
  if(t.htc_day_avg>1 and t.htc_day_avg <=2,1.2,
    if(t.htc_day_avg>2 and t.htc_day_avg<=3,1.8,
      if(t.htc_day_avg>3 and t.htc_day_avg <=4,2.4,
        if(t.htc_day_avg>4,3.0,0))))) as htc_day_avg_rating,       
--6日均搜索次数得分
if(t.se_day_avg<=1 and t.se_day_avg>0,0.6, 
  if(t.se_day_avg>1 and t.se_day_avg <=2,1.2,
    if(t.se_day_avg>2 and t.se_day_avg<=3,1.8,
      if(t.se_day_avg>3 and t.se_day_avg <=4,2.4,
        if(t.se_day_avg>4,3.0,0))))) as se_day_avg_rating,
--7日均楼盘过滤次数得分
if(t.fp_day_avg<=1 and t.fp_day_avg>0,0.6, 
  if(t.fp_day_avg>1 and t.fp_day_avg <=2,1.2,
    if(t.fp_day_avg>2 and t.fp_day_avg<=3,1.8,
      if(t.fp_day_avg>3 and t.fp_day_avg <=4,2.4,
        if(t.fp_day_avg>4,3.0,0))))) as fp_day_avg_rating,
--8浏览时间
if(t.frequent_visit_hour_1st in(8,9,12,20,21,22,23) 
or t.frequent_visit_hour_2nd in (8,9,12,20,21,22,23)
or t.frequent_visit_hour_3rd in (8,9,12,20,21,22,23),3.0,1.0) as visit_hour_rating,

--8视频浏览次数
if(t.call_video_cnt<=10 and t.call_video_cnt>0,0.3, 
  if(t.call_video_cnt>10 and t.call_video_cnt <=15,0.6,
    if(t.call_video_cnt>15 and t.call_video_cnt<=20,0.9,
      if(t.call_video_cnt>20 and t.call_video_cnt <=30,1.2,
        if(t.call_video_cnt>30,1.5,0))))) as call_video_cnt_rating,
--9视频浏览时长
if(t.call_video_duration<=1000 and t.call_video_duration>0,0.3, 
  if(t.call_video_duration>1000 and t.call_video_duration <=2000,0.6,
    if(t.call_video_duration>2000 and t.call_video_duration<=2500,0.9,
      if(t.call_video_duration>2500 and t.call_video_duration <=4000,1.2,
        if(t.call_video_duration>4000,1.5,0))))) as call_video_duration_rating,
--10连续n天点击楼盘 
if(t.cp_cont_days<=3 and t.cp_cont_days>0,0.3, 
  if(t.cp_cont_days>3 and t.cp_cont_days <=7,0.6,
    if(t.cp_cont_days>7 and t.cp_cont_days<=8,0.9,
      if(t.cp_cont_days>8 and t.cp_cont_days <=10,1.2,
        if(t.cp_cont_days>10,1.5,0))))) as cp_cont_days_rating,
--11连续n天点击户型
if(t.htc_cont_days<=1 and t.htc_cont_days>0,0.3, 
  if(t.htc_cont_days>1 and t.htc_cont_days <=2,0.6,
    if(t.htc_cont_days>2 and t.htc_cont_days<=3,0.9,
      if(t.htc_cont_days>3 and t.htc_cont_days <=5,1.2,
        if(t.htc_cont_days>5,1.5,0))))) as htc_cont_days_rating, 
--12
if(t.se_cont_days<=1 and t.se_cont_days>0,0.3, 
  if(t.se_cont_days>1 and t.se_cont_days <=2,0.6,
    if(t.se_cont_days>2 and t.se_cont_days<=3,0.9,
      if(t.se_cont_days>3 and t.se_cont_days <=4,1.2,
        if(t.se_cont_days>4,1.5,0))))) as se_cont_days_rating,
--13
if(t.fp_cont_pv<=2 and t.fp_cont_pv>0,0.6, 
  if(t.fp_cont_pv>2 and t.fp_cont_pv <=3,1.2,
    if(t.fp_cont_pv>3 and t.fp_cont_pv<=4,1.8,
      if(t.fp_cont_pv>4 and t.fp_cont_pv <=5,2.4,
        if(t.fp_cont_pv>5,3.0,0))))) as fp_cont_pv_rating,
--14连续n天点击楼盘总数
if(t.cp_cont_pv<=1 and t.cp_cont_pv>0,0.3, 
  if(t.cp_cont_pv>1 and t.cp_cont_pv <=2,0.6,
    if(t.cp_cont_pv>2 and t.cp_cont_pv<=3,0.9,
      if(t.cp_cont_pv>3 and t.cp_cont_pv <=4,1.2,
        if(t.cp_cont_pv>4,1.5,0))))) as cp_cont_pv_rating,  
--15
if(t.htc_cont_pv<=1 and t.htc_cont_pv>0,1.2, 
  if(t.htc_cont_pv>1 and t.htc_cont_pv <=2,2.4,
    if(t.htc_cont_pv>2 and t.htc_cont_pv<=3,3.0,0
     ))) as htc_cont_pv_rating, 
--16
if(t.se_cont_pv<=1 and t.se_cont_pv>0,1.2,  
    if(t.se_cont_pv>2 and t.se_cont_pv<=3,3.0,0
     )) as se_cont_pv_rating, 
--17
if(t.fp_cont_days<=1 and t.fp_cont_days>0,1.2,  
    if(t.fp_cont_days>2 and t.fp_cont_days<=3,3.0,0
     )) as fp_cont_days_rating, 
--1.参加活动数
if(t.activity_cnt<=1 and t.activity_cnt>0,0.3, 
  if(t.activity_cnt>1 and t.activity_cnt <=2,0.6,
    if(t.activity_cnt>2 and t.activity_cnt<=3,0.9,
      if(t.activity_cnt>3 and t.activity_cnt <=4,1.2,
        if(t.activity_cnt>4,1.5,0))))) as activity_cnt_rating,
--2.
if(t.qa_ask_cnt<=1 and t.qa_ask_cnt>0,0.3, 
  if(t.qa_ask_cnt>1 and t.qa_ask_cnt <=2,0.6,
    if(t.qa_ask_cnt>2 and t.qa_ask_cnt<=3,0.9,
      if(t.qa_ask_cnt>3 and t.qa_ask_cnt <=4,1.2,
        if(t.qa_ask_cnt>4,1.5,0))))) as qa_ask_cnt_rating,
 --3.问问点击数 
 if(t.qa_click_cnt<=8 and t.qa_click_cnt>0,0.3, 
  if(t.qa_click_cnt>8 and t.qa_click_cnt <=10,0.6,
    if(t.qa_click_cnt>10 and t.qa_click_cnt<=11,0.9,
      if(t.qa_click_cnt>11 and t.qa_click_cnt <=12,1.2,
        if(t.qa_click_cnt>12,1.5,0))))) as qa_click_cnt_rating, 
 --4.
 if(t.qa_view_duration<=150 and t.qa_view_duration>0,0.3, 
  if(t.qa_view_duration>150 and t.qa_view_duration <=180,0.6,
    if(t.qa_view_duration>180 and t.qa_view_duration<=200,0.9,
      if(t.qa_view_duration>200 and t.qa_view_duration <=260,1.2,
        if(t.qa_view_duration>260,1.5,0))))) as qa_view_duration_rating, 
--5.情报局文章点击数
if(t.info_article_cnt<=5 and t.info_article_cnt>0,0.3, 
  if(t.info_article_cnt>5 and t.info_article_cnt <=6,0.6,
    if(t.info_article_cnt>6 and t.info_article_cnt<=7,0.9,
      if(t.info_article_cnt>7 and t.info_article_cnt <=8,1.2,
        if(t.info_article_cnt>8,1.5,0))))) as info_article_cnt_rating, 
--6.
if(t.info_video_cnt<=5 and t.info_video_cnt>0,0.3, 
  if(t.info_video_cnt>5 and t.info_video_cnt <=6,0.6,
    if(t.info_video_cnt>6 and t.info_video_cnt<=7,0.9,
      if(t.info_video_cnt>7 and t.info_video_cnt <=8,1.2,
        if(t.info_video_cnt>8,1.5,0))))) as info_video_cnt_rating, 
--7.
if(t.info_project_cnt<=6 and t.info_project_cnt>0,0.3, 
  if(t.info_project_cnt>6 and t.info_project_cnt <=7,0.6,
    if(t.info_project_cnt>7 and t.info_project_cnt<=8,0.9,
      if(t.info_project_cnt>8 and t.info_project_cnt <=9,1.2,
        if(t.info_project_cnt>9,1.5,0))))) as info_project_cnt_rating, 
--8.
if(t.info_question_cnt<=8 and t.info_question_cnt>0,0.3, 
  if(t.info_question_cnt>8 and t.info_question_cnt <=9,0.6,
    if(t.info_question_cnt>9 and t.info_question_cnt<=10,0.9,
      if(t.info_question_cnt>10 and t.info_question_cnt <=11,1.2,
        if(t.info_question_cnt>11,1.5,0))))) as info_question_cnt_rating, 
--9.
if(t.leave_phone_cnt<=3 and t.leave_phone_cnt>0,0.3, 
  if(t.leave_phone_cnt>4 and t.leave_phone_cnt <=5,0.6,
    if(t.leave_phone_cnt>5 and t.leave_phone_cnt<=6,0.9,
      if(t.leave_phone_cnt>6 and t.leave_phone_cnt <=8,1.2,
        if(t.leave_phone_cnt>8,1.5,0))))) as leave_phone_cnt_rating, 
--10
if(t.service_chat_cnt<=5 and t.service_chat_cnt>0,0.3, 
  if(t.service_chat_cnt>5 and t.service_chat_cnt <=6,0.6,
    if(t.service_chat_cnt>6 and t.service_chat_cnt<=7,0.9,
      if(t.service_chat_cnt>7 and t.service_chat_cnt <=8,1.2,
        if(t.service_chat_cnt>8,1.5,0))))) as service_chat_cnt_rating,
--11在线咨询时长
if(t.service_chat_duration<=120 and t.service_chat_duration>0,0.3, 
  if(t.service_chat_duration>120 and t.service_chat_duration <=150,0.6,
    if(t.service_chat_duration>150 and t.service_chat_duration<=170,0.9,
      if(t.service_chat_duration>170 and t.service_chat_duration <=190,1.2,
        if(t.service_chat_duration>190,1.5,0))))) as service_chat_duration_rating,
--12在线订房得分
if(t.booking_cnt<=6 and t.booking_cnt>0,0.3, 
  if(t.booking_cnt>6 and t.booking_cnt <=7,0.6,
    if(t.booking_cnt>7 and t.booking_cnt<=8,0.9,
      if(t.booking_cnt>8 and t.booking_cnt <=9,1.2,
        if(t.booking_cnt>9,1.5,0))))) as booking_cnt_rating, 
--13
if(t.submit_question_cnt<=2 and t.submit_question_cnt>0,0.3, 
  if(t.submit_question_cnt>2 and t.submit_question_cnt <=3,0.6,
    if(t.submit_question_cnt>3 and t.submit_question_cnt<=4,0.9,
      if(t.submit_question_cnt>4 and t.submit_question_cnt <=5,1.2,
        if(t.submit_question_cnt>5,1.5,0))))) as submit_question_cnt_rating, 
--14
if(t.project_comment_cnt<=1 and t.project_comment_cnt>0,0.3, 
  if(t.project_comment_cnt>1 and t.project_comment_cnt <=2,0.6,
    if(t.project_comment_cnt>2 and t.project_comment_cnt<=3,0.9,
      if(t.project_comment_cnt>3 and t.project_comment_cnt <=4,1.2,
        if(t.project_comment_cnt>4,1.5,0))))) as project_comment_cnt_rating, 
--15
if(t.send_comment_cnt<=1 and t.send_comment_cnt>0,0.3, 
  if(t.send_comment_cnt>1 and t.send_comment_cnt <=2,0.6,
    if(t.send_comment_cnt>2 and t.send_comment_cnt<=3,0.9,
      if(t.send_comment_cnt>3 and t.send_comment_cnt <=4,1.2,
        if(t.send_comment_cnt>4,1.5,0))))) as send_comment_cnt_rating, 
--16
if(t.share_cnt<=5 and t.share_cnt>0,0.3, 
  if(t.share_cnt>5 and t.share_cnt <=6,0.6,
    if(t.share_cnt>6 and t.share_cnt<=7,0.9,
      if(t.share_cnt>7 and t.share_cnt <=8,1.2,
        if(t.share_cnt>8,1.5,0))))) as share_cnt_rating,
--17
if(t.like_cnt<=2 and t.like_cnt>0,0.3, 
  if(t.like_cnt>2 and t.like_cnt <=3,0.6,
    if(t.like_cnt>3 and t.like_cnt<=4,0.9,
      if(t.like_cnt>4 and t.like_cnt <=5,1.2,
        if(t.like_cnt>5,1.5,0))))) as like_cnt_rating,  
--18
if(t.love_cnt<=5 and t.love_cnt>0,0.3, 
  if(t.love_cnt>10 and t.love_cnt <=15,0.6,
    if(t.love_cnt>15 and t.love_cnt<=20,0.9,
      if(t.love_cnt>20 and t.love_cnt <=25,1.2,
        if(t.love_cnt>25,1.5,0))))) as love_cnt_rating, 
--19
if(t.follow_cnt<=5 and t.follow_cnt>0,0.3, 
  if(t.follow_cnt>5 and t.follow_cnt <=6,0.6,
    if(t.follow_cnt>6 and t.follow_cnt<=7,0.9,
      if(t.follow_cnt>7 and t.follow_cnt <=8,1.2,
        if(t.follow_cnt>8,1.5,0))))) as follow_cnt_rating, 
--20
if(t.collect_cnt<=2 and t.collect_cnt>0,0.3, 
  if(t.collect_cnt>2 and t.collect_cnt <=3,0.6,
    if(t.collect_cnt>3 and t.collect_cnt<=4,0.9,
      if(t.collect_cnt>4 and t.collect_cnt <=6,1.2,
        if(t.collect_cnt>6,1.5,0))))) as collect_cnt_rating, 

--app得分
if(t.real_estate_cnt>0,3.0,0) as real_estate_cnt_rating,
if(t.house_decoration_cnt>0,1.0,0) as house_decoration_cnt_rating,
if(t.car_cnt>0,2.0,0) as car_cnt_rating,
if(t.marriage_cnt>0,1.0,0) as marriage_cnt_rating,
if(t.mombaby_cnt>0,1.0,0) as mombaby_cnt_rating,
if(t.investment_cnt>0,2.0,0) as investment_cnt_rating 
 from julive_topic.topic_lable_user_lifecycle_base t
where t.product_id not in(101,201))t1
group by t1.global_id)tmp;

