drop table if exists ods.cj_project_history;
create external table ods.cj_project_history(
id                                                     bigint          comment '主键id',
project_id                                             bigint          comment '楼盘id',
is_importent_notice                                    int             comment '是否重点通知，1是2否',
see_project_note                                       string          comment '带看注意事项',
report_see_project_note                                string          comment '报备带看注意事项',
project_num                                            string          comment '楼盘编号',
name                                                   string          comment '楼盘名称',
summary                                                string          comment '楼盘概述',
tag_bak                                                string          comment '旧标签tag改成备份tag_bak',
property_right                                         string          comment '产权年限',
live_date                                              int             comment '交房时间',
decorate                                               string          comment '装修情况',
decorate_money                                         double          comment '装修费用',
far                                                    string          comment '容积率',
heating                                                string          comment '供暖方式',
car_space                                              string          comment '车位比',
greening                                               string          comment '绿化率',
manage_fee                                             string          comment '物业费',
water_electricity                                      string          comment '水电气',
business_layout                                        string          comment '业态',
developer                                              string          comment '开发商',
property_services                                      string          comment '物业服务',
build_operation                                        string          comment '建筑施工',
landscaping                                            string          comment '园林绿化',
quality_label                                          string          comment '品质标签',
current_open_time                                      bigint          comment '当期开盘时间',
current_sets                                           string          comment '当期套数',
next_open_time                                         bigint          comment '下次开盘时间',
next_sets                                              string          comment '下期套数',
full_pay_rate                                          double          comment '全款折扣',
loan_pay_rate                                          double          comment '贷款折扣',
last_month_rate                                        double          comment '上月平均折扣',
current_rate                                           double          comment '当期报价',
last_month_deal_price                                  double          comment '上月成交价格',
address                                                string          comment '位置描述',
ring_road                                              double          comment '环线',
near_distance                                          string          comment '近环距离',
far_distance                                           string          comment '远环距离',
admin_id                                               int             comment '创建人',
submit_time                                            bigint          comment '创建时间',
index_img                                              string          comment '首页图片',
quality_img                                            string          comment '品质图片',
coordinate                                             string          comment '百度坐标',
enstate                                                string          comment '环境现状',
en_plan_img                                            string          comment '环境规划图',
en_plan_text                                           string          comment '环境规划描述',
en_plan_doc                                            string          comment '环境规划相关文件',
en_air_num                                             double          comment '环境空气数值',
en_voice_num                                           double          comment '环境噪音数值',
en_bad                                                 string          comment '环境不利因素',
en_bad_doc                                             string          comment '环境不利因素相关文件',
ambitus_text                                           string          comment '周边描述',
district_id                                            bigint          comment '区域id',
project_type                                           bigint          comment '项目类型',
acreage_min                                            double          comment '最小面积',
acreage_max                                            double          comment '最大面积',
price_min                                              double          comment '最小总价',
price_max                                              double          comment '最大总价',
phone                                                  string          comment '联系电话',
enroll_num                                             int             comment '报名人数',
school_district_room                                   int             comment '学区房',
near_subway                                            int             comment '临地铁',
near_subway_list                                       string          comment '地铁线列表',
good_decorate                                          int             comment '精装修',
success_rate                                           double          comment '',
is_estimate                                            int             comment '1: 否  2:是',
status                                                 int             comment '1: 未售  2:在售  3:售罄 4:待售',
alias                                                  string          comment '',
school_district_room_list                              string          comment '学区房列表',
near_subway_station_list                               string          comment '地铁站列表',
is_cooperate                                           int             comment '是否是合作楼盘，1:是  2:否',
sale_num                                               int             comment '侃家楼盘出售数量',
update_datetime                                        bigint          comment '更新时间',
creator                                                string          comment '',
create_datetime                                        bigint          comment '创建时间',
updator                                                bigint          comment '楼盘信息更新者',
pay_info                                               string          comment '折扣信息',
is_discount                                            int             comment '是否折扣:1是，2否根据pay_info来判断，有值为1，无值为2',
click_num                                              bigint          comment '点击量',
error_alias                                            string          comment '楼盘错别字别名',
is_outreach                                            int             comment '是否外联:0不是，1是',
recent_instructions                                    string          comment '楼盘近况通知',
lat_lng                                                string          comment '售楼处经纬度',
lng                                                    string          comment '经度',
lat                                                    string          comment '纬度',
district_name                                          string          comment '区域名称',
trade_area                                             bigint          comment '区域板块id',
is_loft                                                int             comment '1是，2否',
card_timing                                            int             comment '排卡开始时间',
competitive_project                                    string          comment '竞品楼盘',
competitive_project_name                               string          comment '竞品楼盘名称',
ec_flow                                                int             comment '是否刷电商,1是,2否',
during_sale_period                                     int             comment '在售期数',
take_land                                              int             comment '拿地时间',
is_park_building                                       int             comment '是否公园地产，1是，2否',
is_personal_steward                                    int             comment '是否私人管家，1是，2否',
tag                                                    string          comment '替换标签tag_replace改成备份tag',
architectural_style                                    string          comment '建筑风格',
elite_plate                                            string          comment '高端板块',
building_info                                          string          comment '楼栋信息',
recent_instructions_img                                string          comment '楼盘近况图片',
forecast                                               int             comment '是否预估 1是 2否',
report_see_project_img                                 string          comment '报备图片',
update_party                                           int             comment '修改方:1支撑系统2微信后台',
auditor                                                bigint          comment '审核者',
city_id                                                int             comment '城市id，城市化专用的分隔标记',
latest_history_price                                   double          comment '最新历史价格',
latest_change_time                                     bigint          comment '最新修改当期报价时间',
diy_icon                                               string          comment '自定义图标',
diy_text                                               string          comment '自定义文案',
diy_show_start_date                                    bigint          comment '自定义文案显示开始时间',
diy_show_end_date                                      bigint          comment '自定义文案显示结束时间',
special_field_cfg                                      int             comment '是否个性化显示字段信息（默认0非个性化，1为个性化展示）',
remark                                                 string          comment '带看备注',
band_status                                            int             comment '带看状态:1非合作2正常带看3暂停带看',
cooperate_remark                                       string          comment '合作备注',
payback_employee_id                                    int             comment '回款负责人id',
is_have_house_type                                     int             comment '是否有户型:1无2有',
is_show                                                bigint          comment '楼盘是否显示 1显示 2隐藏',
price_type                                             int             comment '总价类型',
current_price_type                                     int             comment '单价类型',
latest_history_price_type                              int             comment '最近历史报价类型',
price_desc                                             string          comment '价格说明',
building_img                                           string          comment '楼栋图片',
building_img_size                                      string          comment '楼栋图片尺寸',
old_pay_info                                           string          comment '往期优惠信息',
is_old_discount                                        int             comment '是否折扣:1是，2否根据old_pay_info来判断，有值为1，无值为2',
live_date_year                                         int             comment '交房时间年份',
live_date_month                                        int             comment '交房时间月份',
live_date_day                                          int             comment '交房时间日',
live_date_ten                                          int             comment '交房时间旬 1上旬 2中旬 3下旬',
open_time_year                                         int             comment '开盘时间年份',
open_time_month                                        int             comment '开盘时间月份',
open_time_day                                          int             comment '开盘时间日',
open_time_ten                                          int             comment '开盘时间旬 1上旬 2中旬 3下旬',
special_price_house_desc                               string          comment '特价房描述',
is_special_price_house                                 int             comment '是否是特价房，1:是，2:否',
brand_developer                                        string          comment '品牌开发商，逗号分隔',
on_sale_num                                            int             comment '在售房源套数',
push_project_num                                       int             comment '加推房源套数',
push_project_year                                      int             comment '加推楼盘时间年份',
push_project_month                                     int             comment '加推楼盘时间月份',
push_project_day                                       int             comment '加推楼盘时间日',
push_project_ten                                       int             comment '加推楼盘时间旬',
take_land_price                                        double          comment '拿地总价',
is_continue_push                                       int             comment '是否会持续加推 1是 2否',
match_type                                             int             comment '匹配类型 1:精确匹配 2:模糊匹配 3:人工匹配',
data_from                                              int             comment '数据来源 1搜房楼盘灌入 2安居客楼盘灌入 3搜狐焦点楼盘灌入 10运营添加 11渠道添加',
etl_time                                               string          comment 'ETL跑数时间'
) row format delimited fields terminated by '\001' 
lines terminated by '\n' 
stored as textfile  
location '/dw/ods/cj_project_history'
;
