drop table if exists ods.cj_user;
create external table ods.cj_user(
id                                                     bigint          comment '',
create_datetime                                        int             comment '',
creator                                                bigint          comment '',
update_datetime                                        int             comment '',
updator                                                bigint          comment '',
nickname                                               string          comment '用户昵称',
realname                                               string          comment '真实姓名',
sex                                                    int             comment '性别',
mobile                                                 string          comment '手机号',
password                                               string          comment '密码',
password_reset_token                                   string          comment '密码重置token',
auth_key                                               string          comment '验证key',
email                                                  string          comment '电子邮箱',
avatar                                                 string          comment '头像',
status                                                 int             comment '',
introduce                                              string          comment '介绍',
birthday                                               string          comment '生日',
register_ctiy                                          string          comment '注册城市',
lasttime                                               int             comment '最后登录时间',
lastip                                                 string          comment '最后登录ip',
point                                                  int             comment '现有积分',
paied_point                                            int             comment '已消费积分',
mobile_captcha                                         int             comment '验证码',
`from`                                                 int             comment '用户来源(此字段已废弃)，0未知，1001地推，2001电话400,3001自己pc网站报名，3002自己微信报名，4001表示seo百度，5001表示sem百度',
source                                                 int             comment '1:pc主动注册 2:微信主动注册  3:pc预约看房  4:微信预约看房  5:后台业务员录入订单  6:后台业务员新增用户  7:pc免费通话 8:买房红包预留手机号 9:400来电 10:端口来电 11:微信留言 12:在线客服 13:友介 14:其他 15:关注楼盘价格留手机号',
channel_id                                             int             comment '渠道（了解途径）id',
more_mobiles                                           string          comment '其他手机号，以逗号分隔',
identity_card                                          string          comment '用户身份证号',
relation_user_id                                       bigint          comment '关联用户id',
relation_desc                                          string          comment '与关联用户之间的关系',
user_type                                              int             comment '用户分类:1自营用户，2中介代理用户',
proxy_sale_id                                          bigint          comment '代理中介id',
proxy_sale_name                                        bigint          comment '代理中介名称',
is_import                                              int             comment '0不是通过历史数据导入的，1是通过历史数据导入的',
user_cookie                                            string          comment '用户的cookie',
work_addr                                              string          comment '工作地点',
house_property                                         int             comment '名下房产:1名下无房，2一套房，3二套房及以上',
loan_info                                              int             comment '家庭名下贷款情况:1无贷款记录，2贷过款已还清，3贷款未还清',
customer_pool                                          int             comment '客户池:1:私客池2:同组池',
pool_department_id                                     bigint          comment '同组池组id',
acc_token                                              string          comment '云信token，供im使用',
unionid                                                string          comment '微信用户唯一id',
wechat_info                                            string          comment '微信用户信息，json存储',
house_desc                                             string          comment '房产说明',
openid                                                 string          comment '开放平台返回的openid',
service_openid                                         string          comment '服务号返回的openid',
service_wechat_info                                    string          comment '服务号返回的微信信息',
binding_service_time                                   int             comment '首次绑定服务号的时间',
no_disturb                                             int             comment '1:设置免打扰2:取消免打扰',
work_addr_lat                                          string          comment '工作地点纬度',
work_addr_lng                                          string          comment '工作地点经度',
work_addr_province                                     int             comment '工作地点省份',
work_addr_city                                         int             comment '工作地点城市',
work_addr_district                                     int             comment '工作地点区域',
work_addr_change                                       string          comment '工作地点可能变更地方',
etl_time                                               string          comment 'ETL跑数时间'
) row format delimited fields terminated by '\001' 
lines terminated by '\n' 
stored as textfile  
location '/dw/ods/cj_user'
;
