drop table if exists ods.esf_order;
create external table ods.esf_order(
id                                                     bigint          comment '',
create_datetime                                        int             comment '创建时间',
creator                                                bigint          comment '创建者',
update_datetime                                        int             comment '更新时间',
updator                                                bigint          comment '修改者',
unite_order_id                                         bigint          comment '广义订单id',
city_id                                                int             comment '城市id',
op_type                                                int             comment '',
channel_id                                             int             comment '对应渠道表的id',
channel_put                                            string          comment '渠道投放关键词',
source                                                 int             comment '订单了解途径',
device_type                                            int             comment '设备来源:0未知，1pc，2移动，3android，4ios',
insert_mobile_time                                     int             comment '留电时间',
insert_mobile_house_id                                 bigint          comment '留电房源id',
insert_mobile_village_id                               bigint          comment '留电小区id',
hope_contact_time_str                                  string          comment '客户填写，客户期望联系时间',
hope_contact_time                                      int             comment '客服跟进，客户期望联系时间',
user_id                                                bigint          comment '用户id',
user_realname                                          string          comment '用户姓名',
user_mobile                                            string          comment '用户手机号',
more_mobile                                            string          comment '备用联系方式',
sex                                                    int             comment '1:男2:女',
status                                                 int             comment '状态:10未处理、20待分配、30无效线索、50未联系、60联系未带看、70已带看',
intent_employee_id                                     bigint          comment '意向咨询师id',
intent_employee_name                                   string          comment '意向咨询师姓名',
new_house_order_id                                     bigint          comment '新房订单id',
new_house_employee_id                                  bigint          comment '新房订单所属咨询师id',
employee_id                                            bigint          comment '所属咨询师id',
first_distribute_datetime                              int             comment '第一次订单分配时间',
distribute_datetime                                    int             comment '所属咨询师分配时间',
see_employee_id                                        bigint          comment '最新一次实际带看咨询师id',
is_close                                               int             comment '是否关闭:1是，2否',
close_order_reason                                     int             comment '关闭订单原因',
close_order_explan                                     string          comment '关闭订单原因说明',
close_order_datetime                                   int             comment '关闭订单时间',
maybe_customer                                         int             comment '是否还有机会上户 1.可以 2.不可以 0.老数据',
has_see_julive_ad                                      int             comment '是否看过居理品牌广告,1 是、2 否、3:未回答',
follow_service                                         string          comment '跟进客服',
recommender_id                                         bigint          comment '友介人id（客户或员工）',
user_level                                             string          comment '用户等级',
user_tag                                               string          comment '用户标签，多个逗号分隔',
etl_time                                               string          comment 'ETL跑数时间'
) row format delimited fields terminated by '\001' 
lines terminated by '\n' 
stored as textfile  
location '/dw/ods/esf_order'
;
