drop table if exists ods.esf_order_require;
create external table ods.esf_order_require(
id                                                     bigint          comment '二手房买方订单需求id',
creator                                                int             comment '创建者',
updator                                                int             comment '修改者',
create_datetime                                        int             comment '创建时间',
update_datetime                                        int             comment '更新时间',
order_id                                               bigint          comment '订单id',
total_price_min                                        bigint          comment '最小总价',
total_price_max                                        bigint          comment '最大总价',
is_up_down                                             int             comment '总价是否可上下浮动25%:1是，2否',
first_price_min                                        bigint          comment '最小首付',
first_price_max                                        bigint          comment '最大首付',
first_price_source                                     string          comment '首付来源:1自己有，2家人出，3卖房买房，4借款收款，5在理财里6其它.多个逗号隔开',
first_price_datetime                                   int             comment '首付到位时间',
first_price_datetime_desc                              string          comment '首付到位时间补充说明',
month_price_min                                        int             comment '最小月供',
month_price_max                                        int             comment '最大月供',
qualifications                                         int             comment '是否有资质:1有，2无，3正在办理',
qualifications_detail                                  string          comment '资质具体情况:1社保纳税，2本地户口，3人才引进，4学校集体户口',
district_id                                            string          comment '区域id，逗号分隔',
trade_area_id                                          string          comment '商圈（板块）id，逗号分隔',
village_id                                             string          comment '小区id，逗号分隔',
care_reason                                            string          comment '考虑区域板块的原因',
travel_type                                            string          comment '通勤方式:1公共交通，2自驾，3步行，4电动车，5其它',
travel_time                                            int             comment '通勤时间:1 0~30min，2 30~60min，3不限',
room_type                                              string          comment '户型:1一居2二居3三居4四居5五居及以上。逗号隔开',
room_type_desc                                         string          comment '户型说明',
toilet                                                 string          comment '卫:1 1卫，2 2卫， 3 3卫及以上。逗号隔开',
live_people                                            int             comment '居住人数',
acreage_min                                            int             comment '最小面积',
acreage_max                                            int             comment '最大面积',
renovation                                             string          comment '装修情况:1毛坯，2简装，3精装修',
floor                                                  string          comment '楼层:1不影响采光，2低，3中，4高，5不要顶楼，6不要底楼',
is_elevator                                            int             comment '是否必须要求有电梯:1是，2否',
village_old_new                                        int             comment '小区新旧:1次新商品房,2次新安置房,3老小区,4都可考虑看性价比',
purchase_purpose                                       string          comment '购房目的:1纯投资，2自住型投资，3自住',
live_require                                           int             comment '自住需求:1刚需首套,2改善居住,3婚房,4养老,5学区房',
is_must_school_house                                   int             comment '是否一定需要学区:1是,2否,3都可以',
school_step                                            string          comment '学区阶段:1幼儿园，2小学，3初中',
use_school_time                                        int             comment '使用学区时间:1今年,2明年,3后年,4 3年后',
see_already                                            int             comment '是否有过看房经历:1是，2否',
see_house_type                                         string          comment '看房类型:1新房，2二手房',
see_new_desc                                           string          comment '看新房描述',
see_esf_desc                                           string          comment '看二手房描述',
see_already_long                                       string          comment '看房经历有多久',
see_house_comparison                                   string          comment '看过的房子优缺点',
not_buy_reason                                         string          comment '还没购买的原因',
investors                                              string          comment '出资人',
decisionor                                             string          comment '决策人',
family_suggest                                         string          comment '家人具体建议',
user_desc                                              string          comment '客户描摹',
other_desc                                             string          comment '其它说明',
new_desc                                               string          comment '新房转入需求',
buy_type                                               int             comment '买房类型:1全款，2贷款',
etl_time                                               string          comment 'ETL跑数时间'
) row format delimited fields terminated by '\001' 
lines terminated by '\n' 
stored as textfile  
location '/dw/ods/esf_order_require'
;
