drop table if exists ods.esf_house;
create external table ods.esf_house(
house_id                                               bigint          comment '',
house_spider_id                                        bigint          comment '二手房抓取表id',
source                                                 int             comment '来源',
url                                                    string          comment '详情页url',
url_md5                                                string          comment '详情页url_md5',
city_id                                                int             comment '城市id',
district_id                                            int             comment '区域id',
title                                                  string          comment '标题（抓取房源:小区+户型+总价 拼接）',
total_price                                            string          comment '总价',
house_price                                            string          comment '单价',
building_num                                           string          comment '楼栋',
unit                                                   string          comment '单元',
room_number                                            string          comment '房号',
room_info                                              string          comment '户型信息',
room_type                                              int             comment '户型:1一居2二居3三居4四居5五居及以上',
hall                                                   int             comment '厅',
toilet                                                 string          comment '卫',
acreage                                                double          comment '面积',
village_id                                             bigint          comment '小区id',
village_name                                           string          comment '小区名',
village_source_id                                      int             comment '抓取源，小区id',
floor                                                  string          comment '所在楼层',
floor_detail                                           string          comment '具体楼层',
floor_total                                            string          comment '总楼层',
orientation                                            string          comment '朝向',
renovation                                             string          comment '装修情况',
house_type_detail                                      string          comment '房屋用途',
house_type                                             int             comment '房屋用途:1普通住宅 2别墅 3其它',
building_type                                          string          comment '建筑类型',
building_year                                          string          comment '建筑年代',
trade_area_id                                          string          comment '商圈id',
see_time                                               string          comment '看房时间',
status                                                 int             comment '状态:1正常，2删除',
img_tag                                                int             comment '1有图片 2无图片',
score                                                  double          comment '房源评分',
is_urgent_sale                                         int             comment '是否急售:1是，2否',
taxation_info                                          string          comment '税费情况',
around_school                                          string          comment '周边学校',
has_key                                                int             comment '钥匙:1有 2无',
subway                                                 string          comment '地铁',
subway_line_id                                         int             comment '地铁线路id',
subway_station_id                                      int             comment '地铁站id',
subway_distance                                        string          comment '距离地铁站',
mortgage_info                                          string          comment '抵押情况',
payment                                                string          comment '付款方式',
tag_id                                                 string          comment '标签id，逗号分隔',
tag_name                                               string          comment '标签中文名，逗号分隔',
is_main_push                                           int             comment '是否主推:1是2否',
sale_status                                            int             comment '销售状态:1在售 2停售3 已售',
creator                                                bigint          comment '创建者',
updator                                                bigint          comment '修改者',
create_datetime                                        int             comment '创建时间',
update_datetime                                        int             comment '更新时间',
property                                               int             comment '产权年限:1:70年 2:50年3:40年',
trading                                                int             comment '交易权属: 1商品房2经济适用房3公房4安置房5其他',
elevator                                               int             comment '有无电梯:1有2无',
house_creator                                          bigint          comment '房源最初的创建者',
etl_time                                               string          comment 'ETL跑数时间'
) row format delimited fields terminated by '\001' 
lines terminated by '\n' 
stored as textfile  
location '/dw/ods/esf_house'
;
