drop table if exists ods.hr_employee_offjob;
create external table ods.hr_employee_offjob(
id                                                     int             comment '',
employee_id                                            int             comment '员工id',
type                                                   int             comment '1:主动离职2:被动离职3:未入职离职4:审批离职',
off_datetime                                           bigint          comment '离职时间',
check_datetime                                         bigint          comment '办理离职时间',
person_reason                                          int             comment '个人主因:1个人身体健康因素2家庭原因3交通不便，离住处远4回校深造5找到更好的企业工作6实习生返校7自己经营生意8转换行业9其他',
company_reason                                         int             comment '公司主因:1工作量太大，压力大2工资低3福利差4与领导关系部和谐5无晋升机会6不满子公司的策略的措施7同事关系不融洽8获取工作必须的资源信息或支持困难9工作时间10工作意见不受重视11工作目标／需求不明确12其他',
off_reason                                             string          comment '具体原因描述',
insurancesub                                           int             comment '社保减员月1:离职日当月2:离职日下月',
housefundsub                                           int             comment '公积金减员月1:离职日当月2:离职日下月',
year_days                                              int             comment '剩余年假',
swap_days                                              int             comment '剩余调休',
is_approval_offjob                                     int             comment '是否审批离职',
offjob_one                                             int             comment '离职因素1',
offjob_two                                             int             comment '离职因素2',
offjob_three                                           int             comment '离职因素3',
offjob_other                                           string          comment '离职因素4',
`describe`                                             string          comment '具体原因描述',
leader_proposal                                        string          comment '对上级的评价和建议',
company_proposal                                       string          comment '对部门及公司的评价和建议',
is_adopt                                               int             comment '是否采纳并改善1是 2否',
improve_id                                             string          comment '改善负责人',
follow_id                                              string          comment '跟进人',
improve_time                                           string          comment '改善时间节点',
improve_plan                                           string          comment '改善方案',
no_adopt_reason                                        string          comment '改善进度&结果/不采纳原因',
group_proposal                                         string          comment '反馈总部的建议',
group_department                                       string          comment '反馈总部部门',
three_days_assess                                      string          comment '3个工作日部门评估',
one_week_plan                                          string          comment '一周内改善方案是否提出',
two_week_plan                                          string          comment '两周内改善方案是否执行',
approval_id                                            int             comment '审批id',
direct_leader_id                                       int             comment '直接上级',
indirect_leader_id                                     int             comment '间接上级',
is_work                                                int             comment '是否找到工作 1是 2否',
hope_post                                              int             comment '期望岗位:1原岗位、2相似岗位、3不同岗位',
hope_industry                                          string          comment '期望行业1、房地产 2、互联网 3、金融和保险 4、汽车 5、教育 6、政府机关 7、医疗卫生 8、交通运输 9、旅游休闲 10、批发和零售 11、住宿和餐饮 12、深造学习 13、创业 14、其他',
hope_other_industry                                    string          comment '其他行业',
entry_company                                          string          comment '入职公司名称',
create_datetime                                        bigint          comment '',
update_datetime                                        bigint          comment '',
creator                                                int             comment '',
updator                                                int             comment '',
entry_datetime                                         bigint          comment '入职时间',
etl_time                                               string          comment 'ETL跑数时间'
) row format delimited fields terminated by '\001' 
lines terminated by '\n' 
stored as textfile  
location '/dw/ods/hr_employee_offjob'
;
