drop table if exists ods.hr_manpower_monthly;
create external table ods.hr_manpower_monthly(
id                                                     bigint          comment '',
employee_name                                          string          comment '员工姓名',
job_number                                             string          comment '员工工号',
status                                                 int             comment '在职情况  0离职 1在职',
city_id                                                int             comment '部门所在城市',
management_form                                        int             comment '管理形式 1总公司 2分公司',
department_attributes                                  int             comment '部门属性 1支撑部门 2职能部门 3业务部门',
department_name                                        string          comment '部门名称',
post_name                                              string          comment '职位',
employment_form                                        int             comment '聘用形式',
rank                                                   string          comment '职级',
sex                                                    int             comment '性别 1男 2女',
marital_status                                         int             comment '婚姻状况 1已婚  2未婚',
idcard                                                 string          comment '身份证号',
birth                                                  int             comment '生日',
age                                                    int             comment '年龄',
nation                                                 string          comment '民族',
domicile_address                                       string          comment '户籍',
household_type                                         int             comment '户口类型 1-农业  2-非农业',
political_outlook                                      string          comment '政治面貌',
contract                                               string          comment '合同归属',
ascription                                             string          comment '社保、公积金归属',
entry_datetime                                         int             comment '入职日期',
plan_full_time                                         int             comment '计划转正时间',
full_time                                              int             comment '转正日期',
full_type                                              int             comment '转正状态 1未转正 2已转正',
first_contract_time                                    int             comment '合同起始日',
end_contract_time                                      int             comment '合同到期日',
graduation_school                                      string          comment '毕业学校',
school_attributes                                      string          comment '学校类型',
graduation_time                                        int             comment '毕业日期',
major                                                  string          comment '专业',
first_worktime                                         int             comment '正式参加工作日期',
high_major                                             int             comment '学历 1初中 2高中 3大专 4本科 5硕士 6博士 7其他',
open_bank                                              string          comment '开户行信息',
bank_num                                               string          comment '工资卡卡号',
mobile                                                 string          comment '联系方式',
offjob_time                                            int             comment '离职时间',
now_addrress                                           string          comment '现住址',
create_datetime                                        int             comment '添加时间',
update_datetime                                        int             comment '更新时间',
creator                                                int             comment '添加人',
updator                                                int             comment '更新人',
department_id                                          int             comment '部门id',
leader_job_number                                      bigint          comment '部门负责人工号（按照部门leader取的员工工号)',
check_date                                             int             comment '月报时间',
leader_employee_id                                     int             comment '部门负责人id',
direct_leader_id                                       int             comment '员工直接上级id',
is_worker                                              int             comment '是否是晚加班员工 1 是 2 否',
post_id                                                int             comment '岗位id',
employee_id                                            int             comment '员工id',
adjust_city_id                                         bigint          comment '业绩核算城市',
etl_time                                               string          comment 'ETL跑数时间'
) row format delimited fields terminated by '\001' 
lines terminated by '\n' 
stored as textfile  
location '/dw/ods/hr_manpower_monthly'
;
