drop table if exists mydb.topic_sem_keyword_day_indi on cluster julive_cluster;
create table mydb.topic_sem_keyword_day_indi on cluster julive_cluster(
city_id                                                String          comment '城市id',
city_name                                              String          comment '城市名称',
media_id                                               String          comment '媒体id',
media_name                                             String          comment '媒体名称',
module_id                                              String          comment '模块id',
module_name                                            String          comment '模块名称',
channel_id                                             String          comment '渠道id',
channel_name                                           String          comment '渠道名称',
account_id                                             String          comment '账户id',
account_name                                           String          comment '账户名称',
plan_id                                                String          comment '计划id',
plan_name                                              String          comment '计划名称',
unit_id                                                String          comment '单元id',
unit_name                                              String          comment '单元名称',
keyword_id                                             Int64           comment '关键词id',
keyword_name                                           String          comment '关键词名称',
match_type                                             String          comment '匹配模式',
pc_average_ranking                                     String          comment 'pc端平均排名',
m_average_ranking                                      String          comment 'm端平均排名',
pc_url                                                 String          comment 'pc端关键词投放url',
m_url                                                  String          comment 'm端关键词投放url',
show_num                                               Int32           comment '展示量',
click_num                                              Int32           comment '点击量',
bill_cost                                              String          comment '账单消费金额',
cost                                                   String          comment '消费金额',
leave_phone_num                                        Int32           comment '留电量',
clue_num                                               Int32           comment '线索量',
distribute_num                                         Int32           comment '上户量',
see_num                                                Int32           comment '带看量',
subscribe_num                                          Int32           comment '认购量',
sign_num                                               Int32           comment '有效签约量',
returned_amt                                           String          comment '回款金额',
first_clue_num                                         Int32           comment '首次匹配keyword线索量',
first_distribute_num                                   Int32           comment '首次匹配keyword上户量',
first_see_num                                          Int32           comment '首次匹配keyword带看量',
first_subscribe_num                                    Int32           comment '首次匹配keyword认购量',
first_sign_num                                         Int32           comment '首次匹配keyword有效签约量',
first_returned_amt                                     String          comment '首次匹配keyword回款',
jump_num                                               Int32           comment '跳出量',
uv                                                     Int32           comment 'uv',
eff_leave_phone_num                                    Float32         comment '助攻留电量',
eff_clue_num                                           Float32         comment '助攻线索量',
eff_distribute_num                                     Float32         comment '助攻上户量',
eff_see_num                                            Float32         comment '助攻带看量',
eff_subscribe_num                                      Float32         comment '助攻认购量',
eff_num                                                Int32           comment '助攻次数',
uv_400                                                 Int32           comment '400用户量',
pv_400                                                 Int32           comment '400点击量',
etl_time                                               String          comment 'etl跑数时间')ENGINE=MergeTree
partition by pdate  
order by (keyword_id) 
;

drop table if exists mydb.topic_sem_keyword_day_indi_all on cluster julive_cluster;
create table mydb.topic_sem_keyword_day_indi_all on cluster julive_cluster(
city_id                                                String          comment '城市id',
city_name                                              String          comment '城市名称',
media_id                                               String          comment '媒体id',
media_name                                             String          comment '媒体名称',
module_id                                              String          comment '模块id',
module_name                                            String          comment '模块名称',
channel_id                                             String          comment '渠道id',
channel_name                                           String          comment '渠道名称',
account_id                                             String          comment '账户id',
account_name                                           String          comment '账户名称',
plan_id                                                String          comment '计划id',
plan_name                                              String          comment '计划名称',
unit_id                                                String          comment '单元id',
unit_name                                              String          comment '单元名称',
keyword_id                                             Int64           comment '关键词id',
keyword_name                                           String          comment '关键词名称',
match_type                                             String          comment '匹配模式',
pc_average_ranking                                     String          comment 'pc端平均排名',
m_average_ranking                                      String          comment 'm端平均排名',
pc_url                                                 String          comment 'pc端关键词投放url',
m_url                                                  String          comment 'm端关键词投放url',
show_num                                               Int32           comment '展示量',
click_num                                              Int32           comment '点击量',
bill_cost                                              String          comment '账单消费金额',
cost                                                   String          comment '消费金额',
leave_phone_num                                        Int32           comment '留电量',
clue_num                                               Int32           comment '线索量',
distribute_num                                         Int32           comment '上户量',
see_num                                                Int32           comment '带看量',
subscribe_num                                          Int32           comment '认购量',
sign_num                                               Int32           comment '有效签约量',
returned_amt                                           String          comment '回款金额',
first_clue_num                                         Int32           comment '首次匹配keyword线索量',
first_distribute_num                                   Int32           comment '首次匹配keyword上户量',
first_see_num                                          Int32           comment '首次匹配keyword带看量',
first_subscribe_num                                    Int32           comment '首次匹配keyword认购量',
first_sign_num                                         Int32           comment '首次匹配keyword有效签约量',
first_returned_amt                                     String          comment '首次匹配keyword回款',
jump_num                                               Int32           comment '跳出量',
uv                                                     Int32           comment 'uv',
eff_leave_phone_num                                    Float32         comment '助攻留电量',
eff_clue_num                                           Float32         comment '助攻线索量',
eff_distribute_num                                     Float32         comment '助攻上户量',
eff_see_num                                            Float32         comment '助攻带看量',
eff_subscribe_num                                      Float32         comment '助攻认购量',
eff_num                                                Int32           comment '助攻次数',
uv_400                                                 Int32           comment '400用户量',
pv_400                                                 Int32           comment '400点击量',
etl_time                                               String          comment 'etl跑数时间') ENGINE=Distributed(
julive_cluster, 
mydb, 
topic_sem_keyword_day_indi,
keyword_id 
);
