drop table if exists ods.trigger_project_house_type;
create external table ods.trigger_project_house_type(
house_type_id                                          bigint          comment '户型id',
project_id                                             bigint          comment '楼盘id',
project_num                                            string          comment '楼盘编号',
name                                                   string          comment '楼盘名称',
general_score                                          int             comment '冗余 推荐楼盘 主推楼盘 竞品楼盘排序',
district_general_score                                 int             comment '区域主推楼盘得分',
live_date                                              int             comment '交房时间',
current_rate                                           double          comment '当期报价',
last_month_deal_price                                  double          comment '上月成交价格',
ring_road                                              double          comment '环线',
district_id                                            bigint          comment '区域id',
project_type                                           bigint          comment '项目类型',
enroll_num                                             int             comment '报名人数',
school_district_room                                   int             comment '学区房',
near_subway                                            int             comment '临地铁',
near_subway_list                                       string          comment '地铁线列表',
good_decorate                                          int             comment '精装修',
status                                                 int             comment '状态，1: 未售  2:在售  3:售罄 4:待售',
alias                                                  string          comment '别名',
school_district_room_list                              string          comment '学区房列表',
near_subway_station_list                               string          comment '地铁站列表',
is_cooperate                                           int             comment '是否是合作楼盘，1:是  2:否',
sale_num                                               int             comment '侃家楼盘出售数量',
click_num                                              bigint          comment '点击量',
error_alias                                            string          comment '楼盘错别字别名',
district_name                                          string          comment '区域名称',
trade_area                                             bigint          comment '区域板块id',
is_loft                                                int             comment '是否loft:1是，2否',
is_personal_steward                                    int             comment '是否私人管家，1是，2否',
tag                                                    string          comment '替换标签tag_replace改成备份tag',
city_id                                                int             comment '城市id，城市化专用的分隔标记',
is_show                                                bigint          comment '楼盘是否显示 1显示 2隐藏',
is_outreach                                            int             comment '是否外联:0不是，1是',
card_timing                                            int             comment '排卡开始时间',
ec_flow                                                int             comment '是否刷电商,1是,2否',
take_land                                              string          comment '拿地时间',
is_park_building                                       int             comment '是否公园地产，1是，2否',
is_discount                                            int             comment '是否折扣:1是，2否根据pay_info来判断，有值为1，无值为2',
lng                                                    string          comment '经度',
lat                                                    string          comment '纬度',
acreage_min                                            double          comment '最小面积',
acreage_max                                            double          comment '最大面积',
price_min                                              double          comment '最小总价',
price_max                                              double          comment '最大总价',
sign_num                                               int             comment '最近90天，楼盘签约统计',
house_type_num                                         string          comment '户型编号（业务编号）',
room_type                                              int             comment '厅室类别:0不限, 1一居, 2二居, 3三居, 4四居, 5五居及以上, 6 loft',
acreage                                                int             comment '建筑面积',
price                                                  double          comment '总价',
trans_price                                            double          comment '成交单价',
offer_price                                            double          comment '报价单价',
house_status                                           int             comment 'cj_house_type:status状态，1: 未售  2:在售  3:售罄 4:待售',
building_type                                          int             comment '建筑类型:0不限,1独栋,2双拼,3联排,4叠拼,5平层,6复式,7洋房,8loft,9非loft',
house_type_tag                                         string          comment 'cj_house_type:house_tag户型标签',
small_family                                           int             comment '是否是小户型 1:是2:否,面积在0-80平,脚本自动计算',
low_price                                              int             comment '是否是低总价 1:是2:否,价格在0-2百万,脚本自动计算',
is_show_room_type                                      int             comment '是否展现厅室类别，1: 否  2:是',
see_num                                                int             comment '最近90天，楼盘带看量统计',
operation_score                                        int             comment '运营数据排序得分',
coordinate                                             string          comment '百度坐标',
panorama_code                                          string          comment '全景看房资源id',
current_open_time                                      bigint          comment '当期开盘时间',
developer                                              string          comment '开发商',
is_old_discount                                        int             comment '是否折扣:1是，2否根据old_pay_info来判断，有值为1，无值为2',
is_special_price_house                                 int             comment '是否特价房，1:是，2:否',
brand_developer                                        string          comment '品牌开发商，逗号分隔',
open_time_year                                         int             comment '开盘时间年份',
open_time_month                                        int             comment '开盘时间月份',
open_time_day                                          int             comment '开盘时间日',
open_time_ten                                          int             comment '开盘时间旬',
abtest_general_score                                   int             comment '狙击手测试楼盘得分',
volume_status                                          int             comment '楼盘放量状态 1:新开楼盘 2:即将开盘',
down_pay                                               double          comment '首付',
name_use_for_sort                                      string          comment '楼盘名称–用于相关性排序',
project_video_num                                      int             comment '楼盘显示的视频数量',
score                                                  int             comment '大数据计算得分',
volume_date_pre                                        int             comment '预计开盘、加推时间',
volume_date_done                                       int             comment '已开盘、加推时间',
etl_time                                               string          comment 'ETL跑数时间'
) row format delimited fields terminated by '\001' 
lines terminated by '\n' 
stored as textfile  
location '/dw/ods/trigger_project_house_type'
;
