drop table if exists ods.xpt_opensearch_middle_village_house;
create external table ods.xpt_opensearch_middle_village_house(
id                                                     bigint          comment '自增id',
house_id                                               bigint          comment '房源id-xpt_house',
title                                                  string          comment '房源标题-xpt_house',
city_id                                                int             comment '城市id-xpt_village',
village_id                                             int             comment '小区id',
village_name                                           string          comment '小区名称-xpt_village',
brand_id                                               int             comment '门店所属品牌商id-xpt_house',
store_id                                               int             comment '门店id-xpt_house',
district_id                                            int             comment '区域id-xpt_village',
district_name                                          string          comment '区域名称-cj_district中name_cn',
district_name_pinyin                                   string          comment '区域名称拼音-cj_district中name_pinyin',
trade_area_id                                          int             comment '商圈id-xpt_village',
trade_area_name                                        string          comment '商圈名称-yw_trade_area中trade_area',
trade_area_pinyin                                      string          comment '板块拼音-yw_trade_area中pinyin',
village_address                                        string          comment '地址-xpt_village中address',
village_lng                                            string          comment '小区经度-xpt_village中lng',
village_lat                                            string          comment '小区纬度-xpt_village中lat',
coordinate                                             string          comment '百度坐标,以空格分割 （经度 纬度）,使用场景传入坐标和半径公里至查半径防伪内的数据--xpt_village',
village_loop                                           string          comment '小区环线-xpt_village中loop',
decoration_status                                      int             comment '装修情况1.毛坯 2.简装 3.精装-xpt_house_attr中的decoration_status',
near_subway_list                                       string          comment '地铁线列表 多个逗号分隔-xpt_house_attr中的near_subway_list',
house_type                                             int             comment '房屋用途:1普通住宅、2车库、3别墅、4写字楼、5商业、6工业平房、7商住两用、8底商-xpt_house_construction中的house_type',
house_tag_id_list                                      string          comment '房源标签list-xpt_tag_relation中tag_id',
house_orientations_id_list                             string          comment '房源标签list-xpt_house_orientations中orientations_id',
house_video_num                                        int             comment '视频数量-xpt_house_attachment中文件类型值file_type为3房源视频',
height_type                                            int             comment '楼层类型 1低层 2中层 3高层-xpt_house',
total_floor_num                                        int             comment '总楼层-xpt_house',
floor_detail                                           string          comment '具体楼层-xpt_house',
room                                                   int             comment '几室，居室-xpt_house',
hall                                                   int             comment '几厅-xpt_house',
kitchen                                                int             comment '几厨-xpt_house',
toilet                                                 int             comment '几卫-xpt_house',
unit_price                                             double          comment '单价-xpt_house',
total_price                                            int             comment '总价-xpt_house',
build_acreage                                          double          comment '建筑面积-xpt_house',
inside_acreage                                         double          comment '套内面积-xpt_house',
is_common_owership                                     string          comment '产权是否共有-xpt_house',
is_delete                                              int             comment '是否删除 1是 2否-xpt_house',
is_draft                                               int             comment '是否为草稿 1.是， 2.否-xpt_house',
is_hidden                                              int             comment '是否隐藏 1是 2否-xpt_house',
is_sales                                               int             comment '是否售卖（房态）（非下架） 1.是 2.否-xpt_house',
house_year                                             int             comment '产证年限(房屋年限) 1 不满2年 2 满2年 3 满5年唯一 4满5年不唯一-xpt_house_selling_info',
is_only                                                int             comment '是否唯一 1是2否-xpt_house_selling_info',
building_structure                                     int             comment '建筑结构-xpt_house_construction',
house_create_datetime                                  int             comment '创建时间，房源主表创建时间-xpt_house',
house_update_datetime                                  int             comment '修改时间，房源主表更新时间-xpt_house',
create_datetime                                        int             comment '创建时间',
update_datetime                                        int             comment '修改时间',
creator                                                int             comment '创建者',
updator                                                int             comment '更新者',
maintain_id                                            int             comment '维护人id--xpt_house',
building_type                                          int             comment '建筑类型 1板楼 2塔楼 3板塔结合 4平方--xpt_house_construction',
elevator                                               int             comment '有无电梯:1有2无--xpt_house_construction',
trading_ownership                                      int             comment '交易权属:1商品房、2已购公房、3经济适用房、4动迁安置房、5限价商品房、6使用权、7乡产、8私产、9军产、10公租房、11廉租房、12校产、13宗教产、14保障性住房--xpt_house_construction',
etl_time                                               string          comment 'ETL跑数时间'
) row format delimited fields terminated by '\001' 
lines terminated by '\n' 
stored as textfile  
location '/dw/ods/xpt_opensearch_middle_village_house'
;
