drop table if exists ods.xpt_house;
create external table ods.xpt_house(
id                                                     bigint          comment '自增id',
title                                                  string          comment '房屋标题',
village_id                                             int             comment '小区id',
village_name                                           string          comment '冗余小区名称',
building_id                                            int             comment '楼座id',
owner_id                                               int             comment '业主id',
brand_id                                               int             comment '门店所属品牌商id',
store_id                                               int             comment '门店id',
maintain_id                                            int             comment '维护人id',
input_id                                               int             comment '录入人id',
district_id                                            int             comment '区域id',
trade_area_id                                          int             comment '商圈id',
index_url                                              string          comment '首图url',
video_header_url                                       string          comment '房源视频头图',
entrust_type                                           int             comment '委托类型 1出售',
entrust_source                                         string          comment '委托来源',
height_type                                            int             comment '楼层类型 1低层 2中层 3高层',
total_floor_num                                        int             comment '总楼层',
floor_detail                                           string          comment '具体楼层',
unit                                                   string          comment '单元',
house_number                                           string          comment '门牌号',
room                                                   int             comment '几室',
hall                                                   int             comment '几厅',
kitchen                                                int             comment '几厨',
toilet                                                 int             comment '几卫',
unit_price                                             double          comment '单价',
total_price                                            int             comment '总价',
build_acreage                                          double          comment '建筑面积',
inside_acreage                                         double          comment '套内面积',
is_common_owership                                     string          comment '产权是否共有',
authentic_task_datetime                                int             comment '验真日期',
authentic_task_status                                  int             comment '验真状态',
is_delete                                              int             comment '是否删除 1是 2否',
is_draft                                               int             comment '是否为草稿 1.是， 2.否',
is_select                                              int             comment '是否精选 1是 2否',
is_hidden                                              int             comment '是否隐藏 1是 2否',
is_sales                                               int             comment '是否售卖（房态）（非下架） 1.是 2.否',
easy_sell                                              double          comment '易成交评分',
quality_score                                          double          comment '质量评分',
integrity_score                                        double          comment '信息完整度评分',
create_datetime                                        int             comment '创建时间',
update_datetime                                        int             comment '修改时间',
creator                                                int             comment '创建者',
updator                                                int             comment '更新者',
etl_time                                               string          comment 'ETL跑数时间'
) row format delimited fields terminated by '\001' 
lines terminated by '\n' 
stored as textfile  
location '/dw/ods/xpt_house'
;
