drop table if exists ods.yw_app_user_behavior;
create external table ods.yw_app_user_behavior(
id                                                     bigint          comment '',
julive_id                                              string          comment '居理id',
distinct_id                                            string          comment '用户标识id',
product_id                                             string          comment '设备端',
select_city_count                                      string          comment '切换城市数',
view_banner_count                                      string          comment '查看banner数',
search_project_count                                   string          comment '使用搜索次数',
map_room_count                                         string          comment '使用地图找房次数',
project_sort_count                                     string          comment '使用楼盘排序次数',
project_info_unfold_count                              string          comment '展开更多楼盘信息次数',
get_car_discout_count                                  string          comment '领专车券次数',
get_discout_count                                      string          comment '领超值优惠次数',
view_house_type_count                                  string          comment '查看户型列表次数',
view_surrounding_count                                 string          comment '查看周边分析次数',
click_service_chat_count                               string          comment '点击在线咨询的总次数',
dial_service_call_count                                string          comment '点击免费通话总次数',
order_view_house_count                                 string          comment '点击预约看房的总次数',
view_user_help_find_room_count                         string          comment '浏览个人中心帮我找房次数',
view_home_help_find_room_count                         string          comment '浏览金刚帮我找房次数',
view_project_help_find_room_count                      string          comment '浏览楼盘详情页帮我找房次数',
view_order_car_count                                   string          comment '浏览预约专车次数',
view_project_count                                     string          comment '浏览楼盘数',
favorit_project_count                                  string          comment '浏览次数最多的楼盘',
view_project_dynamic_count                             string          comment '浏览楼盘动态数',
view_question_card_count                               string          comment '浏览问问数',
order_price_notice_count                               string          comment '订阅变价通知的次数',
order_opening_count                                    string          comment '订阅开盘通知的次数',
order_project_dynamic_count                            string          comment '订阅楼盘变动通知的次数',
order_house_dynamic_count                              string          comment '订阅楼栋变动通知的次数',
submit_question_count                                  string          comment '提问次数',
click_like_count                                       string          comment '点赞成功次数',
write_project_comment_count                            string          comment '点评楼盘次数',
collection_project_count                               string          comment '收藏成功楼盘数次数',
share_project_count                                    string          comment '分享楼盘数',
adviser_list_chat_count                                string          comment '点击咨询师列表页“向ta咨询”次数',
adviser_detalis_chat_count                             string          comment '点击咨询师详情页“向ta咨询”次数',
help_find_room_count                                   string          comment '帮我找房留电次数',
order_car_count                                        string          comment '预约专车留电次数',
visit_duration                                         string          comment '单天访问时长总和',
start_count                                            string          comment '启动次数',
date                                                   string          comment '',
time                                                   int             comment '',
etl_time                                               string          comment 'ETL跑数时间'
) row format delimited fields terminated by '\001' 
lines terminated by '\n' 
stored as textfile  
location '/dw/ods/yw_app_user_behavior'
;
