drop table if exists ods.yw_booking;
create external table ods.yw_booking(
id                                                     bigint          comment 'id',
project_id                                             int             comment '楼盘id',
order_id                                               bigint          comment '订单id',
deal_id                                                bigint          comment '成交单id',
booking_type                                           int             comment '订房类型 1咨询师 2客户 3经纪人 4拓展',
house_type_id                                          bigint          comment '户型id',
control_id                                             bigint          comment '销控id',
building_name                                          string          comment '楼栋名称',
unit_name                                              string          comment '单元号',
floor_name                                             string          comment '楼层',
room_name                                              string          comment '室',
deal_money                                             double          comment '优惠后总价',
acreage                                                double          comment '建筑面积',
discount                                               string          comment '优惠信息',
intention_money                                        double          comment '订房意向金',
project_type                                           bigint          comment '楼盘业态',
sales_name                                             string          comment '销售姓名',
sales_mobile                                           string          comment '销售电话',
user_id                                                bigint          comment '用户id',
user_name                                              string          comment '用户姓名',
user_phone                                             string          comment '用户电话',
id_type                                                int             comment '证件类型: 1:大陆身份证 2:其他',
user_identity_number                                   string          comment '用户人身份证号',
address                                                string          comment '用户人地址',
deal_type                                              int             comment '成交类型:0未知 1合作 2非合作 3无效 4外联 5待定',
status                                                 int             comment '状态:5待支付 10取消支付 15审核支付中 20待商务确认 21待客户确认 25取消确认 30待签字 35取消签字 40待盖章 45锁房中 50取消锁房 55锁房成功 60锁房失败',
pay_status                                             int             comment '意向金状态: 0待支付 5取消支付 10支付待审核 15支付成功 20退款待商务审核 25退款待主管审核 30退款主管驳回 35退款待财务审核 40退款财务驳回 45退款成功',
city_id                                                int             comment '城市id',
project_city_id                                        int             comment '楼盘城市id',
contract_id                                            bigint          comment '订房合同id',
contract_template_id                                   bigint          comment '订房合同模板id',
cw_supplier_id                                         int             comment '卖方合同主体 id (人力供应商 cw_supplier表id)',
contract_type                                          int             comment '订房合同类型:1自营 2直营',
booking_datetime                                       int             comment '发起订房合同时间',
contract_pdf                                           string          comment '合同pdf地址',
contract_start_datetime                                int             comment '合同有效开始时间(锁房开始时间)',
contract_end_datetime                                  int             comment '合同有效结束时间(锁房结束时间)',
custom_pay_datetime                                    int             comment '客户完成付款时间',
custom_sign_datetime                                   int             comment '客户完成签字时间',
custom_cancel_datetime                                 int             comment '客户发起退订时间',
cancel_audit_datetime                                  int             comment '退款审批通过时间',
seller_sign_datetime                                   int             comment '卖方合同盖章时间',
sign_deadline_datetime                                 int             comment '签字截止时间',
subscribe_datetime                                     int             comment '转认购时间',
audit_group_id                                         string          comment '审核组id',
create_datetime                                        int             comment '创建时间',
update_datetime                                        int             comment '更新时间',
creator                                                int             comment '创建者',
updator                                                int             comment '更新者',
op_type                                                string          comment 'op_type',
flow_id                                                int             comment '签署流程id',
contract_no                                            string          comment '合同编号',
is_syn_order                                           int             comment '是否同步发送订单进行分配，1是，2否',
booking_source                                         int             comment '订房来源 1居理 2新平台',
is_julive_employee                                     int             comment '是否是居理员工1.不是居理员工2.居理在职员工3.居理离职员工',
etl_time                                               string          comment 'ETL跑数时间'
) row format delimited fields terminated by '\001' 
lines terminated by '\n' 
stored as textfile  
location '/dw/ods/yw_booking'
;
