drop table if exists ods.yw_didi_order;
create external table ods.yw_didi_order(
id                                                     bigint          comment '',
order_id                                               bigint          comment '居理订单id',
replate_reason                                         int             comment '补录理由（1.正常带看忘记录入、2.带看被临时取消、3.正常签约陪同忘记录入、4.其他成交后服务、5.其他）',
business_type                                          int             comment '业务类型，1带看',
business_id                                            bigint          comment '业务id',
deal_id                                                bigint          comment '成交单id',
relate_type                                            int             comment '是否关联（0-未关联、1.已关联、2.补关联）',
relate_datetime                                        int             comment '业务关联时间',
budget_item_id                                         string          comment '滴滴订单id',
type                                                   int             comment '0:实时 1:预约 2:接机单 3:送机单 4:日租 5:半日租 6:接送站 7:马上用车',
flat                                                   string          comment '出发地纬度',
flng                                                   string          comment '出发地经度',
tlat                                                   string          comment '目的地纬度',
tlng                                                   string          comment '目的地经度',
create_time                                            int             comment '叫单时间',
user_car_type                                          int             comment '用车方式（1:出租车，2:专车，3:快车，4:代驾）',
require_level                                          int             comment '车型（100舒适型,400商务型,200豪华型,500优选型,600快车,700易达,1出租车,2新能源）',
city                                                   int             comment '城市id',
city_name                                              string          comment '城市名称',
start_name                                             string          comment '出发地址',
end_name                                               string          comment '目的地地址',
departure_time                                         int             comment '出发时间',
status                                                 int             comment '订单状态（2-已支付 3-已退款 4-已取消 7-部分退款 8-等待司机接单 9-司机已接单 10-司机已到达 11-服务中 12-服务结束）',
pay_type                                               int             comment '支付方式（0企业支付 1个人垫付 2混合支付 3 个人支付需报销）',
member_id                                              bigint          comment '员工在滴滴企业的id（同员工新增接口中返回的id）',
pay_time                                               int             comment '支付时间',
normal_distance                                        double          comment '总里程',
total_price                                            double          comment '总金额',
actual_price                                           double          comment '实付金额（总金额-券抵扣金额）',
refund_price                                           double          comment '退款金额',
company_pay                                            double          comment '公司支付金额',
personal_pay                                           double          comment '个人支付金额',
company_real_pay                                       double          comment '公司实付金额',
personal_real_pay                                      double          comment '个人实付金额',
company_real_refund                                    double          comment '公司实际退款金额',
personal_real_refund                                   double          comment '个人实际退款金额',
is_invoice                                             int             comment '报销开票状态（1:开过 0:未开）',
call_phone                                             string          comment '叫车人手机号',
passenger_phone                                        string          comment '乘车人手机号',
budget_center_id                                       bigint          comment '成本中心id',
use_car_type                                           int             comment '用车规则id',
order_source                                           int             comment '订单来源(0-web 1-滴滴出行app 2-h5 3-openapi 4-企业app 5-邀约券 6-sdk)',
is_carpool                                             int             comment '是否拼车(0-不是 1-是)',
encrypted_info                                         string          comment '价格加密信息',
create_datetime                                        int             comment '创建时间',
update_datetime                                        int             comment '更新时间',
begin_charge_time                                      int             comment '开始计价时间',
finish_time                                            int             comment '结束计价时间',
voucher_pay                                            double          comment '券抵扣金额',
remark                                                 string          comment '备注说明',
see_project_id                                         bigint          comment '带看id',
use_car_config_id                                      string          comment '用车规则id',
pricing_mode                                           bigint          comment 'pricing_mode',
didi_order_id                                          bigint          comment '滴滴订单id',
job_number                                             bigint          comment '员工工号',
taxi_channel_type                                      int             comment '打车渠道:1 滴滴 2 易道 3曹操',
etl_time                                               string          comment 'ETL跑数时间'
) row format delimited fields terminated by '\001' 
lines terminated by '\n' 
stored as textfile  
location '/dw/ods/yw_didi_order'
;
