drop table if exists ods.yw_deal;
create external table ods.yw_deal(
id                                                     bigint          comment '成交id',
order_id                                               bigint          comment '订单id',
creator                                                int             comment '创建人',
create_datetime                                        int             comment '创建时间',
step                                                   int             comment '成交进度 10已排号 20退排号 30已认购 40退认购 50已草签 60退草签 70已网签 80退网签',
updator                                                int             comment '更新人',
update_datetime                                        int             comment '更新时间',
status                                                 int             comment '状态 1正常 2删除',
first_deal_datetime                                    int             comment '第一次成交时间',
paihao_datetime                                        int             comment '排号时间',
rengou_datetime                                        int             comment '认购时间',
grass_sign_datetime                                    int             comment '草签时间',
sign_datetime                                          int             comment '网签时间',
back_datetime                                          int             comment '退单时间',
payment_way                                            int             comment '是否支持后置返费:0不支持，1支持',
return_poss                                            int             comment '返费可能性:1:高2:中3:低',
expect_return_datetime                                 int             comment '预计返费日期',
expect_return_money                                    double          comment '预计返费金额',
invoice_state                                          int             comment '发票状态:0:待开票1:已开票2:无需开票 默认为待开票',
invoice_datetime                                       int             comment '开票日期',
payment_situation                                      string          comment '回款情况',
return_datetime                                        int             comment '实际返回日期',
return_money                                           double          comment '实际返回金额',
is_payment                                             int             comment '0否1是默认为0',
project_name                                           string          comment '楼盘名称',
ec_payment_way                                         int             comment '是否刷电商:0否 1是',
ec_status                                              int             comment '刷电商状态:0未刷 1已刷',
ec_poss                                                int             comment '电商到账可能性:1高 2中3低',
expect_ec_datetime                                     int             comment '预计刷电商日期',
expect_ec_money                                        double          comment '预计刷电商金额',
reality_ec_datetime                                    int             comment '实际刷电商日期',
reality_ec_money                                       double          comment '实际刷电商金额',
bd_updatetime                                          int             comment '拓展修改时间',
payback_update_datetime                                int             comment '回款信息更新时间',
is_bad                                                 int             comment '是否坏单，1是2否坏单在回款信息列表里不展示',
payback_updator                                        int             comment '回款信息更新人',
finish_chargeback_datetime                             int             comment '完成退单时间',
to_account_datetime                                    int             comment '钱款到帐时间',
account_updator                                        int             comment '退单管理更新人',
account_update_datetime                                int             comment '退单管理更新时间',
account_note                                           string          comment '退款到账说明',
account_return                                         int             comment '是否到账',
first_pay_status                                       int             comment '首付收齐(1=是，2=否)(已废弃)',
first_pay_time                                         int             comment '首次付款时间(已废弃)',
first_pay_pretime                                      int             comment '首次付款预计时间(已废弃)',
full_pay_status                                        int             comment '全款收齐（1=是，2=否）(已废弃)',
full_pay_time                                          int             comment '全款到账时间(已废弃)',
full_pay_pretime                                       int             comment '预计全款到账时间(已废弃)',
loan_info_pay_status                                   int             comment '贷款资料是否上传（1=是 2=否）(已废弃)',
loan_info_pay_time                                     int             comment '贷款资料上传时间(已废弃)',
loan_info_pay_pretime                                  int             comment '预计贷款资料上传的时间(已废弃)',
loan_audited_pay_status                                int             comment '贷款审核通过(1=是,2=否)(已废弃)',
loan_audited_pay_pretime                               int             comment '预计贷款审核通过时间(已废弃)',
loan_audited_pay_time                                  int             comment '贷款审核通过时间(已废弃)',
stage_pay_status                                       int             comment '分期总数(0无分期，其他表示分期数)(已废弃)',
ban_type                                               string          comment '楼栋类型',
building_type                                          int             comment '楼盘列表/常用信息下的户型类型',
ac_acreage                                             double          comment '室内面积',
rooms                                                  int             comment '几室',
fall                                                   int             comment '几厅',
building_number                                        string          comment '楼栋号码',
acreage                                                double          comment '面积',
acreage_type                                           int             comment '面积类型:1是建筑面积，2是室内面积',
ecom_money                                             string          comment '手动修改的电商金额',
paihao_money                                           string          comment '排号刷电商金额（已作废）',
subscribe_money                                        string          comment '认购刷电商金额（已作废）',
grass_money                                            string          comment '草签刷电商金额（已作废）',
sign_money                                             string          comment '网签刷电商金额（已作废）',
back_type                                              string          comment '返费金额算法（已作废） 1按成交套数 2按成交额点位结佣，多个用逗号分隔',
back_money                                             string          comment '返费金额（元）（已作废）',
contract_id                                            bigint          comment '合同id',
category_id                                            int             comment '合同分类id',
contract_modify_datetime                               bigint          comment '修改成交单合同应收佣金时间',
contract_expect_datetime                               bigint          comment '合同预测回款更新时间',
manual_payment_datetime                                bigint          comment '人工预测回款更新时间',
actual_payment_datetime                                bigint          comment '实际回款更新时间',
see_project_id                                         bigint          comment '带看id',
project_id                                             int             comment '楼盘id',
quality_note                                           string          comment '质检说明',
quality_updator                                        int             comment '质检说明填写人',
back_percent                                           string          comment '返费百分比（已作废）',
have_confirm_sheet                                     int             comment '是否有确认单 1有 2无',
plan_upload_time                                       int             comment '预计确认单上传时间',
payment_employee_id                                    int             comment '回款负责人',
first_contract_time                                    int             comment '首次找到合同时间',
original_price                                         double          comment '原价',
premium_price                                          double          comment '溢价',
rough_price                                            double          comment '毛坯款',
fixture_price                                          double          comment '装修款',
payment_timeout_times                                  int             comment '回款跟进延迟次数',
confirm_review                                         int             comment '确认单审核状态 0未审核 1审核成功 2审核失败',
is_finish_payment                                      int             comment '是否完成全部回款  1是 2否',
finish_pay_audit                                       int             comment '成交单是否完成回款节点,并且凭证审核通过 0:否1:是',
floor                                                  int             comment '楼层',
group_buy_desc                                         string          comment '团购费类型 描述',
orientation                                            int             comment '朝向',
decorate_info                                          int             comment '装修情况，1.有装修，2毛坯',
building_position                                      string          comment '楼栋位置描述',
jump_contract_id                                       int             comment '跳点合同id',
jump_category_id                                       int             comment '跳点合同分类id',
jump_content_id                                        int             comment '跳点内容id',
back_money_total                                       double          comment '后置返费总金额',
reward_money_total                                     double          comment '成交奖总金额',
is_use_manual_payment                                  int             comment '是否启用手动修改的佣金 1是 2否',
forecast_payment_total                                 double          comment '合同预测总佣金',
etl_time                                               string          comment 'ETL跑数时间'
) row format delimited fields terminated by '\001' 
lines terminated by '\n' 
stored as textfile  
location '/dw/ods/yw_deal'
;
