drop table if exists ods.yw_employee;
create external table ods.yw_employee(
id                                                     bigint          comment '表id',
employee_name                                          string          comment '员工名字',
mobile                                                 string          comment '手机号',
personal_mobile                                        string          comment '个人私有手机号',
personal_wechat                                        string          comment '个人私有微信',
old_mobiles                                            string          comment '曾用手机号，用英文逗号隔开',
elite_flag                                             int             comment '是否可以接高端楼盘，1是，2否',
job_number                                             bigint          comment '',
create_datetime                                        bigint          comment '创建时间',
update_datetime                                        bigint          comment '修改时间',
creator                                                bigint          comment '创建者',
updator                                                bigint          comment '更新者',
email                                                  string          comment '',
password                                               string          comment '密码',
password_reset_token                                   string          comment '密钥',
auth_key                                               string          comment '验证',
sex                                                    int             comment '性别',
status                                                 int             comment '状态:0离职，1在职，2停访',
offjob_datetime                                        int             comment '离职时间',
academy                                                string          comment '毕业院校',
education                                              string          comment '学历',
birth                                                  int             comment '出生日期',
more_mobiles                                           string          comment '其他手机号，以逗号分隔',
department_name                                        string          comment '员工所在部门',
dingding_id                                            string          comment '钉钉系统中的用户id',
department_id                                          bigint          comment '部门id',
city_id                                                int             comment '城市id，城市化专用的分隔标记',
acc_token                                              string          comment '云信token，供im使用',
post_id                                                int             comment '岗位id',
didi_mobile                                            string          comment '滴滴打车手机号',
last_operation_datetime                                bigint          comment '客服上一次处理网站新上户订单的时间',
bdp_username                                           string          comment 'dbp登录账户名，用来实现bdp单点登录功能',
confluence_username                                    string          comment 'cwiki登录账户名，用来实现cwiki单点登录功能',
zentao_username                                        string          comment '禅道登录账户名，用来实现禅道单点登录功能',
ask_username                                           string          comment '问答系统登录账户名，用来实现问答系统单点登录功能',
yxt_username                                           string          comment '云学堂登录账号',
sop_days                                               int             comment 'sop连续达标天数',
header_type                                            int             comment '0:其他50:离职40:转岗220:转岗130:在职210:在职1',
last_city_id                                           int             comment '上一次城市id',
cwiki                                                  string          comment 'wiki账号----废弃此字段，与confluence_username重复',
update_password_time                                   int             comment '更新密码时间',
password_safety                                        int             comment '密码是否符合复杂性要求，passport系统会检测并且更新',
total_alloc_num                                        int             comment '上户总数',
alloc_policy                                           int             comment '分配策略 1:a组 2:b组',
is_prohibit_yxt                                        int             comment '是否禁用云学堂账号 1正常 2禁用',
adjust_city_id                                         bigint          comment '核算城市',
etl_time                                               string          comment 'ETL跑数时间'
) row format delimited fields terminated by '\001' 
lines terminated by '\n' 
stored as textfile  
location '/dw/ods/yw_employee'
;
