drop table if exists ods.yw_project_business;
create external table ods.yw_project_business(
id                                                     int             comment '',
project_id                                             bigint          comment '楼盘id',
bd_sign_id                                             int             comment 'bd单签约详情表id',
bd_order_id                                            int             comment 'bd单id（合同号）',
check_status                                           int             comment '核查状态:1，待核查，2，已核查',
project_partner_name                                   string          comment '项目合作方',
report_datetime                                        string          comment '报备时间',
report_datetime_type                                   int             comment '报备时间类型:1分钟，2小时，3天',
report_type                                            string          comment '报备方式:1微信，2短信，3邮件，4app，5公众号，6开发商系统。多个逗号隔开',
employee_report                                        int             comment '是否需要咨询师报备:1是，2否',
employee_report_type                                   string          comment '报备方式:1微信，2短信，3邮件，4app，5公众号，6开发商系统',
employee_report_desc                                   string          comment '咨询师报备说明',
wx_room_ids                                            string          comment '微信报备群id,逗号隔开',
report_template                                        string          comment '报备模板',
repeat_visit_is_report                                 int             comment '复访是否备注:1，否，2，是',
regist_is_need                                         int             comment '是否需要登记:1，需要，2，不需要',
regist_people                                          string          comment '谁来登记登记信息',
regist_place                                           string          comment '在哪登记来访信息',
is_regist_whole_mobile                                 string          comment '是否登记客户电话全号',
confirmation_sheet_is_have                             int             comment '有无确认单:1，有，2，无',
confirmation_sheet_place                               string          comment '从哪拿确认单',
confirmation_sheet_writer                              string          comment '谁填写确认单',
sign_people                                            string          comment '需要谁签字',
write_text                                             string          comment '填写的内容',
is_photo_retention                                     string          comment '是否拍照留存',
to_people_after_write                                  string          comment '填完交给谁',
protection_period_report                               string          comment '报备保护期',
protection_period_first_visit                          string          comment '首访保护期',
protection_period_repeat_visit                         string          comment '复访保护期',
protection_period_call                                 string          comment '来电保护期',
protection_period_customer                             string          comment '客户保护期',
single_decision_principle                              string          comment '撞单判定原则',
old_belt_new_system                                    string          comment '有无老带新制度',
commission_form                                        string          comment '结佣形式',
commission_point                                       string          comment '',
commission_cycle_process                               string          comment '结佣周期+流程',
scene_other_request                                    string          comment '案场其他要求',
creator                                                bigint          comment '创建者',
create_datetime                                        int             comment '创建时间',
updator                                                bigint          comment '修改者',
update_datetime                                        int             comment '修改时间',
recent_take_time_min                                   int             comment '近期可带看时间',
recent_take_time_max                                   int             comment '近期可带看时间',
quantity_description                                   string          comment '可售房源数量及说明',
subscribe_is_same                                      int             comment '认购电话和报备电话是否保持一致 1是 2否',
subscribe_file                                         string          comment '认购所需材料',
is_resubscribe                                         int             comment '是否可以退认购 1是 2否',
resubscribe_file                                       string          comment '退认购所需材料',
subscribe_refund_period                                string          comment '认购退款周期',
sign_is_same                                           int             comment '签约电话和报备电话是否保持一致 1是 2否',
average_sign_period                                    string          comment '平均签约周期',
trader_developer_description                           string          comment '操盘开发商介绍',
case_field_description                                 string          comment '案场氛围',
employee_description                                   string          comment '人员素质及接待能力',
payment_way                                            string          comment '付款方式',
cooperate_bank                                         string          comment '合作银行',
etl_time                                               string          comment 'ETL跑数时间'
) row format delimited fields terminated by '\001' 
lines terminated by '\n' 
stored as textfile  
location '/dw/ods/yw_project_business'
;
