drop table if exists ods.yw_see_project;
create external table ods.yw_see_project(
id                                                     bigint          comment '',
create_datetime                                        int             comment '',
creator                                                bigint          comment '',
update_datetime                                        int             comment '',
updator                                                bigint          comment '',
order_id                                               bigint          comment '订单id',
employee_id                                            bigint          comment '员工id',
see_employee_id                                        bigint          comment '带看人的员工id',
see_employee_adjust_city                               bigint          comment '带看咨询师核算城市',
see_employee_realname                                  string          comment '带看人的员工姓名',
employee_realname                                      string          comment '员工姓名',
user_id                                                bigint          comment '用户id',
user_realname                                          string          comment '用户姓名',
user_mobile                                            string          comment '用户手机号',
taxi_fare                                              double          comment '打车费',
phone_fare                                             double          comment '电话费',
plan_real_begin_datetime                               int             comment '计划/实际 带看开始时间',
plan_to_real_datetime                                  int             comment '预约转实际时间',
plan_real_end_datetime                                 int             comment '计划/实际 带看结束时间',
note                                                   string          comment '备注',
status                                                 int             comment '10:已预约，并自己带看  20:已预约，并且邀请其他咨询师带看  30:已预约，并且其他咨询师同意带看  40:已带看 45:已发送邀评带看的短信  50:已评价   60:取消带看',
global_comment                                         string          comment '整体评论',
employee_grade                                         int             comment '员工评价打分，3满意，2一般，0不满意',
send_invite_datetime                                   int             comment '邀评时间',
special_car                                            int             comment '是否有专车, 默认0:无，1:有',
meet_address                                           string          comment '约见地点',
see_house_people_num                                   int             comment '看房人数',
broker_name                                            string          comment '经纪人姓名',
broker_phone                                           string          comment '经纪人电话',
history_employee_id                                    int             comment '历史咨询师',
invitation_employee_id                                 bigint          comment '邀约人id',
invitation_employee_realname                           string          comment '邀约人的员工姓名',
merg_tag                                               int             comment '合并同组带看记录的id:0默认不合并，大于0表示被合并',
see_project_type                                       int             comment '带看类型 1普通带看 2关键带看 3无效带看',
audit_status                                           int             comment '关键审核状态 1未处理 2处理中 3通过 4不通过',
employee_leader_id                                     bigint          comment '咨询师主管id',
employee_leader_realname                               string          comment '咨询师主管姓名',
see_employee_leader_id                                 bigint          comment '带看咨询师主管id',
see_employee_leader_adjust_city                        bigint          comment '带看咨询师主管核算城市',
see_employee_leader_realname                           string          comment '带看咨询师主管姓名',
city_id                                                int             comment '城市id，城市化专用的分隔标记',
invitation_employee_leader_id                          bigint          comment '邀约人主管',
invitation_employee_leader_realname                    string          comment '邀约人主管姓名',
follow_tags                                            string          comment '跟进频率标签',
is_overtime                                            int             comment '是否超时0:未超时 1:已超时',
overtime_days                                          int             comment '超时天数',
pre_confirm                                            int             comment '带看前一天是否确认约见时间和地点1:未确认2已确认',
meet_lat                                               string          comment '约见地点经纬度',
meet_lng                                               string          comment '约见地点经度',
forecast_is_deal                                       int             comment '预测此次带看是否成交 1否 2是',
forecast_deal_project                                  string          comment '预测此次带看成交楼盘，逗号分隔',
sure_method                                            int             comment '确认途径，1电话 2短信 3微信',
before_see_info                                        string          comment '带看前确认附件地址/录音id',
before_sure_time                                       int             comment '带看前确认创建时间',
is_new_deal                                            int             comment '本次是否新增成交 1新增成交单 2无新增 3新增免费排卡',
is_temp                                                int             comment '是否是临时带看 0不是 1是',
have_confirmation_sheet                                int             comment '是否有客户确认单',
confirmation_sheet_pics                                string          comment '客户确认单图片，最多3张',
un_deal_reason                                         int             comment '未成交原因',
is_first_visit                                         int             comment '是否首访，或同盘首访或同盘复访:1首访2同盘复访3非同盘复访',
see_type                                               int             comment '1-线下带看 2-线上带看',
etl_time                                               string          comment 'ETL跑数时间'
) row format delimited fields terminated by '\001' 
lines terminated by '\n' 
stored as textfile  
location '/dw/ods/yw_see_project'
;
