drop table if exists ods.yw_sign_bonus_director;
create external table ods.yw_sign_bonus_director(
id                                                     bigint          comment '',
employee_id                                            int             comment '员工id',
employee_name                                          string          comment '员工姓名',
job_number                                             bigint          comment '员工工号',
department_id                                          int             comment '部门id',
city_id                                                int             comment '城市id',
adjust_city_id                                         bigint          comment '核算城市',
sign_bonus                                             double          comment '签约奖金',
actual_sign_bonus                                      double          comment '签约奖金差值',
diff_types                                             string          comment '签约奖金差值类型',
sign_bonus_base                                        double          comment '签约奖金基数值之和',
diff_a                                                 double          comment '差额a',
team_heads                                             double          comment '组内人头数',
sign_bonus_base_avg                                    double          comment '签约奖金基数值均值',
sign_commission                                        double          comment '签约佣金之和',
diff_b                                                 double          comment '差额b',
city_humans                                            double          comment '城市人力数',
y_val                                                  double          comment 'y值',
fix_ratio                                              double          comment '修正比例',
head_ratio                                             double          comment '人头数系数',
head_count_log                                         string          comment '人头数计算日志',
satisfaction                                           double          comment '总满意度',
satisfaction_month                                     int             comment '满意度月份',
satisfaction_type                                      int             comment '满意度类型0:月份满意度 1:导入满意度(兜底满意度或酒香值) 2:平均满意度',
satisfaction_than                                      double          comment '满意度比',
business_satisfaction                                  double          comment '绩效满意度',
delay_num                                              int             comment '延迟量',
team_humans                                            double          comment '组内人力数',
mystical_del                                           double          comment '神秘访客扣分',
complaint_del                                          double          comment '投诉扣分',
red_yellow_del                                         double          comment '红黄线扣分',
change_del                                             double          comment '更换咨询师扣分',
mystical_add                                           double          comment '神秘访客加分',
fixed_ratio                                            double          comment '固定系数',
type                                                   int             comment '签约奖金类型1:核算月签约奖金 2:差值签约奖金',
check_datetime                                         int             comment '该笔签约奖金首次发放时间',
adjust_datetime                                        int             comment '结算时间',
is_fix_satisfaction                                    int             comment '是否修正过满意度 0:否 1:是',
is_system                                              int             comment '是否系统添加 1:是 0:否(非系统添加不可删除)',
create_datetime                                        int             comment '创建时间',
update_datetime                                        int             comment '更新时间',
etl_time                                               string          comment 'ETL跑数时间'
) row format delimited fields terminated by '\001' 
lines terminated by '\n' 
stored as textfile  
location '/dw/ods/yw_sign_bonus_director'
;
