drop table if exists ods.yw_sign_bonus_detail;
create external table ods.yw_sign_bonus_detail(
id                                                     bigint          comment '',
city_id                                                int             comment '城市id',
adjust_city_id                                         bigint          comment '核算城市',
employee_id                                            int             comment '员工id',
employee_name                                          string          comment '员工姓名',
job_number                                             string          comment '工号',
team_leader_id                                         int             comment '组长id',
department_id                                          int             comment '部门id',
signing_adjust_amount                                  double          comment '网签核算量',
adjust_type                                            int             comment '【新规则不再维护字段】核算类型0:非签约服务人核算 1:签约服务人核算',
commission_in_contract                                 double          comment '合同内佣金',
outside_contract_commission                            double          comment '合同外佣金',
sign_commission                                        double          comment '签约佣金',
sign_commission_grade                                  double          comment '【新规则不再维护字段】职级签约佣金',
sign_bonus_base                                        double          comment '签约奖金基数值',
sign_bonus_base_grade                                  double          comment '【新规则不再维护字段】职级签约奖金基数值',
satisfaction                                           double          comment '咨询师总满意度',
satisfaction_than                                      double          comment '满意度比',
business_satisfaction                                  double          comment '咨询师绩效满意度',
deal_type                                              int             comment '成交类型',
finance_audit_datetime                                 int             comment '网签财务审核通过时间',
pay_audit_datetime                                     int             comment '回款财务审核通过时间',
sign_id                                                bigint          comment '网签id',
sign_datetime                                          int             comment '网签时间',
subscribe_datetime                                     int             comment '认购时间',
sign_bonus                                             double          comment '签约奖金',
actual_sign_bonus                                      double          comment '本次核算实发签约奖金',
actual_sign_bonus_base_grade                           double          comment '【新规则不再维护字段】本次核算实际职级签约奖金基数值',
adjust_datetime                                        int             comment '结算时间',
create_datetime                                        int             comment '创建时间',
update_datetime                                        int             comment '更新时间',
creator                                                int             comment '创建者',
updator                                                int             comment '修改者',
type                                                   int             comment '签约奖金类型 1:核算月签约奖金 2:差值签约奖金',
is_old                                                 int             comment '是否是老数据0:否 1:是',
check_diff                                             int             comment '是否算差值 1:是 0:否(部分历史网签单不按照佣金结算，是以房款核算规则)',
status                                                 int             comment '1:已网签 2:退网签 -1:删除',
is_delete                                              int             comment '是否删除 0:否 1:是',
commission_type                                        int             comment '【新规则计算签约奖金】佣金类型 1前置电商 2 后置返费 3 成交奖',
step                                                   int             comment '【新规则计算签约奖金】电商结佣阶段/返费申请阶段',
step_num                                               int             comment '【新规则计算签约奖金】第几笔回款',
is_outside_contract_commission                         int             comment '【新规则计算签约奖金】是否包含合同外佣金 0:否 1:是',
content                                                string          comment '【新规则计算签约奖金】合同预测展示文本',
etl_time                                               string          comment 'ETL跑数时间'
) row format delimited fields terminated by '\001' 
lines terminated by '\n' 
stored as textfile  
location '/dw/ods/yw_sign_bonus_detail'
;
