drop table if exists ods.zp_order;
create external table ods.zp_order(
id                                                     bigint          comment '',
bs_id                                                  bigint          comment '北森简历id',
applicant_name                                         string          comment '应聘者姓名',
applicant_sex                                          int             comment '应聘者性别 0 未知 1 男 2女',
applicant_age                                          int             comment '应聘者年龄',
city_id                                                int             comment '城市id',
applicant_first_tel                                    string          comment '联系人首要联系方式',
applicant_spare_tel                                    string          comment '应聘者备用联系方式',
applicant_email                                        string          comment '应聘者邮箱',
applicant_spare_email                                  string          comment '备用联系方式',
education_level                                        int             comment '学历 0 未知 1、高中 2、中专 3、大专 4、本科 5硕士 6博士 7专升本',
school_type                                            int             comment '学校类型 -1 未知 1 985 ，2 211，3 一本，4 二本 ，5 三本，6 专科及以下 ，7 海外院校',
work_experience                                        int             comment '工作经验 单位为月',
applicant_status                                       int             comment '求职状态 0 未知 1在职 2离职 3 应届生',
status                                                 int             comment '状态 1 未筛选 2 筛选通过 3 筛选未通过 4 电面通过 5 电面未通过 6一面通过 7一面 未通过 8 二面通过 9二面未通过 10已录入offer 12已入职',
applicant_school                                       int             comment '应聘者毕业院校id',
applicant_source                                       string          comment '简历来源',
cv_content                                             string          comment '简历正文',
cv_attachment                                          string          comment '简历附件',
is_own_offer                                           int             comment '是否拥有其它offer 0 未知 1 是 2否',
is_other_interview                                     int             comment '是否有其它面试 0 未知 1 是 2否',
is_match                                               int             comment '岗位满足其求职关注点 未知 1 是 2 否',
is_lock                                                int             comment '是否锁定 1是 2 否',
revive_count                                           int             comment '复活次数',
follow_person_id                                       int             comment '跟进人id',
is_open                                                int             comment '开关状态 1、可用 2、关闭',
close_reason                                           int             comment '关闭原因 待产品补充',
close_reson_other                                      string          comment '手动关闭订单补充原因',
phone_interviewer_id                                   int             comment '电话面试官id',
first_interviewer_id                                   int             comment '一面面试官id',
second_interviewer_id                                  int             comment '二面面试官id',
first_interviewer_datetime                             int             comment '一面面试时间',
second_interviewer_datetime                            int             comment '二面时间',
is_first_interviewer_confirm                           int             comment '一面是否确认收到分配 1 已确认 2未确认 4自动确认',
first_interviewer_confirm_datetime                     int             comment '一面确认时间',
first_interviewer_allot_datetime                       int             comment '分配一面面试官时间',
second_interviewer_allot_datetime                      int             comment '分配二面面试官时间',
is_second_interviewer_confirm                          int             comment '二面面试官是否确认收到分配 1是 2否 3已拒绝 4自动确认',
second_interviewer_confirm_datetime                    int             comment '二面面试官确认收到分配或拒绝分配时间',
phone_interviewer_datetime                             int             comment '电面时间',
is_objection                                           int             comment '是否有异议 1一面有异议 2 二面有异议 3无异议',
is_first_interviewer_reach                             int             comment '一面是否到面 1 是 2否',
is_second_interviewer_reach                            int             comment '二面是否到面 1 是 2否',
nation                                                 string          comment '民族',
school_start_time                                      int             comment '入学时间',
graduation_time                                        int             comment '毕业时间',
major_name                                             string          comment '专业名称',
birth                                                  int             comment '出生日期',
last_company                                           string          comment '最后一家公司',
last_but_one_company                                   string          comment '倒数第二家公司',
employee_id                                            int             comment '对应员工表的id',
evaluate_sms_send                                      int             comment '邀评短信系统是否发送1 已发送  2 未发送',
evaluate_sms_send_time                                 int             comment '系统发送短信首次时间',
creator                                                int             comment '创建者id',
updator                                                int             comment '更新者id',
create_datetime                                        int             comment '创建时间',
update_datetime                                        int             comment '更新时间',
get_type                                               int             comment '获取方式（对应北森）0 未知 1 主动投递 2 搜索下载 5 内部推荐 6 外部推荐 3 推荐',
temp_school_name                                       string          comment '临时学校名称',
etl_time                                               string          comment 'ETL跑数时间'
) row format delimited fields terminated by '\001' 
lines terminated by '\n' 
stored as textfile  
location '/dw/ods/zp_order'
;
