drop table if exists julive_dim.dim_clue_base_info;
create external table julive_dim.dim_clue_base_info(
skey                                              string                  comment '部门表代理键:主键',
clue_id                                           bigint                  comment '线索ID',
org_id                                            int                     comment '公司id',
org_type                                          int                     comment '类型 1 居理 2加盟',
org_name                                          string                  comment '公司名称',
channel_id                                        int                     comment '对应渠道表的channel_id',
channel_name                                      string                  comment '渠道表的渠道名称',
city_id                                           int                     comment '线索来源城市id',
city_name                                         string                  comment '线索来源城市名称',
city_seq                                          string                  comment '带开城顺序城市名称',
source                                            int                     comment '订单了解途径',
source_tc                                         string                  comment '用户来源,存储source转码结果',
user_id                                           bigint                  comment '用户id',
user_name                                         string                  comment '用户姓名',
user_mobile                                       string                  comment '用户手机号',
creator                                           string                  comment '创建人',
sex                                               int                     comment '用户性别1:男2:女',
emp_id                                            int                     comment '员工id',
emp_name                                          string                  comment '员工姓名',
follow_service                                    int                     comment '跟进客服',
follow_service_name                               string                  comment '跟进客服名称',
clue_status                                       int                     comment '线索状态ID',
clue_status_tc                                    string                  comment '线索状态Name',
is_distribute                                     int                     comment '是否分配，及不分配的原因：1、分配2、谈合作3、超区域4、不关注楼盘5、必须找售楼处6、关注二手房7、之前已上户8、不愿留电话9、电话无法接通99、其他',
distribute_tc                                     string                  comment '是否分配，及不分配的原因',
unreasonable                                      int                     comment '是否为不合理关闭订单：1是 0否',
distribute_date_diff                              int                     comment '分配距今天数',
product_id                                        int                     comment '来源产品ID',
product_name                                      string                  comment '来源产品名称',
sub_product_id                                    int                     comment '来源产品子类ID',
sub_product_name                                  string                  comment '来源产品子类名称',
customer_intent_city_id                           int                     comment '客户意向城市ID',
customer_intent_city_name                         string                  comment '客户意向城市名称',
customer_intent_city_seq                          string                  comment '带开城顺序的客户意向城市名称',
first_customer_intent_city_id                     int                     comment '客户意向城市ID',
first_customer_intent_city_name                   string                  comment '客户意向城市名称',
first_customer_intent_city_seq                    string                  comment '带开城顺序的客户意向城市名称',
op_type                                           int                     comment 'app留电口',
op_type_name_cn                                   string                  comment 'app留电口描述',
is_400_called                                     string                  comment '是否400来电,即客服订单',
short_order_tag                                   string                  comment '路径缩短订单类型标记:A 正常订单 B 缩短订单 C 参与试验缩短订单 D 参与试验正常订单',
is_recommend                                      int                     comment '友介：全',
is_cust_recommend                                 int                     comment '是否客户友介',
is_emp_recommend                                  int                     comment '是否员工友介',
is_short_alloc                                    int                     comment '是否符合路径缩短计划:1 是 0 否',
is_short_alloc_clue                               int                     comment '是否路径订单线索',
short_alloc_type                                  int                     comment '1 A组 2 B组',
order_alloc_type                                  int                     comment '订单分配成功是所属分配类型:100 路径缩短-指定问答分配 101 神秘客户 102 路径缩短-特殊线索分配 103 路径缩短-rank分配 104 路径缩短-avg分配 105 客服创建订单指定分配 106 特殊线索分配 107 rank分配 108 avg分配',
alloc_type                                        int                     comment '分配类型:10 批量分配 20 溢出分配 30 指定分配 40 特殊线索分配',
first_distribute_source                           string                  comment '分配来源-初步',
distribute_category                               int                     comment '一级分类名称',
distribute_category_desc                          string                  comment '一级分类名称描述',
sale_stage                                        string                  comment '线索所处销售阶段',
is_first_shorten_path                             string                  comment '是否路径缩短计划-初步',
last_distribute_source                            string                  comment '分配来源-终',
cust_source_type                                  string                  comment '来源归类',
distribute_time                                   string                  comment '分配时间:yyyy-MM-dd HH:mm:ss',
distribute_date                                   string                  comment '分配日期:yyyy-MM-dd',
first_distribute_time                             string                  comment '首次分配时间:yyyy-MM-dd HH:mm:ss',
first_distribute_date                             string                  comment '首次分配日期:yyyy-MM-dd',
confirm_distribute_time                           string                  comment '确认分配时间:yyyy-MM-dd HH:mm:ss',
confirm_distribute_date                           string                  comment '确认分配日期:yyyy-MM-dd',
re_distribute_time                                string                  comment '重新分配时间:yyyy-MM-dd HH:mm:ss',
re_distribute_date                                string                  comment '重新分配日期:yyyy-MM-dd',
server_distribute_time                            string                  comment '客服分配时间:yyyy-MM-dd HH:mm:ss',
server_distribute_date                            string                  comment '客服分配日期:yyyy-MM-dd',
last_distribute_time                              string                  comment '最后一次分配时间:yyyy-MM-dd HH:mm:ss',
create_time                                       string                  comment '创建时间:yyyy-MM-dd HH:mm:ss',
create_date                                       string                  comment '创建日期:yyyy-MM-dd',
update_time                                       string                  comment '更新时间:yyyy-MM-dd HH:mm:ss',
update_date                                       string                  comment '更新日期:yyyy-MM-dd',
district_id                                       string                  comment '关注区域id，逗号分隔',
district_other                                    string                  comment '区域其他',
line                                              string                  comment '环线，逗号分隔',
line_status                                       string                  comment '是否限制环线',
line_max                                          string                  comment '最大环线',
subway                                            string                  comment '地铁线，逗号分隔',
address                                           string                  comment '地址',
house_type                                        string                  comment '户型，逗号分隔',
project_type                                      string                  comment '业态类型',
project_type_name                                 string                  comment '业态名称',
acreage_min                                       string                  comment '最小面积',
acreage_max                                       string                  comment '最大面积',
total_price_min                                   string                  comment '最小总价',
total_price_max                                   string                  comment '最大总价',
budget_range_grade                                string                  comment '预算区间：通过最大总价计算',
unit_price_min                                    string                  comment '最小单价',
unit_price_max                                    string                  comment '最大单价',
first_price_min                                   string                  comment '最小首付',
first_price_max                                   string                  comment '最大首付',
month_price_min                                   string                  comment '最小月供',
month_price_max                                   string                  comment '最大月供',
interest_project                                  string                  comment '客户感兴趣楼盘id，用逗号隔开',
recommend_project_id                              string                  comment '侃家推荐楼盘id，用逗号隔开',
saw_project                                       string                  comment '之前看过楼盘ID，用逗号隔开',
see_datetime                                      string                  comment '用户看房时间:yyyy-MM-dd HH:mm:ss',
interest_project_name                             string                  comment '客户感兴趣楼盘名称，用逗号隔开',
interest_project_type_name_list                   string                  comment '线索感兴趣的楼盘业态列表',
recommend_project_name                            string                  comment '侃家推荐楼盘名称，用逗号隔开',
saw_project_name                                  string                  comment '之前看过楼盘名称，用逗号隔开',
investment                                        string                  comment '是否是投资',
qualifications                                    string                  comment '是否有资质',
intent                                            int                     comment '1.无意向 2.保留 3.有意向',
intent_tc                                         string                  comment '1.无意向 2.保留 3.有意向',
intent_enddate                                    string                  comment '意向保留截止日期:yyyy-MM-dd HH:mm:ss',
intent_low_time                                   string                  comment '变为无意向的时间:yyyy-MM-dd HH:mm:ss',
intent_employee_id                                string                  comment '意向咨询师id',
intent_employee_name                              string                  comment '意向咨询师名称',
intent_no_like                                    string                  comment '无意向说明',
lowintent_reincustomer_datetime                   string                  comment '无意向重新上户时间:yyyy-MM-dd HH:mm:ss',
intent_low_reason                                 string                  comment '关闭客户原因（即无意向原因',
is_elite                                          string                  comment '是否是高端客户（最高总结在600万以上的就是高端客户），1是，2否',
building_type                                     string                  comment '建筑类型',
purchase_purpose                                  int                     comment '购房目的:1刚需，2改善，3投资，4自助+投资',
purchase_purpose_tc                               string                  comment '购房目的:1刚需，2改善，3投资，4自助+投资',
purchase_urgency                                  string                  comment '购房紧迫度:1高，2中，3低',
accept_other_area                                 string                  comment '是否接受其它区域:1是，2否',
see_time                                          string                  comment '可看房时间:1工作日，2周末，3随时，4其它',
see_time_desc                                     string                  comment '可看房时间（其它）说明',
focus_point                                       string                  comment '新关注点字段--旧的输入框改为多选项:1交通便利，2通勤，3教育，4商业，5医疗，6环境，7养老，8配套，9投资升值，10区域，11性价比，12户型，13楼盘品质，14现房，15地段,16样式',
resistance_point                                  string                  comment '抗性点',
coordination_degree                               string                  comment '配合程度:1高，2中，3低',
has_main_push_projects                            string                  comment '客户感兴趣楼盘是否有当期主推楼盘1:否2:是',
investors                                         string                  comment '出资人',
decisionor                                        string                  comment '决策人',
disturbor                                         string                  comment '决策影响人',
family_funds                                      string                  comment '家庭及资金',
other_desc                                        string                  comment '其它说明',
estate_by_name                                    string                  comment '名下房产有或无0无1有默认为0',
estate_by_name_desc                               string                  comment '名下房产说明',
whether_house                                     string                  comment '1 否 2是',
customer_description                              string                  comment '客户描摹',
close_explan                                      string                  comment '订单关闭原因说明',
is_pause_follow                                   int                     COMMENT '是否是暂停跟进关闭的订单 :0否1是',
clue_score                                        string                  comment '线索质量分',
is_ai_service                                     int                     comment '是否是ai客服 1是0否',
from_source                                       int                     comment '数据来源: 1-居理数据 2-乌鲁木齐虚拟项目数据 3-二手房中介项目数据 4-加盟商数据',
from_source_detail                                int                     comment '数据来源: 1-居理数据 11-自营(ai客服) 2-乌鲁木齐虚拟项目数据 3-二手房中介项目数据 31-来源xpt_order二手房中介数据 4-加盟商数据',
separate_feature                                  map<string,string>      comment '所属业务线独立数据',
etl_time                                          string                  comment 'ETL跑数日期'
) comment '线索维度基表-包含多条业务线数据 from_source区分'
stored as parquet 
;


-- 子表schma生成逻辑 
drop table if exists julive_dim.dim_wlmq_clue_info;
create external table julive_dim.dim_wlmq_clue_info like julive_dim.dim_clue_base_info;
drop table if exists julive_dim.dim_clue_info;
create external table julive_dim.dim_clue_info like julive_dim.dim_clue_base_info;
drop table if exists julive_dim.dim_esf_clue_info;
create external table julive_dim.dim_esf_clue_info like julive_dim.dim_clue_base_info;
drop table if exists julive_dim.dim_jms_clue_info;
create external table julive_dim.dim_jms_clue_info like julive_dim.dim_clue_base_info;

