drop table if exists julive_dim.dim_house_info;
CREATE EXTERNAL TABLE julive_dim.dim_house_info(
house_id                bigint COMMENT '户型id', 
app_house_type_id       int    COMMENT '咨询师编辑户型id', 
house_type_num          string COMMENT '户型编号（业务编号）',
  
project_type            bigint COMMENT '项目类型',
project_type_desc       string COMMENT '项目类型注释', 
room_type               int    COMMENT '厅室类别', 
room_type_desc          string COMMENT '厅室类别注释',
summary                 string COMMENT '厅室描述',
is_show_room_type       int    COMMENT '是否展现厅室类别，1: 否  2:是', 
orientation             string COMMENT '房屋朝向', 
good_desc               string COMMENT '优势描述', 
bad_desc                string COMMENT '劣势描述', 
is_loft                 int    COMMENT '是否loft:1是，2否', 
building_type           int    COMMENT '建筑类型', 
building_type_desc      string COMMENT '建筑类型注释',
house_tag               string COMMENT '户型标签',
small_family            int    COMMENT '是否是小户型 1:是2:否,面积在0-80平,脚本自动计算', 
low_price               int    COMMENT '是否是低总价 1:是2:否,价格在0-2百万,脚本自动计算', 
layout_shi              int    COMMENT '几室', 
layout_ting             int    COMMENT '几厅', 
layout_chu              int    COMMENT '几厨', 
layout_wei              int    COMMENT '几卫', 
master_bed_room         string COMMENT '主卧居室详解', 
toilet                  string COMMENT '卫生间居室详解', 
living_room             string COMMENT '客厅详解', 
kitchen                 string COMMENT '厨房详解', 
restaurant              string COMMENT '餐厅详解', 
terrace                 string COMMENT '露台详解', 
  
acreage                 int    COMMENT '建筑面积', 
ac_acreage              string COMMENT '套内面积', 
price                   double COMMENT '总价', 
down_pay                double COMMENT '首付',
payment_ratio           double COMMENT '首付比例',  
month_pay               double COMMENT '月供', 
total_count             int    COMMENT '总套数', 
surplus_count           int    COMMENT '剩余套数', 
trans_price             double COMMENT '成交单价', 
offer_price             double COMMENT '报价单价', 
rate                    double COMMENT '平均折扣', 
  
status                  int    COMMENT '在售状态', 
status_desc             string COMMENT '在售状态注释',
house_on_sale_num       int    COMMENT '户型在售余量', 
house_on_sale_tag       int    COMMENT '剩余房源标签', 
house_on_sale_tag_desc  string COMMENT '剩余房源标签注释',
is_false                int    COMMENT '是否是假户型 1:是 2否', 
  
project_id              bigint COMMENT '楼盘id', 
employee_id             bigint COMMENT '咨询师id', 
employee_name           string COMMENT '咨询师姓名', 
create_datetime         bigint COMMENT '创建时间', 
update_datetime         bigint COMMENT '更新时间'
)
stored as parquet;

