CREATE VIEW `julive_dim.dim_ps_employee_info` AS SELECT `skey` AS `skey`, `emp_id` AS `emp_id`, `emp_name` AS `emp_name`, `from_source` AS `from_source`, `job_number` AS `job_number`, `card_no` AS `card_no`, `sex` AS `sex`, `sex_tc` AS `sex_tc`, `nation` AS `nation`, `domicile_address` AS `domicile_address`, `marital_status` AS `marital_status`, `marital_status_tc` AS `marital_status_tc`, `birthday` AS `birthday`, `age` AS `age`, `employment_form` AS `employment_form`, `employment_form_tc` AS `employment_form_tc`, `political_outlook` AS `political_outlook`, `graduation_school` AS `graduation_school`, `school_attributes` AS `school_attributes`, `graduation_date` AS `graduation_date`, `major` AS `major`, `first_work_date` AS `first_work_date`, `high_major` AS `high_major`, `high_major_tc` AS `high_major_tc`, `contract` AS `contract`, `ascription` AS `ascription`, `orgi_entry_date` AS `orgi_entry_date`, `entry_date` AS `entry_date`, `full_date` AS `full_date`, `full_type` AS `full_type`, `full_type_tc` AS `full_type_tc`, `offjob_date` AS `offjob_date`, `first_contract_date` AS `first_contract_date`, `end_contract_date` AS `end_contract_date`, `post_id` AS `post_id`, `post_name` AS `post_name`, `management_form` AS `management_form`, `management_form_tc` AS `management_form_tc`, `dept_attr` AS `dept_attr`, `dept_attr_tc` AS `dept_attr_tc`, `city_id` AS `city_id`, `city_name` AS `city_name`, `adjust_city_id` AS `adjust_city_id`, `adjust_city_name` AS `adjust_city_name`, `job_status` AS `job_status`, `job_status_tc` AS `job_status_tc`, `direct_leader_id` AS `direct_leader_id`, `direct_leader_name` AS `direct_leader_name`, `indirect_leader_id` AS `indirect_leader_id`, `indirect_leader_name` AS `indirect_leader_name`, `dept_id` AS `dept_id`, `dept_name` AS `dept_name`, `dept_level` AS `dept_level`, `team_leader_id` AS `team_leader_id`, `team_leader_name` AS `team_leader_name`, `cate_id` AS `cate_id`, `cate_name` AS `cate_name`, `dept_type_id` AS `dept_type_id`, `dept_type_name` AS `dept_type_name`, `dept_level_leader` AS `dept_level_leader`, `dept_id_first` AS `dept_id_first`, `dept_name_first` AS `dept_name_first`, `dept_leader_id_first` AS `dept_leader_id_first`, `dept_leader_name_first` AS `dept_leader_name_first`, `dept_id_second` AS `dept_id_second`, `dept_name_second` AS `dept_name_second`, `dept_leader_id_second` AS `dept_leader_id_second`, `dept_leader_name_second` AS `dept_leader_name_second`, `dept_id_third` AS `dept_id_third`, `dept_name_third` AS `dept_name_third`, `dept_leader_id_third` AS `dept_leader_id_third`, `dept_leader_name_third` AS `dept_leader_name_third`, `dept_id_fourth` AS `dept_id_fourth`, `dept_name_fourth` AS `dept_name_fourth`, `dept_leader_id_fourth` AS `dept_leader_id_fourth`, `dept_leader_name_fourth` AS `dept_leader_name_fourth`, `dept_id_fifth` AS `dept_id_fifth`, `dept_name_fifth` AS `dept_name_fifth`, `dept_leader_id_fifth` AS `dept_leader_id_fifth`, `dept_leader_name_fifth` AS `dept_leader_name_fifth`, `dept_id_sixth` AS `dept_id_sixth`, `dept_name_sixth` AS `dept_name_sixth`, `dept_leader_id_sixth` AS `dept_leader_id_sixth`, `dept_leader_name_sixth` AS `dept_leader_name_sixth`, `dept_id_seventh` AS `dept_id_seventh`, `dept_name_seventh` AS `dept_name_seventh`, `dept_leader_id_seventh` AS `dept_leader_id_seventh`, `dept_leader_name_seventh` AS `dept_leader_name_seventh`, `dept_id_eighth` AS `dept_id_eighth`, `dept_name_eighth` AS `dept_name_eighth`, `dept_leader_id_eighth` AS `dept_leader_id_eighth`, `dept_leader_name_eighth` AS `dept_leader_name_eighth`, `create_date` AS `create_date`, `version` AS `version`, `status` AS `status`, `start_date` AS `start_date`, `etl_time` AS `etl_time`, `end_date` AS `end_date`, `pdate` AS `pdate` FROM (select `dim_employee_info`.`skey`, `dim_employee_info`.`emp_id`, `dim_employee_info`.`emp_name`, `dim_employee_info`.`from_source`, `dim_employee_info`.`job_number`, `dim_employee_info`.`card_no`, `dim_employee_info`.`sex`, `dim_employee_info`.`sex_tc`, `dim_employee_info`.`nation`, `dim_employee_info`.`domicile_address`, `dim_employee_info`.`marital_status`, `dim_employee_info`.`marital_status_tc`, `dim_employee_info`.`birthday`, `dim_employee_info`.`age`, `dim_employee_info`.`employment_form`, `dim_employee_info`.`employment_form_tc`, `dim_employee_info`.`political_outlook`, `dim_employee_info`.`graduation_school`, `dim_employee_info`.`school_attributes`, `dim_employee_info`.`graduation_date`, `dim_employee_info`.`major`, `dim_employee_info`.`first_work_date`, `dim_employee_info`.`high_major`, `dim_employee_info`.`high_major_tc`, `dim_employee_info`.`contract`, `dim_employee_info`.`ascription`, `dim_employee_info`.`orgi_entry_date`, `dim_employee_info`.`entry_date`, `dim_employee_info`.`full_date`, `dim_employee_info`.`full_type`, `dim_employee_info`.`full_type_tc`, `dim_employee_info`.`offjob_date`, `dim_employee_info`.`first_contract_date`, `dim_employee_info`.`end_contract_date`, `dim_employee_info`.`post_id`, `dim_employee_info`.`post_name`, `dim_employee_info`.`management_form`, `dim_employee_info`.`management_form_tc`, `dim_employee_info`.`dept_attr`, `dim_employee_info`.`dept_attr_tc`, `dim_employee_info`.`city_id`, `dim_employee_info`.`city_name`, `dim_employee_info`.`adjust_city_id`, `dim_employee_info`.`adjust_city_name`, `dim_employee_info`.`job_status`, `dim_employee_info`.`job_status_tc`, `dim_employee_info`.`direct_leader_id`, `dim_employee_info`.`direct_leader_name`, `dim_employee_info`.`indirect_leader_id`, `dim_employee_info`.`indirect_leader_name`, `dim_employee_info`.`dept_id`, `dim_employee_info`.`dept_name`, `dim_employee_info`.`dept_level`, `dim_employee_info`.`team_leader_id`, `dim_employee_info`.`team_leader_name`, `dim_employee_info`.`cate_id`, `dim_employee_info`.`cate_name`, `dim_employee_info`.`dept_type_id`, `dim_employee_info`.`dept_type_name`, `dim_employee_info`.`dept_level_leader`, `dim_employee_info`.`dept_id_first`, `dim_employee_info`.`dept_name_first`, `dim_employee_info`.`dept_leader_id_first`, `dim_employee_info`.`dept_leader_name_first`, `dim_employee_info`.`dept_id_second`, `dim_employee_info`.`dept_name_second`, `dim_employee_info`.`dept_leader_id_second`, `dim_employee_info`.`dept_leader_name_second`, `dim_employee_info`.`dept_id_third`, `dim_employee_info`.`dept_name_third`, `dim_employee_info`.`dept_leader_id_third`, `dim_employee_info`.`dept_leader_name_third`, `dim_employee_info`.`dept_id_fourth`, `dim_employee_info`.`dept_name_fourth`, `dim_employee_info`.`dept_leader_id_fourth`, `dim_employee_info`.`dept_leader_name_fourth`, `dim_employee_info`.`dept_id_fifth`, `dim_employee_info`.`dept_name_fifth`, `dim_employee_info`.`dept_leader_id_fifth`, `dim_employee_info`.`dept_leader_name_fifth`, `dim_employee_info`.`dept_id_sixth`, `dim_employee_info`.`dept_name_sixth`, `dim_employee_info`.`dept_leader_id_sixth`, `dim_employee_info`.`dept_leader_name_sixth`, `dim_employee_info`.`dept_id_seventh`, `dim_employee_info`.`dept_name_seventh`, `dim_employee_info`.`dept_leader_id_seventh`, `dim_employee_info`.`dept_leader_name_seventh`, `dim_employee_info`.`dept_id_eighth`, `dim_employee_info`.`dept_name_eighth`, `dim_employee_info`.`dept_leader_id_eighth`, `dim_employee_info`.`dept_leader_name_eighth`, `dim_employee_info`.`create_date`, `dim_employee_info`.`version`, `dim_employee_info`.`status`, `dim_employee_info`.`start_date`, `dim_employee_info`.`etl_time`, `dim_employee_info`.`end_date`, `dim_employee_info`.`pdate` from `julive_dim`.`dim_employee_info`) `julive_dim.dim_ps_employee_info`
;

-- hive中查到建表语句，实际是从julive_dim.dim_employee_base_info中取数据
CREATE VIEW `julive_dim.dim_ps_employee_info` AS SELECT
        `julive_dim.dim_ps_employee_info`.`skey` AS `skey`,
        `julive_dim.dim_ps_employee_info`.`emp_id` AS `emp_id`,
        `julive_dim.dim_ps_employee_info`.`emp_name` AS `emp_name`,
        `julive_dim.dim_ps_employee_info`.`from_source` AS `from_source`,
        `julive_dim.dim_ps_employee_info`.`job_number` AS `job_number`,
        `julive_dim.dim_ps_employee_info`.`card_no` AS `card_no`,
        `julive_dim.dim_ps_employee_info`.`sex` AS `sex`,
        `julive_dim.dim_ps_employee_info`.`sex_tc` AS `sex_tc`,
        `julive_dim.dim_ps_employee_info`.`nation` AS `nation`,
        `julive_dim.dim_ps_employee_info`.`domicile_address` AS `domicile_address`,
        `julive_dim.dim_ps_employee_info`.`marital_status` AS `marital_status`,
        `julive_dim.dim_ps_employee_info`.`marital_status_tc` AS `marital_status_tc`,
        `julive_dim.dim_ps_employee_info`.`birthday` AS `birthday`,
        `julive_dim.dim_ps_employee_info`.`age` AS `age`,
        `julive_dim.dim_ps_employee_info`.`employment_form` AS `employment_form`,
        `julive_dim.dim_ps_employee_info`.`employment_form_tc` AS `employment_form_tc`,
        `julive_dim.dim_ps_employee_info`.`political_outlook` AS `political_outlook`,
        `julive_dim.dim_ps_employee_info`.`graduation_school` AS `graduation_school`,
        `julive_dim.dim_ps_employee_info`.`school_attributes` AS `school_attributes`,
        `julive_dim.dim_ps_employee_info`.`graduation_date` AS `graduation_date`,
        `julive_dim.dim_ps_employee_info`.`major` AS `major`,
        `julive_dim.dim_ps_employee_info`.`first_work_date` AS `first_work_date`,
        `julive_dim.dim_ps_employee_info`.`high_major` AS `high_major`,
        `julive_dim.dim_ps_employee_info`.`high_major_tc` AS `high_major_tc`,
        `julive_dim.dim_ps_employee_info`.`contract` AS `contract`,
        `julive_dim.dim_ps_employee_info`.`ascription` AS `ascription`,
        `julive_dim.dim_ps_employee_info`.`orgi_entry_date` AS `orgi_entry_date`,
        `julive_dim.dim_ps_employee_info`.`entry_date` AS `entry_date`,
        `julive_dim.dim_ps_employee_info`.`full_date` AS `full_date`,
        `julive_dim.dim_ps_employee_info`.`full_type` AS `full_type`,
        `julive_dim.dim_ps_employee_info`.`full_type_tc` AS `full_type_tc`,
        `julive_dim.dim_ps_employee_info`.`offjob_date` AS `offjob_date`,
        `julive_dim.dim_ps_employee_info`.`first_contract_date` AS `first_contract_date`,
        `julive_dim.dim_ps_employee_info`.`end_contract_date` AS `end_contract_date`,
        `julive_dim.dim_ps_employee_info`.`post_id` AS `post_id`,
        `julive_dim.dim_ps_employee_info`.`post_name` AS `post_name`,
        `julive_dim.dim_ps_employee_info`.`management_form` AS `management_form`,
        `julive_dim.dim_ps_employee_info`.`management_form_tc` AS `management_form_tc`,
        `julive_dim.dim_ps_employee_info`.`dept_attr` AS `dept_attr`,
        `julive_dim.dim_ps_employee_info`.`dept_attr_tc` AS `dept_attr_tc`,
        `julive_dim.dim_ps_employee_info`.`city_id` AS `city_id`,
        `julive_dim.dim_ps_employee_info`.`city_name` AS `city_name`,
        `julive_dim.dim_ps_employee_info`.`adjust_city_id` AS `adjust_city_id`,
        `julive_dim.dim_ps_employee_info`.`adjust_city_name` AS `adjust_city_name`,
        `julive_dim.dim_ps_employee_info`.`job_status` AS `job_status`,
        `julive_dim.dim_ps_employee_info`.`job_status_tc` AS `job_status_tc`,
        `julive_dim.dim_ps_employee_info`.`direct_leader_id` AS `direct_leader_id`,
        `julive_dim.dim_ps_employee_info`.`direct_leader_name` AS `direct_leader_name`,
        `julive_dim.dim_ps_employee_info`.`indirect_leader_id` AS `indirect_leader_id`,
        `julive_dim.dim_ps_employee_info`.`indirect_leader_name` AS `indirect_leader_name`,
        `julive_dim.dim_ps_employee_info`.`dept_id` AS `dept_id`,
        `julive_dim.dim_ps_employee_info`.`dept_name` AS `dept_name`,
        `julive_dim.dim_ps_employee_info`.`dept_level` AS `dept_level`,
        `julive_dim.dim_ps_employee_info`.`team_leader_id` AS `team_leader_id`,
        `julive_dim.dim_ps_employee_info`.`team_leader_name` AS `team_leader_name`,
        `julive_dim.dim_ps_employee_info`.`cate_id` AS `cate_id`,
        `julive_dim.dim_ps_employee_info`.`cate_name` AS `cate_name`,
        `julive_dim.dim_ps_employee_info`.`dept_type_id` AS `dept_type_id`,
        `julive_dim.dim_ps_employee_info`.`dept_type_name` AS `dept_type_name`,
        `julive_dim.dim_ps_employee_info`.`dept_level_leader` AS `dept_level_leader`,
        `julive_dim.dim_ps_employee_info`.`dept_id_first` AS `dept_id_first`,
        `julive_dim.dim_ps_employee_info`.`dept_name_first` AS `dept_name_first`,
        `julive_dim.dim_ps_employee_info`.`dept_leader_id_first` AS `dept_leader_id_first`,
        `julive_dim.dim_ps_employee_info`.`dept_leader_name_first` AS `dept_leader_name_first`,
        `julive_dim.dim_ps_employee_info`.`dept_id_second` AS `dept_id_second`,
        `julive_dim.dim_ps_employee_info`.`dept_name_second` AS `dept_name_second`,
        `julive_dim.dim_ps_employee_info`.`dept_leader_id_second` AS `dept_leader_id_second`,
        `julive_dim.dim_ps_employee_info`.`dept_leader_name_second` AS `dept_leader_name_second`,
        `julive_dim.dim_ps_employee_info`.`dept_id_third` AS `dept_id_third`,
        `julive_dim.dim_ps_employee_info`.`dept_name_third` AS `dept_name_third`,
        `julive_dim.dim_ps_employee_info`.`dept_leader_id_third` AS `dept_leader_id_third`,
        `julive_dim.dim_ps_employee_info`.`dept_leader_name_third` AS `dept_leader_name_third`,
        `julive_dim.dim_ps_employee_info`.`dept_id_fourth` AS `dept_id_fourth`,
        `julive_dim.dim_ps_employee_info`.`dept_name_fourth` AS `dept_name_fourth`,
        `julive_dim.dim_ps_employee_info`.`dept_leader_id_fourth` AS `dept_leader_id_fourth`,
        `julive_dim.dim_ps_employee_info`.`dept_leader_name_fourth` AS `dept_leader_name_fourth`,
        `julive_dim.dim_ps_employee_info`.`dept_id_fifth` AS `dept_id_fifth`,
        `julive_dim.dim_ps_employee_info`.`dept_name_fifth` AS `dept_name_fifth`,
        `julive_dim.dim_ps_employee_info`.`dept_leader_id_fifth` AS `dept_leader_id_fifth`,
        `julive_dim.dim_ps_employee_info`.`dept_leader_name_fifth` AS `dept_leader_name_fifth`,
        `julive_dim.dim_ps_employee_info`.`dept_id_sixth` AS `dept_id_sixth`,
        `julive_dim.dim_ps_employee_info`.`dept_name_sixth` AS `dept_name_sixth`,
        `julive_dim.dim_ps_employee_info`.`dept_leader_id_sixth` AS `dept_leader_id_sixth`,
        `julive_dim.dim_ps_employee_info`.`dept_leader_name_sixth` AS `dept_leader_name_sixth`,
        `julive_dim.dim_ps_employee_info`.`dept_id_seventh` AS `dept_id_seventh`,
        `julive_dim.dim_ps_employee_info`.`dept_name_seventh` AS `dept_name_seventh`,
        `julive_dim.dim_ps_employee_info`.`dept_leader_id_seventh` AS `dept_leader_id_seventh`,
        `julive_dim.dim_ps_employee_info`.`dept_leader_name_seventh` AS `dept_leader_name_seventh`,
        `julive_dim.dim_ps_employee_info`.`dept_id_eighth` AS `dept_id_eighth`,
        `julive_dim.dim_ps_employee_info`.`dept_name_eighth` AS `dept_name_eighth`,
        `julive_dim.dim_ps_employee_info`.`dept_leader_id_eighth` AS `dept_leader_id_eighth`,
        `julive_dim.dim_ps_employee_info`.`dept_leader_name_eighth` AS `dept_leader_name_eighth`,
        `julive_dim.dim_ps_employee_info`.`create_date` AS `create_date`,
        `julive_dim.dim_ps_employee_info`.`version` AS `version`,
        `julive_dim.dim_ps_employee_info`.`status` AS `status`,
        `julive_dim.dim_ps_employee_info`.`start_date` AS `start_date`,
        `julive_dim.dim_ps_employee_info`.`etl_time` AS `etl_time`,
        `julive_dim.dim_ps_employee_info`.`end_date` AS `end_date`,
        `julive_dim.dim_ps_employee_info`.`pdate` AS `pdate`
    FROM
        (SELECT
            `dim_employee_info`.`skey`,
                `dim_employee_info`.`emp_id`,
                `dim_employee_info`.`emp_name`,
                `dim_employee_info`.`from_source`,
                `dim_employee_info`.`job_number`,
                `dim_employee_info`.`card_no`,
                `dim_employee_info`.`sex`,
                `dim_employee_info`.`sex_tc`,
                `dim_employee_info`.`nation`,
                `dim_employee_info`.`domicile_address`,
                `dim_employee_info`.`marital_status`,
                `dim_employee_info`.`marital_status_tc`,
                `dim_employee_info`.`birthday`,
                `dim_employee_info`.`age`,
                `dim_employee_info`.`employment_form`,
                `dim_employee_info`.`employment_form_tc`,
                `dim_employee_info`.`political_outlook`,
                `dim_employee_info`.`graduation_school`,
                `dim_employee_info`.`school_attributes`,
                `dim_employee_info`.`graduation_date`,
                `dim_employee_info`.`major`,
                `dim_employee_info`.`first_work_date`,
                `dim_employee_info`.`high_major`,
                `dim_employee_info`.`high_major_tc`,
                `dim_employee_info`.`contract`,
                `dim_employee_info`.`ascription`,
                `dim_employee_info`.`orgi_entry_date`,
                `dim_employee_info`.`entry_date`,
                `dim_employee_info`.`full_date`,
                `dim_employee_info`.`full_type`,
                `dim_employee_info`.`full_type_tc`,
                `dim_employee_info`.`offjob_date`,
                `dim_employee_info`.`first_contract_date`,
                `dim_employee_info`.`end_contract_date`,
                `dim_employee_info`.`post_id`,
                `dim_employee_info`.`post_name`,
                `dim_employee_info`.`management_form`,
                `dim_employee_info`.`management_form_tc`,
                `dim_employee_info`.`dept_attr`,
                `dim_employee_info`.`dept_attr_tc`,
                `dim_employee_info`.`city_id`,
                `dim_employee_info`.`city_name`,
                `dim_employee_info`.`adjust_city_id`,
                `dim_employee_info`.`adjust_city_name`,
                `dim_employee_info`.`job_status`,
                `dim_employee_info`.`job_status_tc`,
                `dim_employee_info`.`direct_leader_id`,
                `dim_employee_info`.`direct_leader_name`,
                `dim_employee_info`.`indirect_leader_id`,
                `dim_employee_info`.`indirect_leader_name`,
                `dim_employee_info`.`dept_id`,
                `dim_employee_info`.`dept_name`,
                `dim_employee_info`.`dept_level`,
                `dim_employee_info`.`team_leader_id`,
                `dim_employee_info`.`team_leader_name`,
                `dim_employee_info`.`cate_id`,
                `dim_employee_info`.`cate_name`,
                `dim_employee_info`.`dept_type_id`,
                `dim_employee_info`.`dept_type_name`,
                `dim_employee_info`.`dept_level_leader`,
                `dim_employee_info`.`dept_id_first`,
                `dim_employee_info`.`dept_name_first`,
                `dim_employee_info`.`dept_leader_id_first`,
                `dim_employee_info`.`dept_leader_name_first`,
                `dim_employee_info`.`dept_id_second`,
                `dim_employee_info`.`dept_name_second`,
                `dim_employee_info`.`dept_leader_id_second`,
                `dim_employee_info`.`dept_leader_name_second`,
                `dim_employee_info`.`dept_id_third`,
                `dim_employee_info`.`dept_name_third`,
                `dim_employee_info`.`dept_leader_id_third`,
                `dim_employee_info`.`dept_leader_name_third`,
                `dim_employee_info`.`dept_id_fourth`,
                `dim_employee_info`.`dept_name_fourth`,
                `dim_employee_info`.`dept_leader_id_fourth`,
                `dim_employee_info`.`dept_leader_name_fourth`,
                `dim_employee_info`.`dept_id_fifth`,
                `dim_employee_info`.`dept_name_fifth`,
                `dim_employee_info`.`dept_leader_id_fifth`,
                `dim_employee_info`.`dept_leader_name_fifth`,
                `dim_employee_info`.`dept_id_sixth`,
                `dim_employee_info`.`dept_name_sixth`,
                `dim_employee_info`.`dept_leader_id_sixth`,
                `dim_employee_info`.`dept_leader_name_sixth`,
                `dim_employee_info`.`dept_id_seventh`,
                `dim_employee_info`.`dept_name_seventh`,
                `dim_employee_info`.`dept_leader_id_seventh`,
                `dim_employee_info`.`dept_leader_name_seventh`,
                `dim_employee_info`.`dept_id_eighth`,
                `dim_employee_info`.`dept_name_eighth`,
                `dim_employee_info`.`dept_leader_id_eighth`,
                `dim_employee_info`.`dept_leader_name_eighth`,
                `dim_employee_info`.`create_date`,
                `dim_employee_info`.`version`,
                `dim_employee_info`.`status`,
                `dim_employee_info`.`start_date`,
                `dim_employee_info`.`etl_time`,
                `dim_employee_info`.`end_date`,
                `dim_employee_info`.`pdate`
        FROM
            `julive_dim`.`dim_employee_base_info` as `dim_employee_info`
) `julive_dim.dim_ps_employee_info`
;