 

drop view if exists julive_fact.fact_event_dtl_white_view;
create view julive_fact.fact_event_dtl_white_view(

skey                                              comment '记录唯一标识',
session_id                                        comment '默认规则切割session标识:pc-5分钟 m-1分钟 app(视频)-3分钟 小程序-1分钟 其他-不切割session',
prev_event_elapse                                 comment '与上一条事件时间间隔,单位(秒)',
next_event_elapse                                 comment '与下一条事件时间间隔,单位(秒)',
user_access_seq_asc_today                         comment '当天内用户访问行为序列-正序',
user_access_seq_desc_today                        comment '当天内用户访问行为序列-倒序',
global_id                                         comment '全局唯一ID',
distinct_id                                       comment '神策自动生成的用户标识', 
map_id                                            comment '映射id通常和DISTINCT_ID相同',
user_id                                           comment '神策USER_ID',
julive_id                                         comment '居理用户ID',
comjia_unique_id                                  comment '用户ID',
cookie_id                                         comment 'COOKIE ID',
open_id                                           comment '公众号用户唯一标识',
product_id                                        comment '产品ID',
product_name                                      comment '产品名称', -- 由product_id产出 
track_id                                          comment '埋点ID(对应CMS中)',
event                                             comment '事件名称',
create_time                                       comment '事件创建时间(time):yyyy-MM-dd HH:mm:ss',
create_timestamp                                  comment '事件创建原始时间戳',
recv_time                                         comment 'nginx接收时间:yyyy-MM-dd HH:mm:ss',
fl_project_id                                     comment '项目ID',
fl_project_name                                   comment '项目名称',
app_id                                            comment '设备端',
p_ip                                              comment '用户使用设备的 IP',
idfa                                              comment 'IOS设备名',
idfv                                              comment 'IOS设备编号',
channel_id                                        comment '渠道ID',
login_employee_id                                 comment '员工工号',
project_id                                        comment '进入页面前的楼盘ID',
comjia_android_id                                 comment '安卓id设备标识',
comjia_device_id                                  comment '设备id',
comjia_imei                                       comment 'imei-安卓设备标识:coalesce(comjia_imei,imei)',
visitor_id                                        comment '用户id(pc/m=cookie_id/distinct_id app=加密后install_id 小程序=open_id)',
order_id                                          comment '订单ID',
adviser_id                                        comment '咨询师ID',
fromitemindex                                     comment '位置编号',
fromitem                                          comment '按钮',
frompage                                          comment '当前页面',
topage                                            comment '到达页面',
frommodule                                        comment '当前模块',
tomodule                                          comment '到达模块',
p_is_first_day                                    comment '是否首日访问',
p_is_first_time                                   comment '是否首次访问',
app_version                                       comment 'APP版本号:短',
p_app_version                                     comment 'APP版本号',
select_city                                       comment '选择的城市ID',
lat                                               comment '经度',
lng                                               comment '维度',
current_url                                       comment '落地页的URL',
to_url                                            comment '跳转链接',
referer                                           comment '来源url',
user_agent                                        comment 'UA',
p_utm_source                                      comment '首次广告系列来源',
op_type                                           comment '留电位置',
track_type                                        comment '埋点类型(计算属性)：1 新埋点 2 神策埋点 3 旧埋点',
is_new_order                                      comment '是否为新订单',
channel_put                                       comment '推广渠道',
login_state                                       comment '登录状态',
button_title                                      comment '按钮名称',
banner_id                                         comment 'BANNER位置',
tab_id                                            comment '标签ID',
leave_phone_state                                 comment '留电状态', 
source                                            comment '联系途径',
operation_type                                    comment '运营位类型', 
operation_position                                comment '运营位置名字', 
abtest_name                                       comment 'AB测试名称', 
abtest_value                                      comment 'AB测试值', 
p_os                                              comment "操作系统，例如IOS",
p_lib_version                                     comment "SDK版本",
p_lib                                             comment "SDK类型，例如PYTHON、IOS等",
p_os_version                                      comment "操作系统版本，例如8.1.1",
p_carrier                                         comment "通信运营商",
login_city_id                                     comment "登录城市ID",
p_latest_referrer                                 comment "站外前向地址",
p_latest_referrer_host                            comment "站外前向域名",
channel_source                                    comment "渠道",
customer_id                                       comment "客户ID",
see_id                                            comment "带看计划ID",
employee_id                                       comment "被赞咨询师ID",
abtest_value1                                     comment "ab测试取值",
abtest_name1                                      comment "ab测试名称",

etl_time                                          comment 'ETL跑数时间',
pdate                                             comment "数据日期",
pplatform                                         comment "产品端分区:101 pc | 102 m | 103 app | 104 miniprogram | 999 other"
) 

as 

select 

skey,
session_id,
prev_event_elapse,
next_event_elapse,
user_access_seq_asc_today,
user_access_seq_desc_today,
global_id,
distinct_id,
map_id,
user_id,
julive_id,
comjia_unique_id,
cookie_id,
open_id,
product_id,
product_name,
track_id,
event,
create_time,
create_timestamp,
recv_time,
fl_project_id,
fl_project_name,
app_id,
p_ip,
idfa,
idfv,
channel_id,
login_employee_id,
project_id,
comjia_android_id,
comjia_device_id,
comjia_imei,
visitor_id,
order_id,
adviser_id,
fromitemindex,
fromitem,
frompage,
topage,
frommodule,
tomodule,
p_is_first_day,
p_is_first_time,
app_version,
p_app_version,
select_city,
lat,
lng,
current_url,
to_url,
referer,
user_agent,
p_utm_source,
op_type,
track_type,
is_new_order,
channel_put,
login_state,
button_title,
banner_id,
tab_id,
leave_phone_state,
source,
operation_type ,
operation_position,
abtest_name,
abtest_value,
get_json_object(properties,$."$os"),
get_json_object(properties,$."$lib_version"),
get_json_object(properties,$."$lib"),
get_json_object(properties,$."$os_version"),
get_json_object(properties,$."$carrier"),
get_json_object(properties,$."login_city_id"),
get_json_object(properties,$."$latest_referrer"),
get_json_object(properties,$."$latest_referrer_host"),
get_json_object(properties,$."channel_source"),
get_json_object(properties,$."customer_id"),
get_json_object(properties,$."see_id"),
get_json_object(properties,$."employee_id"),
get_json_object(properties,$."abtest_value1"),
get_json_object(properties,$."abtest_name1"),

etl_time,
pdate,
pplatform

from julive_fact.fact_event_dtl 
