 

drop view if exists julive_fact.fact_event_dtl_full_view;
create view julive_fact.fact_event_dtl_full_view(

skey                                              comment '记录唯一标识',
session_id                                        comment '默认规则切割session标识:pc-5分钟 m-1分钟 app(视频)-3分钟 小程序-1分钟 其他-不切割session',
prev_event_elapse                                 comment '与上一条事件时间间隔,单位(秒)',
next_event_elapse                                 comment '与下一条事件时间间隔,单位(秒)',
user_access_seq_asc_today                         comment '当天内用户访问行为序列-正序',
user_access_seq_desc_today                        comment '当天内用户访问行为序列-倒序',
global_id                                         comment '全局唯一ID',
distinct_id                                       comment '神策自动生成的用户标识', 
map_id                                            comment '映射id通常和DISTINCT_ID相同',
user_id                                           comment '神策USER_ID',
julive_id                                         comment '居理用户ID',
comjia_unique_id                                  comment '用户ID',
cookie_id                                         comment 'COOKIE ID',
open_id                                           comment '公众号用户唯一标识',
product_id                                        comment '产品ID',
product_name                                      comment '产品名称', -- 由product_id产出 
track_id                                          comment '埋点ID(对应CMS中)',
event                                             comment '事件名称',
create_time                                       comment '事件创建时间(time):yyyy-MM-dd HH:mm:ss',
create_timestamp                                  comment '事件创建原始时间戳',
recv_time                                         comment 'nginx接收时间:yyyy-MM-dd HH:mm:ss',
fl_project_id                                     comment '项目ID',
fl_project_name                                   comment '项目名称',
app_id                                            comment '设备端',
p_ip                                              comment '用户使用设备的 IP',
idfa                                              comment 'IOS设备名',
idfv                                              comment 'IOS设备编号',
channel_id                                        comment '渠道ID',
login_employee_id                                 comment '员工工号',
project_id                                        comment '进入页面前的楼盘ID',
comjia_android_id                                 comment '安卓id设备标识',
comjia_device_id                                  comment '设备id',
comjia_imei                                       comment 'imei-安卓设备标识:coalesce(comjia_imei,imei)',
visitor_id                                        comment '用户id(pc/m=cookie_id/distinct_id app=加密后install_id 小程序=open_id)',
order_id                                          comment '订单ID',
adviser_id                                        comment '咨询师ID',
fromitemindex                                     comment '位置编号',
fromitem                                          comment '按钮',
frompage                                          comment '当前页面',
topage                                            comment '到达页面',
frommodule                                        comment '当前模块',
tomodule                                          comment '到达模块',
p_is_first_day                                    comment '是否首日访问',
p_is_first_time                                   comment '是否首次访问',
app_version                                       comment 'APP版本号:短',
p_app_version                                     comment 'APP版本号',
select_city                                       comment '选择的城市ID',
lat                                               comment '经度',
lng                                               comment '维度',
current_url                                       comment '落地页的URL',
to_url                                            comment '跳转链接',
referer                                           comment '来源url',
user_agent                                        comment 'UA',
p_utm_source                                      comment '首次广告系列来源',
op_type                                           comment '留电位置',
track_type                                        comment '埋点类型(计算属性)：1 新埋点 2 神策埋点 3 旧埋点',
is_new_order                                      comment '是否为新订单',
channel_put                                       comment '推广渠道',
login_state                                       comment '登录状态',
button_title                                      comment '按钮名称',
banner_id                                         comment 'BANNER位置',
tab_id                                            comment '标签ID',
leave_phone_state                                 comment '留电状态', 
source                                            comment '联系途径',
operation_type                                    comment '运营位类型', 
operation_position                                comment '运营位置名字', 
abtest_name                                       comment 'AB测试名称', 
abtest_value                                      comment 'AB测试值', 
p_province                                        comment "用户所在的省份",
p_is_login_id                                     comment "DISTINCT_ID 对应的是否是一个注册 ID",
l_lib_method                                      comment "None",
p_city                                            comment "IP转换得到的城市",
p_country                                         comment "国家",
p_os                                              comment "操作系统，例如IOS",
p_lib_version                                     comment "SDK版本",
p_lib                                             comment "SDK类型，例如PYTHON、IOS等",
p_os_version                                      comment "操作系统版本，例如8.1.1",
p_screen_height                                   comment "屏幕高度",
p_screen_width                                    comment "屏幕宽度",
device_type                                       comment "设备类型",
p_model                                           comment "设备型号，例如IPHONE 8",
p_browser                                         comment "浏览器名称",
p_manufacturer                                    comment "设备制造商，例如APPLE",
p_wifi                                            comment "是否在使用 WIFI",
l_lib_detail                                      comment "None",
p_carrier                                         comment "通信运营商",
p_browser_version                                 comment "浏览器版本",
p_network_type                                    comment "网络类型，例如4G",
city_id                                           comment "城市ID",
l_app_version                                     comment "APP版本",
p_device_id                                       comment "设备ID",
login_city_id                                     comment "登录城市ID",
pixel_height                                      comment "分辨率高度",
pixel_width                                       comment "分辨率宽度",
`role`                                            comment "",
action_time                                       comment "",
app_version_build                                 comment "app-build号",
network_type                                      comment "网络连接类型",
electricity_remain                                comment "剩余电量",
carrier                                           comment "通信运营商",
p_latest_referrer                                 comment "站外前向地址",
p_latest_referrer_host                            comment "站外前向域名",
channel_source                                    comment "渠道",
type                                              comment "需求类型",
media_source                                      comment "媒体来源",
c_adposition                                      comment "展现排名id",
c_creative                                        comment "创意ID",
c_keywordid                                       comment "关键词ID",
c_matchtype                                       comment "匹配方式",
c_pagenum                                         comment "页码",
p_latest_search_keyword                           comment "最近一次搜索引擎关键词",
p_latest_traffic_source_type                      comment "最近一次流量来源类型",
is_login                                          comment "是否登录",
referer_type                                      comment "来源类型",
unique_id                                         comment "用户id",
p_latest_scene                                    comment "最近一次启动场景",
union_id                                          comment "",
p_latest_utm_source                               comment "最近广告系列来源",
order_status                                      comment "预约状态",
department_id                                     comment "None",
employee_leader_id                                comment "None",
project_name                                      comment "楼盘名称",
customer_id                                       comment "客户ID",
order_status_list                                 comment "订单状态",
see_id                                            comment "带看计划ID",
employee_id                                       comment "被赞咨询师ID",
question_id                                       comment "问题ID",
house_type_id                                     comment "跳转前的户型ID",
project_type                                      comment "楼盘类型",
search_condition_list                             comment "",
batch                                             comment "批次",
keywords                                          comment "关键词",
page_type                                         comment "页面样式",
strategy                                          comment "策略",
recall_id                                         comment "召回id",
project_dynamic_id                                comment "楼盘动态ID",
recall_type                                       comment "召回类型",
district                                          comment "区域",
job_number                                        comment "工号",
sale_status                                       comment "销售状态",
click_position                                    comment "点击位置（仅用于方案A）",
page_soure                                        comment "",
in_wechat                                         comment "",
room_size                                         comment "户型",
query                                             comment "清除的内容",
whole_price                                       comment "总价范围,以万为单位,两个数字用逗号分隔",
project_ids                                       comment "浏览过的楼盘",
contact_id                                        comment "联系ID",
video_id                                          comment "视频ID",
proportion                                        comment "面积",
features                                          comment "特色",
report_id                                         comment "报告ID",
`timestamp`                                       comment "",
abtest_value1                                     comment "ab测试取值",
material_id                                       comment "资料ID",
abtest_name1                                      comment "ab测试名称",
input_total_price                                 comment "输入总价,最小最大值之间用逗号分隔",
adviser_comment_id                                comment "点评ID",
deal_id                                           comment "成交id",
area_id                                           comment "区域ID",
is_first_report                                   comment "是否首次报告",
tab_title                                         comment "按钮名称",
subway                                            comment "地铁线路名称",
unit_price                                        comment "单价",
open_source                                       comment "打开入口",
brand_developer                                   comment "品牌开发商",
building_id                                       comment "楼栋 ID",
city                                              comment "城市名",
report_type                                       comment "报告类型",
follow_id                                         comment "跟进ID",
click_type                                        comment "点击类型",
`loop`                                            comment "环线名称",
page                                              comment "页面名",
app_name                                          comment "",
`current_date`                                    comment "None",
subscribe_id                                      comment "认购id",
info_id                                           comment "买房知识文章ID",
p_bot_name                                        comment "",
tag_title                                         comment "标签名称",
deal_case_id                                      comment "成交故事ID",
comment_id                                        comment "评论_ID",
play_time_all                                     comment "总播放时长",
answer_id                                         comment "问答ID",
periphery_type                                    comment "周边类型",
video_time                                        comment "视频总时长",
task_type                                         comment "任务类型",
datetime_max                                      comment "",
datetime_min                                      comment "",
title                                             comment "按钮名称",
house_type                                        comment "户型",
abtest_value2                                     comment "",
net_id                                            comment "",
abtest_name2                                      comment "",
rank_type                                         comment "排行榜类型",
channel_name                                      comment "",
journey_id                                        comment "行程_ID",
is_calling                                        comment "是否正在通话中",
status                                            comment "设置状态",
article_type                                      comment "文章类型",
rank_region                                       comment "排行榜区域",
msg                                               comment "选择的内容",
activity_id                                       comment "活动ID",
activity_title                                    comment "活动标题",
window_type                                       comment "弹窗类型",
user_mobile_list                                  comment "",
input_unit_price                                  comment "输入单价",
state                                             comment "",
customer_pool_type                                comment "",
task_datetime                                     comment "None",
abtest_value3                                     comment "",
sector_id                                         comment "板块 ID",
paihao_id                                         comment "",
abtest_name3                                      comment "",
view_time                                         comment "浏览时长",
task_status                                       comment "None",
article_card_id                                   comment "好文ID",
transaction_number                                comment "None",
is_first_open                                     comment "是否首次录入需求",
district_name                                     comment "区域名称",
from_page_id                                      comment "来源落地页ID",
from_step                                         comment "进度条",
user_realname_list                                comment "",
sequence_id                                       comment "顺序ID",
total_price                                       comment "总价,以万为单位,最小最大值之间用逗号分隔",
p_url_path                                        comment "",
reward_money                                      comment "打赏金额",
deal_status                                       comment "None",
abtest_value4                                     comment "",
house_type_ids                                    comment "浏览过的户型",
pool_user_id                                      comment "",
grass_id                                          comment "",
abtest_name4                                      comment "",
frompage_id                                       comment "None",
is_cooperate                                      comment "是否合作",
p_user_agent                                      comment "None",
content_category                                  comment "内容类别",
tag_id                                            comment "标签ID",
operation_index                                   comment "运营位置编号",
input_proportion                                  comment "输入面积",
budget                                            comment "预算,以万为单位",
filter_sort                                       comment "筛选区_筛选按钮",
article_id                                        comment "文章 ID",
p_title                                           comment "",
house_id                                          comment "房源ID",
play_time                                         comment "每次视频暂停间隔时间",
question_contents                                 comment "问题内容",
wechat_authorization                              comment "微信授权状态",
module_type                                       comment "模块类型",
is_have_video                                     comment "是否有视频",
service_id                                        comment "客服ID",
picture_type_id                                   comment "图片类型",
total_price_max                                   comment "最高总价",
p_screen_name                                     comment "",
total_price_min                                   comment "最低总价",
rewindow_type                                     comment "二次确认弹窗类型",
is_julive                                         comment "是否自营房源",
is_main_push                                      comment "是否主推房源",
content_id                                        comment "内容ID",
village_id                                        comment "小区ID",
result_id                                         comment "结果ID",
show_state                                        comment "",
p_event_duration                                  comment "",
abtest_value8                                     comment "",
p_short_url_key                                   comment "",
ranking_list_name                                 comment "楼盘分类名称",
project_dynamic_ids                               comment "动态ID",
special_room_id                                   comment "特价房ID",
abtest_name8                                      comment "",
to_step                                           comment "到达的步骤",
p_short_url_target                                comment "",
sign                                              comment "",
transfer_info_id                                  comment "交房信息ID",
rank_condition                                    comment "None",
user_phone                                        comment "客户的绑定号码",
traceAvailable                                    comment "网络是否正常",
operation_king_id                                 comment "金刚ID",
article_title_id                                  comment "None",
license_id                                        comment "证件信息ID",
total_budget                                      comment "总价预算",
traceNetwork                                      comment "当前网络类型",
push_id                                           comment "",
button_ids                                        comment "按钮ID",
tag_type                                          comment "标签类型",
project_review                                    comment "",
info_flow_id                                      comment "点击前滚动的信息流ID",
recorder_id                                       comment "None",
sex                                               comment "性别",
task_id                                           comment "任务ID",
isEsaTrace                                        comment "None",
component_id                                      comment "组件ID",
special_car_new                                   comment "有无专车",
tag                                               comment "标签名称",
plan_real_datetime                                comment "联系时间",
p_share_depth                                     comment "",
firstpage                                         comment "打赏入口页面",
component_remarks                                 comment "组件备注",
latitude                                          comment "纬度",
select_status                                     comment "勾选状态",
audit_status                                      comment "",
component_style                                   comment "组件风格",
p_utm_campaign                                    comment "首次广告系列名称",
longitude                                         comment "经度",
send_again                                        comment "是否发送再次发送给客户",
entry_type                                        comment "入口类型",
plate_result                                      comment "板块_选择结果",
is_update_user_phone                              comment "是否更改客户的号码绑定信息",
p_utm_matching_type                               comment "",
update_datetime                                   comment "",
sms_result                                        comment "None",
other_requirement                                 comment "特殊要求",
from_op_type                                      comment "上一弹层，确认留电弹层的OP_TYPE",
work_addr_province                                comment "None",
see_house_time                                    comment "看房时间",
appid                                             comment "",
isCalled                                          comment "None",
search_result_type                                comment "搜索结果样式",
error                                             comment "None",
p_utm_medium                                      comment "首次广告系列媒介",
filter_sort_value                                 comment "户型分析_筛选",
isCalleding                                       comment "None",
house_home_app_download                           comment "户型详情页的遮挡",
building_saling_status                            comment "楼栋销售状态",
p_referrer                                        comment "",
p_utm_term                                        comment "首次广告系列字词",
url                                               comment "",
`sort`                                            comment "分类",
agency                                            comment "",
send_type                                         comment "发送类型",
filter_type                                       comment "筛选类型",
isCalledRinging                                   comment "None",
phone                                             comment "None",
focus_point_new                                   comment "None",
action                                            comment "动作",
surround_type                                     comment "周边类型",
is_full_screen                                    comment "是否全屏",
contact_emoloyee_id                               comment "联系人",
p_scene                                           comment "",
app_type                                          comment "",
isCaller                                          comment "None",
phone_content                                     comment "编译后的手机号",
img_url                                           comment "图片链接地址",
test_standard                                     comment "考试标准",
esa_error_message                                 comment "None",
p_matched_key                                     comment "",
akey                                              comment "",
like_action                                       comment "点赞状态",
gender                                            comment "性别",
button_name_test                                  comment "导航栏名称AB测试",
push_type                                         comment "",
isCallerRinging                                   comment "None",
step                                              comment "",
order_plan_status                                 comment "",
wen_title                                         comment "文章标题",
url_name                                          comment "",
begin_time                                        comment "None",
speak_standard                                    comment "讲盘标准",
isCalling                                         comment "None",
screen_content                                    comment "筛选的内容",
audio_id                                          comment "",
feedback_content                                  comment "反馈内容",
user_comment_app_download                         comment "用户点评页面的遮挡",
click_id                                          comment "",
advertiser_id                                     comment "",
user_comment_id                                   comment "点评ID",
abtest_value5                                     comment "",
record_file_url                                   comment "None",
esa_message                                       comment "None",
input                                             comment "None",
report_project_id                                 comment "None",
abtest_name5                                      comment "",
special_price                                     comment "特价",
ip_type                                           comment "",
qa_card_style                                     comment "",
meet_address_new                                  comment "约见地点",
abtest_value6                                     comment "",
is_security                                       comment "是否安全购",
p_share_distinct_id                               comment "",
is_first_call                                     comment "是OR否选项",
time_online                                       comment "",
work_addr_city                                    comment "None",
mute_status                                       comment "静音状态",
abtest_name6                                      comment "",
to_project_id                                     comment "跳转后楼盘ID",
news_id                                           comment "热门看点ID",
tag_name                                          comment "标签名称",
isSuccess                                         comment "None",
p_share_url_path                                  comment "",
area_result                                       comment "区域_选择结果",
sms_id                                            comment "None",
original_price                                    comment "原价",
work_addr_district                                comment "None",
nearby                                            comment "附近公里数",
deal_type                                         comment "",
p_utm_content                                     comment "首次广告系列内容",
room_number                                       comment "房号",
pause_action                                      comment "暂停动作",
FirstUseTime                                      comment "",
qa_task_completed                                 comment "",
is_3_twice_pop_up                                 comment "是否弹出3次楼盘未变更的弹层",
search_keyword                                    comment "搜索关键词",
code                                              comment "码",
mms_sent_status                                   comment "None",
submit_state                                      comment "提交状态",
img_id                                            comment "楼盘图片ID",
region_id                                         comment "区域_ID",
deal_validity                                     comment "",
return_msg                                        comment "None",
background_duration_102                           comment "None",
connect_time                                      comment "None",
subway_line                                       comment "地铁站线",
exception                                         comment "None",
certification_input_state                         comment "验证码是否正确",
choose_time                                       comment "None",
user_navigation_id                                comment "我的页面宫格ID",
payment                                           comment "",
hot_query_name                                    comment "热门搜索词",
receiver                                          comment "None",
is_open_notice                                    comment "是否打开推送权限",
send_qa_state                                     comment "",
note                                              comment "",
first_stage_id                                    comment "None",
taxi_channel_type                                 comment "None",
qa_task_total                                     comment "",
is_activated                                      comment "是否激活",
collection_action                                 comment "收藏状态",
mobile                                            comment "",
access_token                                      comment "",
submit_time                                       comment "提交时间",
platform_id                                       comment "分享平台",
img_type_id                                       comment "图片类型ID,如效果图、环境规划图",
register_user_id                                  comment "",
is_video_play                                     comment "视频是否播放",
project_dynamic_type                              comment "楼盘动态类型",
channel                                           comment "",
leave_phone_window_style                          comment "留电弹层样式",
delay_time                                        comment "",
uploadTime                                        comment "None",
sms_time                                          comment "None",
is_first_play                                     comment "",
contact_datetime_max                              comment "",
adviser_goal_datetime                             comment "",
zoom_type                                         comment "缩小或放大",
net_datetime                                      comment "",
subway_station_name                               comment "地铁站名",
send_state                                        comment "发送状态",
notice_status                                     comment "",
approximate_house_number                          comment "近似户型推荐的数量",
tag_title_id                                      comment "",
room_type                                         comment "户型",
main_navigation_id                                comment "运营ID",
stackTraceString                                  comment "None",
drag_action                                       comment "拖拽动作",
receive_state                                     comment "None",
is_pass                                           comment "是否通过",
ts                                                comment "None",
release_time                                      comment "None",
floor                                             comment "楼层",
article_title                                     comment "None",
test_speak                                        comment "是否需要讲盘和考试都通过",
visit_time                                        comment "None",
is_adviser_phone                                  comment "是否是咨询师电话",
search_type                                       comment "",
comjia_user_id                                    comment "",
module                                            comment "",
error_code                                        comment "错误码",
acreage                                           comment "面积",
call_400                                          comment "文案AB测试",
subscribe_datetime                                comment "",
play_action                                       comment "播放暂停动作",
net_employee_id                                   comment "",
sure_method                                       comment "确认途径",
install_id                                        comment "",
level                                             comment "所属层级",
pageName                                          comment "",
top_category                                      comment "一级分类名称",
rank_conditon                                     comment "None",
before_result_update                              comment "提交时的楼盘数量",
contact_datetime_min                              comment "",
see_num                                           comment "None",
traceMsg                                          comment "轨迹回调消息",
recommend_module                                  comment "推荐模块",
no_match                                          comment "",
pulldown_state                                    comment "下拉状态",
p_channel_extra_information                       comment "None",
sales_mobile                                      comment "",
drag_time                                         comment "拖拽时长",
business_list_number                              comment "成交单编号",
p_resume_from_background                          comment "",
subscribe_datetime_max                            comment "",
release_time_max                                  comment "发布任务结束时间",
deal_case_ids                                     comment "成交故事ID",
order_close_cause                                 comment "",
p_track_signup_original_id                        comment "None",
test_stage                                        comment "考试阶段",
secondary_category                                comment "二级分类名称",
module_name                                       comment "模块名称",
esa_clear_record_type                             comment "None",
call_duration                                     comment "None",
agent                                             comment "",
see_project_name                                  comment "",
project_list_module                               comment "",
intent_employee_id                                comment "",
return_status                                     comment "None",
device_id                                         comment "",
sort_rule_name                                    comment "排序规则名称",
`function`                                        comment "板块/页面/功能",
rank_data                                         comment "",
exceptionMessage                                  comment "None",
recommend_sort                                    comment "推荐排序位置",
number_before                                     comment "刚开始的楼盘数量",
find_house_scrip_test                             comment "找房功能的文案测试",
click_abandon_button                              comment "是否点击过取消按钮",
user_type                                         comment "",
medal                                             comment "",
house_number                                      comment "",
call_result                                       comment "None",
subscribe_datetime_min                            comment "",
type_name                                         comment "类别名称",
release_time_min                                  comment "发布任务开始时间",
sign_datetime_max                                 comment "",
order_intent                                      comment "",
p_url                                             comment "",
follow_action                                     comment "关注动作",
wechat_data_size                                  comment "None",
is_comment                                        comment "None",
secondclass_id                                    comment "二级分类ID",
contact_employee_id                               comment "",
exceptionTime                                     comment "None",
see_result_update                                 comment "带看结果变更",
system_msg_content                                comment "",
intent_low_reason                                 comment "关闭订单原因",
revisit_or_not                                    comment "None",
cheat_number                                      comment "疑似刷量的号码（编译处理）",
device_os_version                                 comment "",
speak_stage                                       comment "讲盘阶段",
page_state                                        comment "",
is_passed                                         comment "None",
traceStatus                                       comment "轨迹回调状态码",
number_submit                                     comment "提交时的楼盘数量",
find_house_step0_test                             comment "找房功能STEP0弹层有无测试",
click_category_name                               comment "分类名称",
use_car_config_id                                 comment "None",
schedule_type                                     comment "日程类型",
medal_id                                          comment "徽章ID",
esa_is_alarm_running                              comment "None",
`index`                                           comment "直击结果",
can_alloc                                         comment "",
type_title                                        comment "切换到的图片分类名称",
remarks                                           comment "备注",
lastMD5                                           comment "None",
sign_datetime_min                                 comment "",
deal_money                                        comment "",
assign_type                                       comment "订单分配类型",
thumb_number                                      comment "点赞数量",
question_ids                                      comment "问题ID",
is_confirm                                        comment "确认还是放弃",
second_stage_id                                   comment "None",
rank_time                                         comment "",
is_invite                                         comment "None",
alerting_time                                     comment "None",
intent_project_id                                 comment "",
check_state                                       comment "勾选状态",
list_type                                         comment "",
stop_guest                                        comment "是否停上户",
button_type                                       comment "None",
is_pause_follow                                   comment "None",
traceTime                                         comment "事件发生时间",
service_state                                     comment "None",
num_page                                          comment "None",
find_house_step4_test                             comment "找房功能STEP4测试",
p_second_msg                                      comment "",
click_content_position                            comment "点击内容位置",
version                                           comment "",
question_list                                     comment "问答列表",
msg_id                                            comment "",
esa_is_market_running                             comment "None",
uid                                               comment "None",
lastUploadTime                                    comment "None",
sign_intent                                       comment "",
follow_type                                       comment "None",
comment_status                                    comment "评价状态",
thumb_status                                      comment "点赞状态",
speak_time                                        comment "发送时长",
is_issued                                         comment "是否下发服务",
contact_information                               comment "联系方式",
net_num                                           comment "None",
alloc_datetime_max                                comment "",
tab_type                                          comment "TAB 类型",
invitation_employee_id                            comment "",
choice_ids                                        comment "选项ID",
disk_remain                                       comment "剩余存储空间",
belong_project_type                               comment "所属楼盘类型",
called                                            comment "None",
is_related_phone                                  comment "是否关联过手机号",
opening_info_id                                   comment "开盘信息ID",
finish_back_time                                  comment "",
p_second_title                                    comment "",
p_element_content                                 comment "",
question_type                                     comment "",
see_adviser_leader                                comment "",
msg_title                                         comment "",
esa_is_wechat_running                             comment "None",
car_user_name                                     comment "",
undefined                                         comment "",
report_ids                                        comment "报告ID",
last_login_ip                                     comment "",
sign_type                                         comment "",
deal_step                                         comment "",
`from`                                            comment "",
audio_status                                      comment "None",
belong_sale_status                                comment "所属售卖状态",
to_house_type_id                                  comment "跳转后户型ID",
real_content                                      comment "",
see_status                                        comment "None",
contact_status                                    comment "",
net_status                                        comment "",
feedback_selection                                comment "None",
alloc_datetime_min                                comment "",
None                                              comment "None",
property_type                                     comment "房屋类型",
re_incustomer                                     comment "客户再上户可能性",
login_status                                      comment "登录状态",
disk_summary                                      comment "总存储空间",
click_num                                         comment "点击次数",
p_element_id                                      comment "None",
search_content                                    comment "搜索内容",
study_name                                        comment "指定学习人",
id_type                                           comment "",
caller                                            comment "None",
is_replay                                         comment "是否是重播",
shanghu_cause_type                                comment "上户关闭原因",
task_num                                          comment "None",
qa_card_location                                  comment "",
isInitTrace                                       comment "None",
audit_refuse_msg                                  comment "None",
time_offline                                      comment "",
wlan_mac                                          comment "",
see_datetime_max                                  comment "",
music_index                                       comment "",
subscribe_num                                     comment "None",
position                                          comment "",
cause_reason                                      comment "放弃原因",
size                                              comment "None",
order_stauts                                      comment "None",
login_window_style                                comment "登录弹窗类型",
distribute_time                                   comment "",
have_confirm_sheet                                comment "None",
to_page_type                                      comment "页面样式",
reason                                            comment "原因",
newMD5                                            comment "None",
feedback_type                                     comment "投诉类型",
alloc_num                                         comment "None",
user_identity_number                              comment "",
re_intent                                         comment "None",
isMemoryCache                                     comment "None",
p_element_position                                comment "None",
employee_leader_realname                          comment "None",
study_stage                                       comment "学习阶段",
plan_real_datetime_end                            comment "",
traceType                                         comment "",
image_requ_id                                     comment "图片热区ID",
record_type                                       comment "后续动作",
caller_out_time                                   comment "None",
area_name                                         comment "区域名称",
shanghu_status                                    comment "None",
open_type                                         comment "打开还是关闭",
task_states                                       comment "任务状态",
sms_content                                       comment "None",
orientations                                      comment "朝向",
fromStartTrace                                    comment "None",
see_datetime_min                                  comment "",
subscribe_status                                  comment "",
esa_record_file_name                              comment "None",
pre_confirm                                       comment "是否和客户提前确认",
adviser_comment_ids                               comment "咨询师点评ID",
input_keyword                                     comment "输入关键词",
cause_type                                        comment "放弃选项",
leave_phone_datetime                              comment "None",
proposal_content                                  comment "建议内容",
user_mobile                                       comment "",
password                                          comment "None",
header_manage                                     comment "咨询主管",
bubble_type                                       comment "气泡类型",
sender                                            comment "None",
filter_artcle                                     comment "",
choose_range                                      comment "None",
share_type                                        comment "分享类型",
qa_tag                                            comment "问答标签",
mms_sent_data                                     comment "None",
p_element_type                                    comment "None",
employee_name                                     comment "",
abtest_value7                                     comment "",
style_abtest_value                                comment "",
plan_real_datetime_start                          comment "",
trade_area                                        comment "商圈",
image_requ_name                                   comment "图片热区名称",
caller_type                                       comment "None",
is_success                                        comment "是否成功",
from_click_button                                 comment "找房功能的入口位置",
q_type                                            comment "问答类型",
background_duration                               comment "None",
is_first_login                                    comment "是否首次登录",
confirm_review                                    comment "None",
see_employee_name_list                            comment "None",
evaluation_id                                     comment "测评ID",
ceiling_tab_id                                    comment "小程序首页吸顶ID",
tag_sort                                          comment "None",
public_pool_flag                                  comment "将该客户放入客户池",
look_house_time                                   comment "预约看房时间",
district_id                                       comment "区域ID",
abtest_name7                                      comment "",
history_employee_id                               comment "",
to_question_id                                    comment "跳转后的问题ID",
is_match                                          comment "",
countermand_step                                  comment "关闭_途径",
notarize_step                                     comment "确认_途径",
filter_artcle_id                                  comment "观点筛选标签ID",
answer_ids                                        comment "回答ID",
choose_result                                     comment "选择结果",

etl_time                                          comment 'ETL跑数时间',
pdate                                             comment "数据日期",
pplatform                                         comment "产品端分区:101 pc | 102 m | 103 app | 104 miniprogram | 999 other"
) 

as 

select 

skey,
session_id,
prev_event_elapse,
next_event_elapse,
user_access_seq_asc_today,
user_access_seq_desc_today,
global_id,
distinct_id,
map_id,
user_id,
julive_id,
comjia_unique_id,
cookie_id,
open_id,
product_id,
product_name,
track_id,
event,
create_time,
create_timestamp,
recv_time,
fl_project_id,
fl_project_name,
app_id,
p_ip,
idfa,
idfv,
channel_id,
login_employee_id,
project_id,
comjia_android_id,
comjia_device_id,
comjia_imei,
visitor_id,
order_id,
adviser_id,
fromitemindex,
fromitem,
frompage,
topage,
frommodule,
tomodule,
p_is_first_day,
p_is_first_time,
app_version,
p_app_version,
select_city,
lat,
lng,
current_url,
to_url,
referer,
user_agent,
p_utm_source,
op_type,
track_type,
is_new_order,
channel_put,
login_state,
button_title,
banner_id,
tab_id,
leave_phone_state,
source,
operation_type ,
operation_position,
abtest_name,
abtest_value,
get_json_object(regexp_replace(properties,"$","p_"),"$.p_province"),
get_json_object(regexp_replace(properties,"$","p_"),"$.p_is_login_id"),
get_json_object(lib,"$.$lib_method"),
get_json_object(regexp_replace(properties,"$","p_"),"$.p_city"),
get_json_object(regexp_replace(properties,"$","p_"),"$.p_country"),
get_json_object(regexp_replace(properties,"$","p_"),"$.p_os"),
get_json_object(regexp_replace(properties,"$","p_"),"$.p_lib_version"),
get_json_object(regexp_replace(properties,"$","p_"),"$.p_lib"),
get_json_object(regexp_replace(properties,"$","p_"),"$.p_os_version"),
get_json_object(regexp_replace(properties,"$","p_"),"$.p_screen_height"),
get_json_object(regexp_replace(properties,"$","p_"),"$.p_screen_width"),
get_json_object(properties,"$.device_type"),
get_json_object(regexp_replace(properties,"$","p_"),"$.p_model"),
get_json_object(regexp_replace(properties,"$","p_"),"$.p_browser"),
get_json_object(regexp_replace(properties,"$","p_"),"$.p_manufacturer"),
get_json_object(regexp_replace(properties,"$","p_"),"$.p_wifi"),
get_json_object(lib,"$.$lib_detail"),
get_json_object(regexp_replace(properties,"$","p_"),"$.p_carrier"),
get_json_object(regexp_replace(properties,"$","p_"),"$.p_browser_version"),
get_json_object(regexp_replace(properties,"$","p_"),"$.p_network_type"),
get_json_object(properties,"$.city_id"),
get_json_object(lib,"$.$app_version"),
get_json_object(regexp_replace(properties,"$","p_"),"$.p_device_id"),
get_json_object(properties,"$.login_city_id"),
get_json_object(properties,"$.pixel_height"),
get_json_object(properties,"$.pixel_width"),
get_json_object(properties,"$.role"),
get_json_object(properties,"$.action_time"),
get_json_object(properties,"$.app_version_build"),
get_json_object(properties,"$.network_type"),
get_json_object(properties,"$.electricity_remain"),
get_json_object(properties,"$.carrier"),
get_json_object(regexp_replace(properties,"$","p_"),"$.p_latest_referrer"),
get_json_object(regexp_replace(properties,"$","p_"),"$.p_latest_referrer_host"),
get_json_object(properties,"$.channel_source"),
get_json_object(properties,"$.type"),
get_json_object(properties,"$.media_source"),
get_json_object(properties,"$.c_adposition"),
get_json_object(properties,"$.c_creative"),
get_json_object(properties,"$.c_keywordid"),
get_json_object(properties,"$.c_matchtype"),
get_json_object(properties,"$.c_pagenum"),
get_json_object(regexp_replace(properties,"$","p_"),"$.p_latest_search_keyword"),
get_json_object(regexp_replace(properties,"$","p_"),"$.p_latest_traffic_source_type"),
get_json_object(properties,"$.is_login"),
get_json_object(properties,"$.referer_type"),
get_json_object(properties,"$.unique_id"),
get_json_object(regexp_replace(properties,"$","p_"),"$.p_latest_scene"),
get_json_object(properties,"$.union_id"),
get_json_object(regexp_replace(properties,"$","p_"),"$.p_latest_utm_source"),
get_json_object(properties,"$.order_status"),
get_json_object(properties,"$.department_id"),
get_json_object(properties,"$.employee_leader_id"),
get_json_object(properties,"$.project_name"),
get_json_object(properties,"$.customer_id"),
get_json_object(properties,"$.order_status_list"),
get_json_object(properties,"$.see_id"),
get_json_object(properties,"$.employee_id"),
get_json_object(properties,"$.question_id"),
get_json_object(properties,"$.house_type_id"),
get_json_object(properties,"$.project_type"),
get_json_object(properties,"$.search_condition_list"),
get_json_object(properties,"$.batch"),
get_json_object(properties,"$.keywords"),
get_json_object(properties,"$.page_type"),
get_json_object(properties,"$.strategy"),
get_json_object(properties,"$.recall_id"),
get_json_object(properties,"$.project_dynamic_id"),
get_json_object(properties,"$.recall_type"),
get_json_object(properties,"$.district"),
get_json_object(properties,"$.job_number"),
get_json_object(properties,"$.sale_status"),
get_json_object(properties,"$.click_position"),
get_json_object(properties,"$.page_soure"),
get_json_object(properties,"$.in_wechat"),
get_json_object(properties,"$.room_size"),
get_json_object(properties,"$.query"),
get_json_object(properties,"$.whole_price"),
get_json_object(properties,"$.project_ids"),
get_json_object(properties,"$.contact_id"),
get_json_object(properties,"$.video_id"),
get_json_object(properties,"$.proportion"),
get_json_object(properties,"$.features"),
get_json_object(properties,"$.report_id"),
get_json_object(properties,"$.timestamp"),
get_json_object(properties,"$.abtest_value1"),
get_json_object(properties,"$.material_id"),
get_json_object(properties,"$.abtest_name1"),
get_json_object(properties,"$.input_total_price"),
get_json_object(properties,"$.adviser_comment_id"),
get_json_object(properties,"$.deal_id"),
get_json_object(properties,"$.area_id"),
get_json_object(properties,"$.is_first_report"),
get_json_object(properties,"$.tab_title"),
get_json_object(properties,"$.subway"),
get_json_object(properties,"$.unit_price"),
get_json_object(properties,"$.open_source"),
get_json_object(properties,"$.brand_developer"),
get_json_object(properties,"$.building_id"),
get_json_object(properties,"$.city"),
get_json_object(properties,"$.report_type"),
get_json_object(properties,"$.follow_id"),
get_json_object(properties,"$.click_type"),
get_json_object(properties,"$.loop"),
get_json_object(properties,"$.page"),
get_json_object(properties,"$.app_name"),
get_json_object(properties,"$.current_date"),
get_json_object(properties,"$.subscribe_id"),
get_json_object(properties,"$.info_id"),
get_json_object(regexp_replace(properties,"$","p_"),"$.p_bot_name"),
get_json_object(properties,"$.tag_title"),
get_json_object(properties,"$.deal_case_id"),
get_json_object(properties,"$.comment_id"),
get_json_object(properties,"$.play_time_all"),
get_json_object(properties,"$.answer_id"),
get_json_object(properties,"$.periphery_type"),
get_json_object(properties,"$.video_time"),
get_json_object(properties,"$.task_type"),
get_json_object(properties,"$.datetime_max"),
get_json_object(properties,"$.datetime_min"),
get_json_object(properties,"$.title"),
get_json_object(properties,"$.house_type"),
get_json_object(properties,"$.abtest_value2"),
get_json_object(properties,"$.net_id"),
get_json_object(properties,"$.abtest_name2"),
get_json_object(properties,"$.rank_type"),
get_json_object(properties,"$.channel_name"),
get_json_object(properties,"$.journey_id"),
get_json_object(properties,"$.is_calling"),
get_json_object(properties,"$.status"),
get_json_object(properties,"$.article_type"),
get_json_object(properties,"$.rank_region"),
get_json_object(properties,"$.msg"),
get_json_object(properties,"$.activity_id"),
get_json_object(properties,"$.activity_title"),
get_json_object(properties,"$.window_type"),
get_json_object(properties,"$.user_mobile_list"),
get_json_object(properties,"$.input_unit_price"),
get_json_object(properties,"$.state"),
get_json_object(properties,"$.customer_pool_type"),
get_json_object(properties,"$.task_datetime"),
get_json_object(properties,"$.abtest_value3"),
get_json_object(properties,"$.sector_id"),
get_json_object(properties,"$.paihao_id"),
get_json_object(properties,"$.abtest_name3"),
get_json_object(properties,"$.view_time"),
get_json_object(properties,"$.task_status"),
get_json_object(properties,"$.article_card_id"),
get_json_object(properties,"$.transaction_number"),
get_json_object(properties,"$.is_first_open"),
get_json_object(properties,"$.district_name"),
get_json_object(properties,"$.from_page_id"),
get_json_object(properties,"$.from_step"),
get_json_object(properties,"$.user_realname_list"),
get_json_object(properties,"$.sequence_id"),
get_json_object(properties,"$.total_price"),
get_json_object(regexp_replace(properties,"$","p_"),"$.p_url_path"),
get_json_object(properties,"$.reward_money"),
get_json_object(properties,"$.deal_status"),
get_json_object(properties,"$.abtest_value4"),
get_json_object(properties,"$.house_type_ids"),
get_json_object(properties,"$.pool_user_id"),
get_json_object(properties,"$.grass_id"),
get_json_object(properties,"$.abtest_name4"),
get_json_object(properties,"$.frompage_id"),
get_json_object(properties,"$.is_cooperate"),
get_json_object(regexp_replace(properties,"$","p_"),"$.p_user_agent"),
get_json_object(properties,"$.content_category"),
get_json_object(properties,"$.tag_id"),
get_json_object(properties,"$.operation_index"),
get_json_object(properties,"$.input_proportion"),
get_json_object(properties,"$.budget"),
get_json_object(properties,"$.filter_sort"),
get_json_object(properties,"$.article_id"),
get_json_object(regexp_replace(properties,"$","p_"),"$.p_title"),
get_json_object(properties,"$.house_id"),
get_json_object(properties,"$.play_time"),
get_json_object(properties,"$.question_contents"),
get_json_object(properties,"$.wechat_authorization"),
get_json_object(properties,"$.module_type"),
get_json_object(properties,"$.is_have_video"),
get_json_object(properties,"$.service_id"),
get_json_object(properties,"$.picture_type_id"),
get_json_object(properties,"$.total_price_max"),
get_json_object(regexp_replace(properties,"$","p_"),"$.p_screen_name"),
get_json_object(properties,"$.total_price_min"),
get_json_object(properties,"$.rewindow_type"),
get_json_object(properties,"$.is_julive"),
get_json_object(properties,"$.is_main_push"),
get_json_object(properties,"$.content_id"),
get_json_object(properties,"$.village_id"),
get_json_object(properties,"$.result_id"),
get_json_object(properties,"$.show_state"),
get_json_object(regexp_replace(properties,"$","p_"),"$.p_event_duration"),
get_json_object(properties,"$.abtest_value8"),
get_json_object(regexp_replace(properties,"$","p_"),"$.p_short_url_key"),
get_json_object(properties,"$.ranking_list_name"),
get_json_object(properties,"$.project_dynamic_ids"),
get_json_object(properties,"$.special_room_id"),
get_json_object(properties,"$.abtest_name8"),
get_json_object(properties,"$.to_step"),
get_json_object(regexp_replace(properties,"$","p_"),"$.p_short_url_target"),
get_json_object(properties,"$.sign"),
get_json_object(properties,"$.transfer_info_id"),
get_json_object(properties,"$.rank_condition"),
get_json_object(properties,"$.user_phone"),
get_json_object(properties,"$.traceAvailable"),
get_json_object(properties,"$.operation_king_id"),
get_json_object(properties,"$.article_title_id"),
get_json_object(properties,"$.license_id"),
get_json_object(properties,"$.total_budget"),
get_json_object(properties,"$.traceNetwork"),
get_json_object(properties,"$.push_id"),
get_json_object(properties,"$.button_ids"),
get_json_object(properties,"$.tag_type"),
get_json_object(properties,"$.project_review"),
get_json_object(properties,"$.info_flow_id"),
get_json_object(properties,"$.recorder_id"),
get_json_object(properties,"$.sex"),
get_json_object(properties,"$.task_id"),
get_json_object(properties,"$.isEsaTrace"),
get_json_object(properties,"$.component_id"),
get_json_object(properties,"$.special_car_new"),
get_json_object(properties,"$.tag"),
get_json_object(properties,"$.plan_real_datetime"),
get_json_object(regexp_replace(properties,"$","p_"),"$.p_share_depth"),
get_json_object(properties,"$.firstpage"),
get_json_object(properties,"$.component_remarks"),
get_json_object(properties,"$.latitude"),
get_json_object(properties,"$.select_status"),
get_json_object(properties,"$.audit_status"),
get_json_object(properties,"$.component_style"),
get_json_object(regexp_replace(properties,"$","p_"),"$.p_utm_campaign"),
get_json_object(properties,"$.longitude"),
get_json_object(properties,"$.send_again"),
get_json_object(properties,"$.entry_type"),
get_json_object(properties,"$.plate_result"),
get_json_object(properties,"$.is_update_user_phone"),
get_json_object(regexp_replace(properties,"$","p_"),"$.p_utm_matching_type"),
get_json_object(properties,"$.update_datetime"),
get_json_object(properties,"$.sms_result"),
get_json_object(properties,"$.other_requirement"),
get_json_object(properties,"$.from_op_type"),
get_json_object(properties,"$.work_addr_province"),
get_json_object(properties,"$.see_house_time"),
get_json_object(properties,"$.appid"),
get_json_object(properties,"$.isCalled"),
get_json_object(properties,"$.search_result_type"),
get_json_object(properties,"$.error"),
get_json_object(regexp_replace(properties,"$","p_"),"$.p_utm_medium"),
get_json_object(properties,"$.filter_sort_value"),
get_json_object(properties,"$.isCalleding"),
get_json_object(properties,"$.house_home_app_download"),
get_json_object(properties,"$.building_saling_status"),
get_json_object(regexp_replace(properties,"$","p_"),"$.p_referrer"),
get_json_object(regexp_replace(properties,"$","p_"),"$.p_utm_term"),
get_json_object(properties,"$.url"),
get_json_object(properties,"$.sort"),
get_json_object(properties,"$.agency"),
get_json_object(properties,"$.send_type"),
get_json_object(properties,"$.filter_type"),
get_json_object(properties,"$.isCalledRinging"),
get_json_object(properties,"$.phone"),
get_json_object(properties,"$.focus_point_new"),
get_json_object(properties,"$.action"),
get_json_object(properties,"$.surround_type"),
get_json_object(properties,"$.is_full_screen"),
get_json_object(properties,"$.contact_emoloyee_id"),
get_json_object(regexp_replace(properties,"$","p_"),"$.p_scene"),
get_json_object(properties,"$.app_type"),
get_json_object(properties,"$.isCaller"),
get_json_object(properties,"$.phone_content"),
get_json_object(properties,"$.img_url"),
get_json_object(properties,"$.test_standard"),
get_json_object(properties,"$.esa_error_message"),
get_json_object(regexp_replace(properties,"$","p_"),"$.p_matched_key"),
get_json_object(properties,"$.akey"),
get_json_object(properties,"$.like_action"),
get_json_object(properties,"$.gender"),
get_json_object(properties,"$.button_name_test"),
get_json_object(properties,"$.push_type"),
get_json_object(properties,"$.isCallerRinging"),
get_json_object(properties,"$.step"),
get_json_object(properties,"$.order_plan_status"),
get_json_object(properties,"$.wen_title"),
get_json_object(properties,"$.url_name"),
get_json_object(properties,"$.begin_time"),
get_json_object(properties,"$.speak_standard"),
get_json_object(properties,"$.isCalling"),
get_json_object(properties,"$.screen_content"),
get_json_object(properties,"$.audio_id"),
get_json_object(properties,"$.feedback_content"),
get_json_object(properties,"$.user_comment_app_download"),
get_json_object(properties,"$.click_id"),
get_json_object(properties,"$.advertiser_id"),
get_json_object(properties,"$.user_comment_id"),
get_json_object(properties,"$.abtest_value5"),
get_json_object(properties,"$.record_file_url"),
get_json_object(properties,"$.esa_message"),
get_json_object(properties,"$.input"),
get_json_object(properties,"$.report_project_id"),
get_json_object(properties,"$.abtest_name5"),
get_json_object(properties,"$.special_price"),
get_json_object(properties,"$.ip_type"),
get_json_object(properties,"$.qa_card_style"),
get_json_object(properties,"$.meet_address_new"),
get_json_object(properties,"$.abtest_value6"),
get_json_object(properties,"$.is_security"),
get_json_object(regexp_replace(properties,"$","p_"),"$.p_share_distinct_id"),
get_json_object(properties,"$.is_first_call"),
get_json_object(properties,"$.time_online"),
get_json_object(properties,"$.work_addr_city"),
get_json_object(properties,"$.mute_status"),
get_json_object(properties,"$.abtest_name6"),
get_json_object(properties,"$.to_project_id"),
get_json_object(properties,"$.news_id"),
get_json_object(properties,"$.tag_name"),
get_json_object(properties,"$.isSuccess"),
get_json_object(regexp_replace(properties,"$","p_"),"$.p_share_url_path"),
get_json_object(properties,"$.area_result"),
get_json_object(properties,"$.sms_id"),
get_json_object(properties,"$.original_price"),
get_json_object(properties,"$.work_addr_district"),
get_json_object(properties,"$.nearby"),
get_json_object(properties,"$.deal_type"),
get_json_object(regexp_replace(properties,"$","p_"),"$.p_utm_content"),
get_json_object(properties,"$.room_number"),
get_json_object(properties,"$.pause_action"),
get_json_object(properties,"$.FirstUseTime"),
get_json_object(properties,"$.qa_task_completed"),
get_json_object(properties,"$.is_3_twice_pop_up"),
get_json_object(properties,"$.search_keyword"),
get_json_object(properties,"$.code"),
get_json_object(properties,"$.mms_sent_status"),
get_json_object(properties,"$.submit_state"),
get_json_object(properties,"$.img_id"),
get_json_object(properties,"$.region_id"),
get_json_object(properties,"$.deal_validity"),
get_json_object(properties,"$.return_msg"),
get_json_object(properties,"$.background_duration_102"),
get_json_object(properties,"$.connect_time"),
get_json_object(properties,"$.subway_line"),
get_json_object(properties,"$.exception"),
get_json_object(properties,"$.certification_input_state"),
get_json_object(properties,"$.choose_time"),
get_json_object(properties,"$.user_navigation_id"),
get_json_object(properties,"$.payment"),
get_json_object(properties,"$.hot_query_name"),
get_json_object(properties,"$.receiver"),
get_json_object(properties,"$.is_open_notice"),
get_json_object(properties,"$.send_qa_state"),
get_json_object(properties,"$.note"),
get_json_object(properties,"$.first_stage_id"),
get_json_object(properties,"$.taxi_channel_type"),
get_json_object(properties,"$.qa_task_total"),
get_json_object(properties,"$.is_activated"),
get_json_object(properties,"$.collection_action"),
get_json_object(properties,"$.mobile"),
get_json_object(properties,"$.access_token"),
get_json_object(properties,"$.submit_time"),
get_json_object(properties,"$.platform_id"),
get_json_object(properties,"$.img_type_id"),
get_json_object(properties,"$.register_user_id"),
get_json_object(properties,"$.is_video_play"),
get_json_object(properties,"$.project_dynamic_type"),
get_json_object(properties,"$.channel"),
get_json_object(properties,"$.leave_phone_window_style"),
get_json_object(properties,"$.delay_time"),
get_json_object(properties,"$.uploadTime"),
get_json_object(properties,"$.sms_time"),
get_json_object(properties,"$.is_first_play"),
get_json_object(properties,"$.contact_datetime_max"),
get_json_object(properties,"$.adviser_goal_datetime"),
get_json_object(properties,"$.zoom_type"),
get_json_object(properties,"$.net_datetime"),
get_json_object(properties,"$.subway_station_name"),
get_json_object(properties,"$.send_state"),
get_json_object(properties,"$.notice_status"),
get_json_object(properties,"$.approximate_house_number"),
get_json_object(properties,"$.tag_title_id"),
get_json_object(properties,"$.room_type"),
get_json_object(properties,"$.main_navigation_id"),
get_json_object(properties,"$.stackTraceString"),
get_json_object(properties,"$.drag_action"),
get_json_object(properties,"$.receive_state"),
get_json_object(properties,"$.is_pass"),
get_json_object(properties,"$.ts"),
get_json_object(properties,"$.release_time"),
get_json_object(properties,"$.floor"),
get_json_object(properties,"$.article_title"),
get_json_object(properties,"$.test_speak"),
get_json_object(properties,"$.visit_time"),
get_json_object(properties,"$.is_adviser_phone"),
get_json_object(properties,"$.search_type"),
get_json_object(properties,"$.comjia_user_id"),
get_json_object(properties,"$.module"),
get_json_object(properties,"$.error_code"),
get_json_object(properties,"$.acreage"),
get_json_object(properties,"$.call_400"),
get_json_object(properties,"$.subscribe_datetime"),
get_json_object(properties,"$.play_action"),
get_json_object(properties,"$.net_employee_id"),
get_json_object(properties,"$.sure_method"),
get_json_object(properties,"$.install_id"),
get_json_object(properties,"$.level"),
get_json_object(properties,"$.pageName"),
get_json_object(properties,"$.top_category"),
get_json_object(properties,"$.rank_conditon"),
get_json_object(properties,"$.before_result_update"),
get_json_object(properties,"$.contact_datetime_min"),
get_json_object(properties,"$.see_num"),
get_json_object(properties,"$.traceMsg"),
get_json_object(properties,"$.recommend_module"),
get_json_object(properties,"$.no_match"),
get_json_object(properties,"$.pulldown_state"),
get_json_object(regexp_replace(properties,"$","p_"),"$.p_channel_extra_information"),
get_json_object(properties,"$.sales_mobile"),
get_json_object(properties,"$.drag_time"),
get_json_object(properties,"$.business_list_number"),
get_json_object(regexp_replace(properties,"$","p_"),"$.p_resume_from_background"),
get_json_object(properties,"$.subscribe_datetime_max"),
get_json_object(properties,"$.release_time_max"),
get_json_object(properties,"$.deal_case_ids"),
get_json_object(properties,"$.order_close_cause"),
get_json_object(regexp_replace(properties,"$","p_"),"$.p_track_signup_original_id"),
get_json_object(properties,"$.test_stage"),
get_json_object(properties,"$.secondary_category"),
get_json_object(properties,"$.module_name"),
get_json_object(properties,"$.esa_clear_record_type"),
get_json_object(properties,"$.call_duration"),
get_json_object(properties,"$.agent"),
get_json_object(properties,"$.see_project_name"),
get_json_object(properties,"$.project_list_module"),
get_json_object(properties,"$.intent_employee_id"),
get_json_object(properties,"$.return_status"),
get_json_object(properties,"$.device_id"),
get_json_object(properties,"$.sort_rule_name"),
get_json_object(properties,"$.function"),
get_json_object(properties,"$.rank_data"),
get_json_object(properties,"$.exceptionMessage"),
get_json_object(properties,"$.recommend_sort"),
get_json_object(properties,"$.number_before"),
get_json_object(properties,"$.find_house_scrip_test"),
get_json_object(properties,"$.click_abandon_button"),
get_json_object(properties,"$.user_type"),
get_json_object(properties,"$.medal"),
get_json_object(properties,"$.house_number"),
get_json_object(properties,"$.call_result"),
get_json_object(properties,"$.subscribe_datetime_min"),
get_json_object(properties,"$.type_name"),
get_json_object(properties,"$.release_time_min"),
get_json_object(properties,"$.sign_datetime_max"),
get_json_object(properties,"$.order_intent"),
get_json_object(regexp_replace(properties,"$","p_"),"$.p_url"),
get_json_object(properties,"$.follow_action"),
get_json_object(properties,"$.wechat_data_size"),
get_json_object(properties,"$.is_comment"),
get_json_object(properties,"$.secondclass_id"),
get_json_object(properties,"$.contact_employee_id"),
get_json_object(properties,"$.exceptionTime"),
get_json_object(properties,"$.see_result_update"),
get_json_object(properties,"$.system_msg_content"),
get_json_object(properties,"$.intent_low_reason"),
get_json_object(properties,"$.revisit_or_not"),
get_json_object(properties,"$.cheat_number"),
get_json_object(properties,"$.device_os_version"),
get_json_object(properties,"$.speak_stage"),
get_json_object(properties,"$.page_state"),
get_json_object(properties,"$.is_passed"),
get_json_object(properties,"$.traceStatus"),
get_json_object(properties,"$.number_submit"),
get_json_object(properties,"$.find_house_step0_test"),
get_json_object(properties,"$.click_category_name"),
get_json_object(properties,"$.use_car_config_id"),
get_json_object(properties,"$.schedule_type"),
get_json_object(properties,"$.medal_id"),
get_json_object(properties,"$.esa_is_alarm_running"),
get_json_object(properties,"$.index"),
get_json_object(properties,"$.can_alloc"),
get_json_object(properties,"$.type_title"),
get_json_object(properties,"$.remarks"),
get_json_object(properties,"$.lastMD5"),
get_json_object(properties,"$.sign_datetime_min"),
get_json_object(properties,"$.deal_money"),
get_json_object(properties,"$.assign_type"),
get_json_object(properties,"$.thumb_number"),
get_json_object(properties,"$.question_ids"),
get_json_object(properties,"$.is_confirm"),
get_json_object(properties,"$.second_stage_id"),
get_json_object(properties,"$.rank_time"),
get_json_object(properties,"$.is_invite"),
get_json_object(properties,"$.alerting_time"),
get_json_object(properties,"$.intent_project_id"),
get_json_object(properties,"$.check_state"),
get_json_object(properties,"$.list_type"),
get_json_object(properties,"$.stop_guest"),
get_json_object(properties,"$.button_type"),
get_json_object(properties,"$.is_pause_follow"),
get_json_object(properties,"$.traceTime"),
get_json_object(properties,"$.service_state"),
get_json_object(properties,"$.num_page"),
get_json_object(properties,"$.find_house_step4_test"),
get_json_object(properties,"$.p_second_msg"),
get_json_object(properties,"$.click_content_position"),
get_json_object(properties,"$.version"),
get_json_object(properties,"$.question_list"),
get_json_object(properties,"$.msg_id"),
get_json_object(properties,"$.esa_is_market_running"),
get_json_object(properties,"$.uid"),
get_json_object(properties,"$.lastUploadTime"),
get_json_object(properties,"$.sign_intent"),
get_json_object(properties,"$.follow_type"),
get_json_object(properties,"$.comment_status"),
get_json_object(properties,"$.thumb_status"),
get_json_object(properties,"$.speak_time"),
get_json_object(properties,"$.is_issued"),
get_json_object(properties,"$.contact_information"),
get_json_object(properties,"$.net_num"),
get_json_object(properties,"$.alloc_datetime_max"),
get_json_object(properties,"$.tab_type"),
get_json_object(properties,"$.invitation_employee_id"),
get_json_object(properties,"$.choice_ids"),
get_json_object(properties,"$.disk_remain"),
get_json_object(properties,"$.belong_project_type"),
get_json_object(properties,"$.called"),
get_json_object(properties,"$.is_related_phone"),
get_json_object(properties,"$.opening_info_id"),
get_json_object(properties,"$.finish_back_time"),
get_json_object(properties,"$.p_second_title"),
get_json_object(regexp_replace(properties,"$","p_"),"$.p_element_content"),
get_json_object(properties,"$.question_type"),
get_json_object(properties,"$.see_adviser_leader"),
get_json_object(properties,"$.msg_title"),
get_json_object(properties,"$.esa_is_wechat_running"),
get_json_object(properties,"$.car_user_name"),
get_json_object(properties,"$.undefined"),
get_json_object(properties,"$.report_ids"),
get_json_object(properties,"$.last_login_ip"),
get_json_object(properties,"$.sign_type"),
get_json_object(properties,"$.deal_step"),
get_json_object(properties,"$.from"),
get_json_object(properties,"$.audio_status"),
get_json_object(properties,"$.belong_sale_status"),
get_json_object(properties,"$.to_house_type_id"),
get_json_object(properties,"$.real_content"),
get_json_object(properties,"$.see_status"),
get_json_object(properties,"$.contact_status"),
get_json_object(properties,"$.net_status"),
get_json_object(properties,"$.feedback_selection"),
get_json_object(properties,"$.alloc_datetime_min"),
get_json_object(properties,"$.None"),
get_json_object(properties,"$.property_type"),
get_json_object(properties,"$.re_incustomer"),
get_json_object(properties,"$.login_status"),
get_json_object(properties,"$.disk_summary"),
get_json_object(properties,"$.click_num"),
get_json_object(regexp_replace(properties,"$","p_"),"$.p_element_id"),
get_json_object(properties,"$.search_content"),
get_json_object(properties,"$.study_name"),
get_json_object(properties,"$.id_type"),
get_json_object(properties,"$.caller"),
get_json_object(properties,"$.is_replay"),
get_json_object(properties,"$.shanghu_cause_type"),
get_json_object(properties,"$.task_num"),
get_json_object(properties,"$.qa_card_location"),
get_json_object(properties,"$.isInitTrace"),
get_json_object(properties,"$.audit_refuse_msg"),
get_json_object(properties,"$.time_offline"),
get_json_object(properties,"$.wlan_mac"),
get_json_object(properties,"$.see_datetime_max"),
get_json_object(properties,"$.music_index"),
get_json_object(properties,"$.subscribe_num"),
get_json_object(properties,"$.position"),
get_json_object(properties,"$.cause_reason"),
get_json_object(properties,"$.size"),
get_json_object(properties,"$.order_stauts"),
get_json_object(properties,"$.login_window_style"),
get_json_object(properties,"$.distribute_time"),
get_json_object(properties,"$.have_confirm_sheet"),
get_json_object(properties,"$.to_page_type"),
get_json_object(properties,"$.reason"),
get_json_object(properties,"$.newMD5"),
get_json_object(properties,"$.feedback_type"),
get_json_object(properties,"$.alloc_num"),
get_json_object(properties,"$.user_identity_number"),
get_json_object(properties,"$.re_intent"),
get_json_object(properties,"$.isMemoryCache"),
get_json_object(regexp_replace(properties,"$","p_"),"$.p_element_position"),
get_json_object(properties,"$.employee_leader_realname"),
get_json_object(properties,"$.study_stage"),
get_json_object(properties,"$.plan_real_datetime_end"),
get_json_object(properties,"$.traceType"),
get_json_object(properties,"$.image_requ_id"),
get_json_object(properties,"$.record_type"),
get_json_object(properties,"$.caller_out_time"),
get_json_object(properties,"$.area_name"),
get_json_object(properties,"$.shanghu_status"),
get_json_object(properties,"$.open_type"),
get_json_object(properties,"$.task_states"),
get_json_object(properties,"$.sms_content"),
get_json_object(properties,"$.orientations"),
get_json_object(properties,"$.fromStartTrace"),
get_json_object(properties,"$.see_datetime_min"),
get_json_object(properties,"$.subscribe_status"),
get_json_object(properties,"$.esa_record_file_name"),
get_json_object(properties,"$.pre_confirm"),
get_json_object(properties,"$.adviser_comment_ids"),
get_json_object(properties,"$.input_keyword"),
get_json_object(properties,"$.cause_type"),
get_json_object(properties,"$.leave_phone_datetime"),
get_json_object(properties,"$.proposal_content"),
get_json_object(properties,"$.user_mobile"),
get_json_object(properties,"$.password"),
get_json_object(properties,"$.header_manage"),
get_json_object(properties,"$.bubble_type"),
get_json_object(properties,"$.sender"),
get_json_object(properties,"$.filter_artcle"),
get_json_object(properties,"$.choose_range"),
get_json_object(properties,"$.share_type"),
get_json_object(properties,"$.qa_tag"),
get_json_object(properties,"$.mms_sent_data"),
get_json_object(regexp_replace(properties,"$","p_"),"$.p_element_type"),
get_json_object(properties,"$.employee_name"),
get_json_object(properties,"$.abtest_value7"),
get_json_object(properties,"$.style_abtest_value"),
get_json_object(properties,"$.plan_real_datetime_start"),
get_json_object(properties,"$.trade_area"),
get_json_object(properties,"$.image_requ_name"),
get_json_object(properties,"$.caller_type"),
get_json_object(properties,"$.is_success"),
get_json_object(properties,"$.from_click_button"),
get_json_object(properties,"$.q_type"),
get_json_object(properties,"$.background_duration"),
get_json_object(properties,"$.is_first_login"),
get_json_object(properties,"$.confirm_review"),
get_json_object(properties,"$.see_employee_name_list"),
get_json_object(properties,"$.evaluation_id"),
get_json_object(properties,"$.ceiling_tab_id"),
get_json_object(properties,"$.tag_sort"),
get_json_object(properties,"$.public_pool_flag"),
get_json_object(properties,"$.look_house_time"),
get_json_object(properties,"$.district_id"),
get_json_object(properties,"$.abtest_name7"),
get_json_object(properties,"$.history_employee_id"),
get_json_object(properties,"$.to_question_id"),
get_json_object(properties,"$.is_match"),
get_json_object(properties,"$.countermand_step"),
get_json_object(properties,"$.notarize_step"),
get_json_object(properties,"$.filter_artcle_id"),
get_json_object(properties,"$.answer_ids"),
get_json_object(properties,"$.choose_result"),

etl_time,
pdate,
pplatform

from julive_fact.fact_event_dtl 
