drop table if exists julive_fact.fact_consultant_call_dtl;
create table if not exists julive_fact.fact_consultant_call_dtl (
called_id                              int           COMMENT '主键',
recorder_id                            string        COMMENT '本次通话唯一标识',
clue_id                                bigint        COMMENT '线索ID：主键',
employee_id                            bigint        comment '咨询师ID',
employee_name                          string        comment '咨询师姓名',
caller_type                            int           COMMENT '1:主叫人是咨询师，2:主叫人是用户',
alerting_time                          string        COMMENT '被叫振铃时间',
connect_time                           string        COMMENT '被叫接通时刻',
release_time                           string        COMMENT '通话结束时刻',
call_duration                          int           COMMENT '通话时长，秒',
bill_duration                          int           COMMENT '计费时长，秒',
call_cost                              string        COMMENT '本次通话费用，元',
call_result                            string        COMMENT '通话状态',
caller_area                            string        COMMENT '主叫地区',
called_area                            string        COMMENT '被叫地区',
is_valid                               int           COMMENT '是否有效 1 有效，0 无效',
is_first_called                        int           COMMENT '是否是首电(全量数据) 1 首电 0 非首电',
distribute_time                        string        COMMENT '订单分配时间',
distribute_date                        string        comment '订单分配日期',
city_id                                int           COMMENT '线索来源城市ID',
city_name                              string        COMMENT '线索来源城市名称',
city_seq                               string        COMMENT '带开城顺序的线索来源城市名称',
customer_intent_city_id                int           COMMENT '客户意向城市ID',
customer_intent_city_name              string        COMMENT '客户意向城市名称',
customer_intent_city_seq               string        COMMENT '带开城顺序客户意向城市名称',
channel_id                             int           COMMENT '渠道ID',
channel_name                           string        comment '渠道名称',
mgr_city                               string        comment '主城',
region                                 string        comment '所属大区',
city_type                              string        comment '城市类型',
media_id                               int           COMMENT '媒体ID',
media_name                             string        COMMENT '媒体名称',
module_id                              int           COMMENT '模块ID',
module_name                            string        COMMENT '模块名称',
device_id                              int           COMMENT '设备ID',
device_name                            string        COMMENT '设备名称',
full_type                              string        comment '转正类型',
full_type_tc                           string        comment '转正状态',
entry_date                             string        comment '入职日期',
full_date                              string        comment '转正日期',
offjob_date                            string        comment '离职日期',
direct_leader_id                       int           comment '业务发生时员工直接上级id',
team_leader_name                       string        comment '主管',
indirect_leader_id                     int           comment '业务发生时员工直接上级的上级员工ID',
p_leader_name                          string        comment '经理',
dept_id                                string        comment '部门ID',
dept_name                              string        comment '部门名称',
project_type                           string        comment '业态ID',
project_type_name                      string        comment '业态名称',
interest_project                       string        comment '关注楼盘ID列表',
intent_low_time                        string        comment '客户变为无意向时间',
intent_low_date                        string        comment '客户变为无意向日期',
from_source                            int           comment '数据来源: 1-居理数据 2-乌鲁木齐虚拟项目数据 3-二手房中介项目数据 4-加盟商数据',
create_time                            string        comment '通话记录创建时间',
etl_time                               string        comment 'ETL跑数时间'
) COMMENT '咨询师通话明细'
stored as parquet;