CREATE TABLE `julive_fact.fact_event_esf_hour_dtl`(
  `skey` string COMMENT '记录唯一标识', 
  `session_id` string COMMENT '默认规则切割session标识:pc-5分钟 m-1分钟 app(视频)-3分钟 小程序-1分钟 其他-不切割session', 
  `prev_event_elapse` double COMMENT '与上一条事件时间间隔,单位(秒)', 
  `next_event_elapse` double COMMENT '与下一条事件时间间隔,单位(秒)', 
  `user_access_seq_asc_today` int COMMENT '当天内用户访问行为序列-row_number正序', 
  `user_access_seq_desc_today` int COMMENT '当天内用户访问行为序列-row_number倒序', 
  `user_access_seq_asc_today_dr` int COMMENT '当天内用户访问行为序列-dense_rank正序', 
  `user_access_seq_desc_today_dr` int COMMENT '当天内用户访问行为序列-dense_rank倒序', 
  `global_id` string COMMENT '全局用户标识', 
  `distinct_id` string COMMENT '神策自动生成的用户标识', 
  `map_id` string COMMENT '映射id通常和DISTINCT_ID相同', 
  `user_id` string COMMENT '神策USER_ID', 
  `julive_id` string COMMENT '居理用户ID', 
  `comjia_unique_id` string COMMENT '用户ID', 
  `cookie_id` string COMMENT 'COOKIE ID', 
  `open_id` string COMMENT '公众号用户唯一标识', 
  `product_id` string COMMENT '产品ID', 
  `product_name` string COMMENT '产品名称', 
  `track_id` string COMMENT '埋点ID(对应CMS中)', 
  `event` string COMMENT '事件名称', 
  `create_time` string COMMENT '事件创建时间(time):yyyy-MM-dd HH:mm:ss', 
  `create_timestamp` string COMMENT '事件创建原始时间戳', 
  `recv_time` string COMMENT 'nginx接收时间:yyyy-MM-dd HH:mm:ss', 
  `fl_project_id` string COMMENT '项目ID', 
  `fl_project_name` string COMMENT '项目名称', 
  `app_id` string COMMENT '设备端', 
  `p_ip` string COMMENT '用户使用设备的IP', 
  `idfa` string COMMENT 'IOS设备名', 
  `idfv` string COMMENT 'IOS设备编号', 
  `channel_id` string COMMENT '渠道ID', 
  `login_employee_id` string COMMENT '员工工号', 
  `project_id` string COMMENT '进入页面前的楼盘ID', 
  `comjia_android_id` string COMMENT '安卓id设备标识', 
  `comjia_device_id` string COMMENT '设备id', 
  `comjia_imei` string COMMENT 'imei-安卓设备标识:coalesce(comjia_imei,imei)', 
  `visitor_id` string COMMENT '用户id(pc/m=cookie_id/distinct_id app=加密后install_id 小程序=open_id)', 
  `order_id` string COMMENT '订单ID', 
  `adviser_id` string COMMENT '咨询师ID', 
  `fromitemindex` string COMMENT '位置编号', 
  `fromitem` string COMMENT '按钮', 
  `frompage` string COMMENT '当前页面', 
  `topage` string COMMENT '到达页面', 
  `frommodule` string COMMENT '当前模块', 
  `tomodule` string COMMENT '到达模块', 
  `p_is_first_day` string COMMENT '是否首日访问', 
  `p_is_first_time` string COMMENT '是否首次访问', 
  `app_version` string COMMENT 'APP版本号:短', 
  `p_app_version` string COMMENT 'APP版本号', 
  `select_city` string COMMENT '选择的城市ID', 
  `lat` string COMMENT '经度', 
  `lng` string COMMENT '维度', 
  `current_url` string COMMENT '落地页的URL', 
  `to_url` string COMMENT '跳转链接', 
  `referer` string COMMENT '来源url', 
  `user_agent` string COMMENT 'UA', 
  `p_utm_source` string COMMENT '首次广告系列来源', 
  `op_type` string COMMENT '留电位置', 
  `track_type` string COMMENT '埋点类型(计算属性)：1 新埋点 2 神策埋点 3 旧埋点', 
  `is_new_order` string COMMENT '是否为新订单', 
  `channel_put` string COMMENT '推广渠道', 
  `login_state` string COMMENT '登录状态', 
  `button_title` string COMMENT '按钮名称', 
  `banner_id` string COMMENT 'BANNER位置', 
  `tab_id` string COMMENT '标签ID', 
  `leave_phone_state` string COMMENT '留电状态', 
  `source` string COMMENT '联系途径', 
  `operation_type` string COMMENT '运营位类型', 
  `operation_position` string COMMENT '运营位置名字', 
  `abtest_name` string COMMENT 'AB测试名称', 
  `abtest_value` string COMMENT 'AB测试值', 
  `lib` string COMMENT '埋点数据Json', 
  `properties` string COMMENT '埋点数据Json', 
  `etl_time` string COMMENT 'ETL跑数时间')
COMMENT '埋点数据明细事实基表'
PARTITIONED BY ( 
  `pdate` string COMMENT '数据日期', 
  `pplatform` string COMMENT '产品端分区:101 pc | 102 m | 103 app | 104 miniprogram | 999 other', 
  `phour` string COMMENT '小时分区')
ROW FORMAT SERDE 
  'org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe' 
STORED AS INPUTFORMAT 
  'org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat' 
OUTPUTFORMAT 
  'org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat'
LOCATION
  'hdfs://optimuspro01:8020/dw/julive_fact/fact_event_esf_hour_dtl'
TBLPROPERTIES (
  'transient_lastDdlTime'='1583123751')
